begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select ok((select relrowsecurity from pg_class where oid=('fmat.'||t)::regclass),t||' has RLS') from unnest(array['oauth_clients','oauth_authorizations','oauth_budgets']) t;
select ok(not has_table_privilege(r,'fmat.'||t,'select,insert,update,delete'),r||' cannot access '||t) from unnest(array['anon','authenticated','service_role']) r cross join unnest(array['oauth_clients','oauth_authorizations','oauth_budgets']) t;
select ok(has_function_privilege('service_role',f,'execute'),'service can call '||f) from unnest(array['public.fmat_oauth_register(text,text[],text)','public.fmat_oauth_authorization_start(jsonb)','public.fmat_oauth_authorization_read(uuid,text)']) f;
select ok(not has_function_privilege(r,f,'execute'),r||' cannot call '||f) from unnest(array['anon','authenticated']) r cross join unnest(array['public.fmat_oauth_register(text,text[],text)','public.fmat_oauth_authorization_start(jsonb)','public.fmat_oauth_authorization_read(uuid,text)']) f;
select ok(not has_function_privilege(r,'fmat.oauth_take_budget(text)','execute'),r||' cannot reset budgets') from unnest(array['anon','authenticated','service_role']) r;
create temporary table fixture(client_id uuid,authorization_id uuid);
insert into fixture(client_id) select (public.fmat_oauth_register('<untrusted client>',array['https://client.example/cb','http://127.0.0.1:5555/cb'],'https://release.findmeatime.com/mcp')->>'clientId')::uuid;
select is((select name from fmat.oauth_clients where id=(select client_id from fixture)),'<untrusted client>','name stored as untrusted text, never fetched or interpreted');
select is((select count(*)::int from fmat.oauth_authorizations),0,'registration grants no consent');
select is(public.fmat_oauth_register('bad',array['https://client.example/cb','https://client.example/cb'],'https://release.findmeatime.com/mcp')->>'error','invalid_client_metadata','duplicate redirects denied');
select is(public.fmat_oauth_register('bad',array[u],'https://release.findmeatime.com/mcp')->>'error','invalid_client_metadata','unsafe redirect denied: '||u) from unnest(array['http://example.com/cb','https://u@client.example/cb','https://client.example/cb#fragment','http://127.1/cb','http://2130706433/cb','http://localhost.evil/cb','javascript:alert(1)','https://client.example/with space',E'https://client.example/\\path']) u;
select is(public.fmat_oauth_register('bad',array[null::text],'https://release.findmeatime.com/mcp')->>'error','invalid_client_metadata','null redirect denied');
select is(public.fmat_oauth_register(null,array['https://client.example/cb'],'https://release.findmeatime.com/mcp')->>'error','invalid_client_metadata','null name denied');
select is(public.fmat_oauth_register('bad',array['https://client.example/cb'],null)->>'error','invalid_client_metadata','null resource denied');
select is(public.fmat_oauth_register('bad',array['https://client.example/cb'],'https://release.findmeatime.com/mcp?x=/mcp')->>'error','invalid_client_metadata','resource query denied');
create function pg_temp.input(p_patch jsonb default '{}') returns jsonb language sql as $$
 select jsonb_build_object('clientId',client_id,'redirectUri','https://client.example/cb','resource','https://release.findmeatime.com/mcp','scope','host:read host:write','codeChallenge',repeat('A',43),'codeChallengeMethod','S256','state','opaque state','browserHash',repeat('a',64))||p_patch from fixture
$$;
update fixture set authorization_id=(public.fmat_oauth_authorization_start(pg_temp.input())->>'authorizationId')::uuid;
select ok((select authorization_id is not null from fixture),'valid attempt created');
select ok((select expires_at-created_at=interval '10 minutes' and decision is null from fmat.oauth_authorizations),'ten minute pending consent; no authority');
select is(public.fmat_oauth_authorization_start(pg_temp.input('{"resource":"https://other.example/mcp"}'))->>'error','invalid_target','different resource denied');
select is(public.fmat_oauth_authorization_start(pg_temp.input('{"redirectUri":"https://client.example/cb/"}'))->>'error','invalid_request','redirect is exact');
select is(public.fmat_oauth_authorization_start(pg_temp.input(jsonb_build_object('scope',s)))->>'error','invalid_scope','bad scope denied: '||s) from unnest(array['','host:read request:read','host:read host:read','host:write host:read','host:admin','host:read ']) s;
select is(public.fmat_oauth_authorization_start(pg_temp.input('{"codeChallengeMethod":"plain"}'))->>'error','invalid_request','plain PKCE denied');
select is(public.fmat_oauth_authorization_start(pg_temp.input(jsonb_build_object('codeChallenge',repeat('B',43))))->>'error','invalid_request','noncanonical challenge denied');
select is(public.fmat_oauth_authorization_start(pg_temp.input('{"browserHash":"raw-browser-secret"}'))->>'error','invalid_request','raw browser secret denied');
select is(public.fmat_oauth_authorization_start(pg_temp.input('{"scope":null}'))->>'error','invalid_request','null input denied');
select is(public.fmat_oauth_authorization_start(pg_temp.input('{"clientId":"not-a-uuid"}'))->>'error','invalid_request','invalid ID returns error without rolling back budget');
select is(public.fmat_oauth_authorization_start(pg_temp.input('{"clientId":"ffffffff-ffff-4fff-8fff-ffffffffffff"}'))->>'error','invalid_client','unknown client consumes global budget');
select is(public.fmat_oauth_authorization_read(authorization_id,repeat('b',64))->>'error','invalid_request','wrong browser denied') from fixture;
select is(public.fmat_oauth_authorization_read(authorization_id,null)->>'error','invalid_request','missing browser denied') from fixture;
select is(public.fmat_oauth_authorization_read(authorization_id,repeat('a',64))->>'scope','host:read host:write','correct browser sees frozen permissions') from fixture;
select ok(not public.fmat_oauth_authorization_read(authorization_id,repeat('a',64)) ?| array['browserHash','codeChallenge','credential','token','grantId'],'projection contains no credential or grant') from fixture;
update fmat.oauth_clients set disabled_at=clock_timestamp() where id=(select client_id from fixture);
select is(public.fmat_oauth_authorization_read(authorization_id,repeat('a',64))->>'error','invalid_request','disabled client cannot read consent') from fixture;
select is(public.fmat_oauth_authorization_start(pg_temp.input())->>'error','invalid_client','disabled client cannot start');
update fmat.oauth_clients set disabled_at=null,authorization_count=20,authorization_window_at=clock_timestamp();
select is(public.fmat_oauth_authorization_start(pg_temp.input())->>'error','rate_limited','per-client limit enforced');
update fmat.oauth_clients set authorization_window_at=clock_timestamp()-interval '61 seconds';
select ok(public.fmat_oauth_authorization_start(pg_temp.input()) ? 'authorizationId','per-client budget renews after window');
select is((select authorization_count from fmat.oauth_clients),1,'renewed counter starts at one');
update fmat.oauth_authorizations set created_at=statement_timestamp()-interval '11 minutes',expires_at=statement_timestamp()-interval '1 minute' where id=(select authorization_id from fixture);
select is(public.fmat_oauth_authorization_read(authorization_id,repeat('a',64))->>'error','invalid_request','expired browser consent denied') from fixture;
update fmat.oauth_budgets set used=30,window_started_at=clock_timestamp() where name='registration';
select is(public.fmat_oauth_register('blocked',array['https://client.example/cb'],'https://release.findmeatime.com/mcp')->>'error','rate_limited','registration global ceiling');
update fmat.oauth_budgets set window_started_at=clock_timestamp()-interval '61 minutes' where name='registration';
select ok(public.fmat_oauth_register('renewed',array['http://[::1]:1234/cb'],'https://release.findmeatime.com/mcp') ? 'clientId','registration renews and literal IPv6 loopback works');
update fmat.oauth_budgets set used=600,window_started_at=clock_timestamp() where name='authorization';
select is(public.fmat_oauth_authorization_start(pg_temp.input())->>'error','rate_limited','authorization global ceiling');
select is((select used from fmat.oauth_budgets where name='authorization'),600,'rejected attempts cannot overflow counter');
update fmat.oauth_budgets set window_started_at=clock_timestamp()-interval '61 seconds' where name='authorization';
select is(public.fmat_oauth_authorization_start('null')->>'error','invalid_request','invalid request still consumes renewed budget');
select is((select used from fmat.oauth_budgets where name='authorization'),1,'invalid request budget committed');
select is((select count(*)::int from fmat.oauth_budgets),2,'only two global budget records');
select * from finish();
rollback;
