begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values('96000000-0000-4000-8000-000000000001','usage@fixture.test',now());
insert into auth.sessions(id,user_id) values('96000000-0000-4000-8000-000000000002','96000000-0000-4000-8000-000000000001');
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('96000000-0000-4000-8000-000000000003','usage@fixture.test',repeat('f',64),now()+interval '1 day','fixture');
insert into fmat.hosts(id,email,invitation_id) values('96000000-0000-4000-8000-000000000001','usage@fixture.test','96000000-0000-4000-8000-000000000003');
create temporary table fixture(name text primary key,value jsonb);
insert into fixture select 'grant',public.fmat_conversation_access('open',jsonb_build_object('kind','host','subject','96000000-0000-4000-8000-000000000001','sessionId','96000000-0000-4000-8000-000000000002','expiresAt',now()+interval '1 hour'),'{"audience":"host_setup"}');
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;
create function pg_temp.scope() returns uuid language sql as $$select (pg_temp.f('grant')->>'conversationId')::uuid$$;
create function pg_temp.grant_id() returns uuid language sql as $$select (pg_temp.f('grant')->>'grantId')::uuid$$;

insert into fixture select 'message',public.fmat_runtime_message('accept',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('clientId',gen_random_uuid(),'text','Retain token usage'));
create function pg_temp.message() returns uuid language sql as $$select (pg_temp.f('message')->>'id')::uuid$$;
create function pg_temp.usage(i bigint default 0,o bigint default 0,r bigint default 0,w bigint default 0) returns jsonb language sql as $$select jsonb_build_object('inputTokens',i,'outputTokens',o,'cacheReadTokens',r,'cacheWriteTokens',w)$$;
create function pg_temp.reserve(u jsonb,session_id text default 'usage-original') returns jsonb language plpgsql as $$declare receipt jsonb;begin
 receipt:=public.fmat_conversation_model_reserve(pg_temp.grant_id(),pg_temp.scope(),pg_temp.message(),session_id,u);
 perform public.fmat_conversation_model_usage(pg_temp.scope(),pg_temp.message(),session_id,(receipt->>'attemptId')::uuid,pg_temp.usage());return receipt;
end$$;
create function pg_temp.recover(u jsonb) returns jsonb language sql as $$select fmat.conversation_recovery_begin(pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('expectedGeneration',s.runtime_generation,'idempotencyKey',gen_random_uuid(),'evidence',jsonb_build_object('generation',s.runtime_generation,'sessionId',s.runtime_session_id,'eventId','terminal-'||s.runtime_generation,'tailIndex',25,'usage',u))) from fmat.conversation_scopes s where s.id=pg_temp.scope()$$;
select ok(not has_table_privilege(r,t,p),r||' cannot '||p||' '||t) from unnest(array['anon','authenticated','service_role']) r cross join unnest(array['fmat.conversation_model_usage','fmat.conversation_model_receipts']) t cross join unnest(array['SELECT','INSERT','UPDATE','DELETE']) p;
select ok((select relrowsecurity from pg_class where oid='fmat.conversation_model_usage'::regclass),'live usage uses RLS');
select ok(not has_function_privilege(r,f,'EXECUTE'),r||' cannot invoke '||f) from unnest(array['anon','authenticated','service_role']) r cross join unnest(array['fmat.require_model_usage(fmat.conversation_scopes,jsonb)','fmat.conversation_model_reserve(uuid,uuid,uuid,text,jsonb)']) f;
select ok(not has_function_privilege(r,'public.fmat_conversation_model_reserve(uuid,uuid,uuid,text,jsonb)','EXECUTE'),r||' cannot supply trusted usage') from unnest(array['anon','authenticated']) r;
select ok(has_function_privilege('service_role','public.fmat_conversation_model_reserve(uuid,uuid,uuid,text,jsonb)','EXECUTE'),'runtime wrapper is service-only');
select ok(not has_function_privilege(r,'public.fmat_conversation_model_usage(uuid,uuid,text,uuid,jsonb)','EXECUTE'),r||' cannot record model usage') from unnest(array['anon','authenticated']) r;
select ok(has_function_privilege('service_role','public.fmat_conversation_model_usage(uuid,uuid,text,uuid,jsonb)','EXECUTE'),'receipt wrapper is service-only');
select lives_ok($$select public.fmat_runtime_message('deliver',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('messageId',pg_temp.message(),'sessionId','usage-original'))$$,'bind original runtime');
select lives_ok($$select pg_temp.reserve(null)$$,'legacy generation-zero reserve remains compatible');
select lives_ok($$select pg_temp.reserve(pg_temp.usage(10,1,2,3))$$,'record original live totals');
select lives_ok($$select fmat.require_model_usage(s,null) from fmat.conversation_scopes s where id=pg_temp.scope()$$,'legacy absence preserves the recorded generation-zero floor');
select lives_ok($$select fmat.require_model_usage(s,pg_temp.usage(9,1,2,3)) from fmat.conversation_scopes s where id=pg_temp.scope()$$,'stale checkpoint cannot subtract observed usage');
select is((select input_tokens from fmat.conversation_model_usage where conversation_id=pg_temp.scope()),10::bigint,'stale checkpoint retains database floor');
select lives_ok($$select pg_temp.recover(pg_temp.usage(99900,7990,2,3))$$,'retire original usage within allowance');
update fmat.conversation_scopes set runtime_session_id='usage-successor' where id=pg_temp.scope();
update fmat.conversation_generations set runtime_session_id='usage-successor' where conversation_id=pg_temp.scope() and generation=1;
select throws_ok($$select pg_temp.reserve(null,'usage-successor')$$,'P0001','MODEL_LIMIT','successor requires checkpointed live usage');
select throws_ok($$select pg_temp.reserve(pg_temp.usage(),'usage-original')$$,'P0001','FORBIDDEN','retired session cannot spend with fresh usage');
select throws_ok(format('select pg_temp.reserve(%L::jsonb,''usage-successor'')',u),'P0001','INVALID_INPUT','invalid usage denied: '||u::text) from (values ('null'::jsonb),('[]'),('{}'),('{"inputTokens":0}'),('{"inputTokens":0,"outputTokens":0,"cacheReadTokens":0,"cacheWriteTokens":0,"generation":0}')) v(u);
select throws_ok(format('select pg_temp.reserve(jsonb_set(pg_temp.usage(),''{inputTokens}'',%L::jsonb),''usage-successor'')',v),'P0001','INVALID_INPUT','unsafe count denied: '||v::text) from (values ('-1'::jsonb),('0.5'),('9007199254740992'),('null'),('"0"')) x(v);
select lives_ok($$select pg_temp.reserve(pg_temp.usage(),'usage-successor')$$,'successor begins at zero live usage with inherited usage retained');
insert into fixture select 'open_receipt',public.fmat_conversation_model_reserve(pg_temp.grant_id(),pg_temp.scope(),pg_temp.message(),'usage-successor',pg_temp.usage());
select throws_ok($$select pg_temp.reserve(pg_temp.usage(),'usage-successor')$$,'P0001','MODEL_LIMIT','unresolved provider work cannot reopen allowance');
select throws_ok($$select pg_temp.recover(pg_temp.usage())$$,'P0001','MODEL_LIMIT','terminal evidence cannot reset unresolved reported usage');
select throws_ok($$select public.fmat_conversation_model_usage(pg_temp.scope(),gen_random_uuid(),'usage-successor',(pg_temp.f('open_receipt')->>'attemptId')::uuid,pg_temp.usage())$$,'P0001','NOT_FOUND','receipt cannot bind another input');
select lives_ok($$select public.fmat_conversation_model_usage(pg_temp.scope(),pg_temp.message(),'usage-successor',(pg_temp.f('open_receipt')->>'attemptId')::uuid,pg_temp.usage(1,1))$$,'record one actual reported provider use');
select lives_ok($$select public.fmat_conversation_model_usage(pg_temp.scope(),pg_temp.message(),'usage-successor',(pg_temp.f('open_receipt')->>'attemptId')::uuid,pg_temp.usage(1,1))$$,'lost receipt acknowledgment retries exactly');
select throws_ok($$select public.fmat_conversation_model_usage(pg_temp.scope(),pg_temp.message(),'usage-successor',(pg_temp.f('open_receipt')->>'attemptId')::uuid,pg_temp.usage(2,1))$$,'P0001','IDEMPOTENCY_CONFLICT','changed receipt cannot rewrite usage');
select is((select input_tokens from fmat.conversation_model_usage where conversation_id=pg_temp.scope() and generation=1),1::bigint,'receipt retries never duplicate reported usage');

select lives_ok($$select pg_temp.reserve(pg_temp.usage(99,9,4,5),'usage-successor')$$,'remaining allowance can be consumed once');
select throws_ok($$select pg_temp.reserve(pg_temp.usage(100,9,4,5),'usage-successor')$$,'P0001','MODEL_LIMIT','retired plus live input reaches original cap');
select throws_ok($$select pg_temp.reserve(pg_temp.usage(99,10,4,5),'usage-successor')$$,'P0001','MODEL_LIMIT','retired plus live output reaches original cap');
select lives_ok(format('select fmat.require_model_usage(s,%L::jsonb) from fmat.conversation_scopes s where id=pg_temp.scope()',u),'stale counters retain the observed floor') from (values (pg_temp.usage(98,9,4,5)),(pg_temp.usage(99,8,4,5)),(pg_temp.usage(99,9,3,5)),(pg_temp.usage(99,9,4,4))) v(u);
select is((select attempts from fmat.model_work_attempts where name='conversation:'||pg_temp.message()),5,'denied work consumes no new attempt and refunds none');
select is((select input_tokens from fmat.conversation_model_usage where conversation_id=pg_temp.scope() and generation=1),99::bigint,'stale counters do not lower the effective token cap');
select lives_ok($$select pg_temp.recover(pg_temp.usage(99,9,4,5))$$,'second recovery retains near-exhausted usage');
update fmat.conversation_scopes set runtime_session_id='usage-third' where id=pg_temp.scope();
update fmat.conversation_generations set runtime_session_id='usage-third' where conversation_id=pg_temp.scope() and generation=2;
select lives_ok($$select pg_temp.reserve(pg_temp.usage(),'usage-third')$$,'retired high-water floors are not double counted');
select throws_ok($$select pg_temp.reserve(pg_temp.usage(1,0),'usage-third')$$,'P0001','MODEL_LIMIT','third generation cannot reset cumulative input');
select throws_ok($$select pg_temp.reserve(pg_temp.usage(0,1),'usage-third')$$,'P0001','MODEL_LIMIT','third generation cannot reset cumulative output');
create function pg_temp.missing_ledger() returns void language plpgsql as $$begin
 delete from fmat.conversation_recoveries where conversation_id=pg_temp.scope();
 delete from fmat.conversation_generations where conversation_id=pg_temp.scope() and generation=0;
 perform pg_temp.reserve(pg_temp.usage(),'usage-third');
end$$;
select throws_ok($$select pg_temp.missing_ledger()$$,'P0001','MODEL_LIMIT','missing retired usage fails closed');
select is((select sum(input_tokens) from fmat.conversation_generations where conversation_id=pg_temp.scope()),99999::numeric,'retired reported usage remains exact');
update fmat.conversation_grants set revoked_at=clock_timestamp() where id=pg_temp.grant_id();
select throws_ok($$select pg_temp.reserve(pg_temp.usage(),'usage-third')$$,'P0001','UNAUTHORIZED','current participant authority still required');
select * from finish();
rollback;
