begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values('96000000-0000-4000-8000-000000000001','successor@fixture.test',now());
insert into auth.sessions(id,user_id) values('96000000-0000-4000-8000-000000000002','96000000-0000-4000-8000-000000000001');
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('96000000-0000-4000-8000-000000000003','successor@fixture.test',repeat('a',64),now()+interval '1 day','fixture');
insert into fmat.hosts(id,email,invitation_id) values('96000000-0000-4000-8000-000000000001','successor@fixture.test','96000000-0000-4000-8000-000000000003');
create temporary table fixture(name text primary key,value jsonb);
insert into fixture select 'grant',public.fmat_conversation_access('open',jsonb_build_object('kind','host','subject','96000000-0000-4000-8000-000000000001','sessionId','96000000-0000-4000-8000-000000000002','expiresAt',now()+interval '1 hour'),'{"audience":"host_setup"}');
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;
create function pg_temp.scope() returns uuid language sql as $$select (pg_temp.f('grant')->>'conversationId')::uuid$$;
create function pg_temp.grant_id() returns uuid language sql as $$select (pg_temp.f('grant')->>'grantId')::uuid$$;
insert into fixture select 'message',public.fmat_runtime_message('accept',pg_temp.grant_id(),pg_temp.scope(),'{"clientId":"96000000-0000-4000-8000-000000000004","text":"Original pending input"}');
create function pg_temp.call(op text,extra jsonb default '{}') returns jsonb language sql as $$select fmat.conversation_successor(op,pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('generation',1,'messageId',pg_temp.f('message')->>'id')||extra)$$;
select ok(not has_table_privilege(r,'fmat.conversation_successors',p),r||' cannot '||p||' successor records') from unnest(array['anon','authenticated','service_role']) r cross join unnest(array['SELECT','INSERT','UPDATE','DELETE']) p;
select ok(not has_function_privilege(r,'fmat.conversation_successor(text,uuid,uuid,jsonb)','EXECUTE'),r||' cannot activate private successor protocol') from unnest(array['anon','authenticated','service_role']) r;
select ok(not has_function_privilege(r,'public.fmat_runtime_successor(text,uuid,uuid,jsonb)','EXECUTE'),r||' cannot invoke runtime successor wrapper') from unnest(array['anon','authenticated']) r;
select ok(has_function_privilege('service_role','public.fmat_runtime_successor(text,uuid,uuid,jsonb)','EXECUTE'),'service-only runtime wrapper is callable');
select ok((select relrowsecurity from pg_class where oid='fmat.conversation_successors'::regclass),'successor ledger has RLS');
select throws_ok($$select pg_temp.call('claim')$$,'P0001','STALE_REVISION','ordinary generation zero cannot allocate a successor');
select public.fmat_runtime_message('deliver',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('messageId',pg_temp.f('message')->>'id','sessionId','wrun_successor_old'));
select fmat.conversation_recovery_begin(pg_temp.grant_id(),pg_temp.scope(),'{"expectedGeneration":0,"idempotencyKey":"96000000-0000-4000-8000-000000000005","evidence":{"generation":0,"sessionId":"wrun_successor_old","eventId":"terminal","tailIndex":5,"usage":{"inputTokens":100,"outputTokens":10,"cacheReadTokens":0,"cacheWriteTokens":0}}}');
insert into fmat.model_work_attempts values('conversation:'||(pg_temp.f('message')->>'id'),3);
insert into fixture select 'before',jsonb_build_object('message',(select to_jsonb(m) from fmat.runtime_messages m where id=(pg_temp.f('message')->>'id')::uuid),'grant',(select to_jsonb(g) from fmat.conversation_grants g where id=pg_temp.grant_id()));
select throws_ok(format('select pg_temp.call(''claim'',%L::jsonb)',p),'P0001','INVALID_INPUT','strict claim input '||p::text) from (values ('{"generation":0}'::jsonb),('{"generation":1.1}'),('{"generation":9007199254740992}'),('{"generation":null}'),('{"generation":"1"}'),('{"messageId":"bad"}'),('{"sessionId":"caller-runtime"}'),('{"leaseToken":null}')) x(p);
select throws_ok($$select pg_temp.call('unknown')$$,'P0001','INVALID_INPUT','unknown operation denied');
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',gen_random_uuid(),'sessionId','successor'))$$,'P0001','FORBIDDEN','binding before a creation permit denied');
select throws_ok($$select pg_temp.call('start',jsonb_build_object('leaseToken',gen_random_uuid()))$$,'P0001','LEASE_LOST','starting before claim denied');
select throws_ok($$select pg_temp.call('claim',jsonb_build_object('messageId',gen_random_uuid()))$$,'P0001','NOT_FOUND','foreign pending input denied');
select throws_ok(format('select pg_temp.call(''start'',%L::jsonb)',p),'P0001','INVALID_INPUT','strict start input '||p::text) from (values ('{}'::jsonb),('{"leaseToken":null}'),('{"leaseToken":"bad"}'),('{"leaseToken":"96000000-0000-4000-8000-000000000006","force":true}')) x(p);
select throws_ok(format('select pg_temp.call(''bind'',%L::jsonb)',p),'P0001','INVALID_INPUT','strict bind input '||p::text) from (values ('{}'::jsonb),('{"creationKey":null,"sessionId":"x"}'),('{"creationKey":"96000000-0000-4000-8000-000000000006","sessionId":null}'),('{"creationKey":"96000000-0000-4000-8000-000000000006","sessionId":""}'),('{"creationKey":"96000000-0000-4000-8000-000000000006","sessionId":"x","force":true}')) x(p);
-- A completed input cannot cause even a prepared successor record.
update fmat.runtime_messages set status='completed' where id=(pg_temp.f('message')->>'id')::uuid;
select throws_ok($$select pg_temp.call('claim')$$,'P0001','FORBIDDEN','completed input cannot allocate a successor');
select is((select count(*) from fmat.conversation_successors where conversation_id=pg_temp.scope()),0::bigint,'no allocation without eligible pending input');
update fmat.runtime_messages set status='pending' where id=(pg_temp.f('message')->>'id')::uuid;
insert into fixture select 'claim',pg_temp.call('claim');
select is(pg_temp.f('claim')->>'state','prepared','claim prepares a single generation');
select is(pg_temp.call('claim'),pg_temp.f('claim'),'concurrent-style retries recover the active lease');
select is(pg_temp.f('claim')->'dispatch','false'::jsonb,'claim itself never authorizes an external creation');
select throws_ok($$select pg_temp.call('start',jsonb_build_object('leaseToken',gen_random_uuid()))$$,'P0001','LEASE_LOST','foreign lease cannot start creation');
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','successor'))$$,'P0001','FORBIDDEN','prepared identity cannot bind before dispatch fence');
update fmat.conversation_successors set lease_until=clock_timestamp()-interval '1 second' where conversation_id=pg_temp.scope();
select throws_ok($$select pg_temp.call('start',jsonb_build_object('leaseToken',pg_temp.f('claim')->>'leaseToken'))$$,'P0001','LEASE_LOST','expired pre-creation lease denied');
insert into fixture select 'renewed',pg_temp.call('claim');
select isnt(pg_temp.f('renewed')->>'leaseToken',pg_temp.f('claim')->>'leaseToken','unstarted expired lease can be renewed');
select is(pg_temp.f('renewed')->>'creationKey',pg_temp.f('claim')->>'creationKey','renewal retains original creation identity');
select throws_ok($$select pg_temp.call('start',jsonb_build_object('leaseToken',pg_temp.f('claim')->>'leaseToken'))$$,'P0001','LEASE_LOST','old lease remains fenced after renewal');
insert into fixture select 'started',pg_temp.call('start',jsonb_build_object('leaseToken',pg_temp.f('renewed')->>'leaseToken'));
select is(pg_temp.f('started')->>'state','creating','start persists uncertainty before external I/O');
select is(pg_temp.f('started')->'dispatch','true'::jsonb,'exactly one start obtains creation permission');
select is(pg_temp.call('start',jsonb_build_object('leaseToken',pg_temp.f('renewed')->>'leaseToken'))->'dispatch','false'::jsonb,'lost start acknowledgement never authorizes a repeat creation');
update fmat.conversation_successors set lease_until=clock_timestamp()-interval '1 second' where conversation_id=pg_temp.scope();
select is(pg_temp.call('claim')->>'state','creating','expired started lease remains uncertain');
select is(pg_temp.call('claim')->>'leaseToken',pg_temp.f('renewed')->>'leaseToken','uncertain creation never rotates its permit');
select is(pg_temp.call('start',jsonb_build_object('leaseToken',pg_temp.f('renewed')->>'leaseToken'))->'dispatch','false'::jsonb,'expiry does not reset creation permission');
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',gen_random_uuid(),'sessionId','successor'))$$,'P0001','FORBIDDEN','foreign creation identity denied');
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','wrun_successor_old'))$$,'P0001','FORBIDDEN','retired runtime cannot become successor');
create function pg_temp.fail_audit() returns trigger language plpgsql as $$begin if new.operation='conversation_successor_bound' then raise exception 'TEST_AUDIT_FAILURE';end if;return new;end$$;
create trigger test_successor_audit before insert on fmat.audit_events for each row execute function pg_temp.fail_audit();
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','wrun_successor_new'))$$,'P0001','TEST_AUDIT_FAILURE','late failure rolls back all binding writes');
select ok((select runtime_session_id is null from fmat.conversation_scopes where id=pg_temp.scope()),'failed bind retains null canonical pointer');
select ok((select runtime_session_id is null from fmat.conversation_generations where conversation_id=pg_temp.scope() and generation=1),'failed bind retains null ledger pointer');
select ok((select bound_at is null from fmat.conversation_successors where conversation_id=pg_temp.scope()),'failed bind retains uncertainty');
drop trigger test_successor_audit on fmat.audit_events;
insert into fixture select 'bound',pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','wrun_successor_new'));
select is(pg_temp.f('bound')->>'state','bound','late original delivery can bind after dispatch lease expiry');
select is(pg_temp.f('bound')->>'sessionId','wrun_successor_new','exact runtime identity is retained');
select is(pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','wrun_successor_new')),pg_temp.f('bound'),'lost binding response reuses committed identity');
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','wrun_other'))$$,'P0001','FORBIDDEN','second candidate cannot steal canonical binding');
select is((select count(*) from fmat.audit_events where operation='conversation_successor_bound' and subject_id=pg_temp.scope()::text),1::bigint,'exactly one binding audit');
select ok(not exists(select 1 from fmat.audit_events where operation='conversation_successor_bound' and subject_id=pg_temp.scope()::text and metadata ?| array['creationKey','leaseToken','sessionId','text']),'audit excludes private permit/runtime/text');
select is(jsonb_build_object('message',(select to_jsonb(m) from fmat.runtime_messages m where id=(pg_temp.f('message')->>'id')::uuid),'grant',(select to_jsonb(g) from fmat.conversation_grants g where id=pg_temp.grant_id())),pg_temp.f('before'),'creation and binding preserve exact original inbox and grant');
select is((select attempts from fmat.model_work_attempts where name='conversation:'||(pg_temp.f('message')->>'id')),3,'original failed attempt charges remain');
select lives_ok($$select public.fmat_runtime_message('deliver',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('messageId',pg_temp.f('message')->>'id','sessionId','wrun_successor_new'))$$,'bound successor can deliver original input');
select throws_ok($$select public.fmat_runtime_message('deliver',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('messageId',pg_temp.f('message')->>'id','sessionId','wrun_successor_old'))$$,'P0001','FORBIDDEN','old runtime remains fenced');
update fmat.conversation_grants set revoked_at=clock_timestamp() where id=pg_temp.grant_id();
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','wrun_successor_new'))$$,'P0001','UNAUTHORIZED','binding replay cannot renew revoked original authority');
select throws_ok($$select pg_temp.call('claim')$$,'P0001','UNAUTHORIZED','revoked original input cannot resume');
update fmat.conversation_grants set revoked_at=null where id=pg_temp.grant_id();
select fmat.conversation_recovery_begin(pg_temp.grant_id(),pg_temp.scope(),'{"expectedGeneration":1,"idempotencyKey":"96000000-0000-4000-8000-000000000007","evidence":{"generation":1,"sessionId":"wrun_successor_new","eventId":"terminal-second","tailIndex":5,"usage":{"inputTokens":100,"outputTokens":10,"cacheReadTokens":0,"cacheWriteTokens":0}}}');
select throws_ok($$select pg_temp.call('bind',jsonb_build_object('creationKey',pg_temp.f('claim')->>'creationKey','sessionId','wrun_successor_new'))$$,'P0001','STALE_REVISION','retired binding cannot reclaim the conversation');
select throws_ok($$select pg_temp.call('start',jsonb_build_object('leaseToken',pg_temp.f('renewed')->>'leaseToken'))$$,'P0001','STALE_REVISION','retired creation permit cannot start new work');
select throws_ok($$select pg_temp.call('claim')$$,'P0001','STALE_REVISION','retired lease cannot be renewed');
select ok((select bound_at is not null from fmat.conversation_successors where conversation_id=pg_temp.scope() and generation=1),'historical creation receipt is retained');
-- Revocation during pre-creation preparation must not strand a new authorized
-- input. No external creation permission has been issued for this generation.
insert into fixture select 'second_prepared',pg_temp.call('claim','{"generation":2}');
update fmat.runtime_messages set next_dispatch_at=clock_timestamp()-interval '1 second',dispatch_until=null where id=(pg_temp.f('message')->>'id')::uuid;
insert into fixture select 'dispatch',r from jsonb_array_elements(public.fmat_runtime_dispatch('claim','{}')) r where r->>'messageId'=pg_temp.f('message')->>'id';
update fmat.conversation_grants set revoked_at=clock_timestamp() where id=pg_temp.grant_id();
select public.fmat_runtime_dispatch('finish',jsonb_build_object('messageId',pg_temp.f('message')->>'id','leaseToken',pg_temp.f('dispatch')->>'leaseToken','outcome','revoked'));
insert into auth.sessions(id,user_id) values('96000000-0000-4000-8000-000000000008','96000000-0000-4000-8000-000000000001');
insert into fixture select 'new_grant',public.fmat_conversation_access('authorize',jsonb_build_object('kind','host','subject','96000000-0000-4000-8000-000000000001','sessionId','96000000-0000-4000-8000-000000000008','expiresAt',now()+interval '1 hour'),jsonb_build_object('conversationId',pg_temp.scope()));
insert into fixture select 'new_message',public.fmat_runtime_message('accept',(pg_temp.f('new_grant')->>'grantId')::uuid,pg_temp.scope(),'{"clientId":"96000000-0000-4000-8000-000000000009","text":"Separately authorized new input"}');
create function pg_temp.new_claim() returns jsonb language sql as $$select public.fmat_runtime_successor('claim',(pg_temp.f('new_grant')->>'grantId')::uuid,pg_temp.scope(),jsonb_build_object('generation',2,'messageId',pg_temp.f('new_message')->>'id'))$$;
insert into fixture select 'reassigned',pg_temp.new_claim();
select is(pg_temp.f('reassigned')->>'state','prepared','new authorized input may replace abandoned preparation only');
select isnt(pg_temp.f('reassigned')->>'creationKey',pg_temp.f('second_prepared')->>'creationKey','old unstarted creation key is invalidated');
select isnt(pg_temp.f('reassigned')->>'leaseToken',pg_temp.f('second_prepared')->>'leaseToken','old preparation lease is invalidated');
select is((select status from fmat.runtime_messages where id=(pg_temp.f('message')->>'id')::uuid),'failed','expired original remains failed and is never replayed');
select ok((select revoked_at is not null from fmat.conversation_grants where id=pg_temp.grant_id()),'reassignment does not restore original authority');
select is((select attempts from fmat.model_work_attempts where name='conversation:'||(pg_temp.f('message')->>'id')),3,'original failed charges survive reassignment');
select is(pg_temp.new_claim(),pg_temp.f('reassigned'),'reassignment retry preserves the replacement preparation');
select is((select count(*) from fmat.audit_events where operation='conversation_successor_preparation_reassigned' and subject_id=pg_temp.scope()::text),1::bigint,'one redacted reassignment audit');
select public.fmat_runtime_successor('start',(pg_temp.f('new_grant')->>'grantId')::uuid,pg_temp.scope(),jsonb_build_object('generation',2,'messageId',pg_temp.f('new_message')->>'id','leaseToken',pg_temp.f('reassigned')->>'leaseToken'));
update fmat.runtime_messages set status='failed' where id=(pg_temp.f('new_message')->>'id')::uuid;
insert into fixture select 'third_message',public.fmat_runtime_message('accept',(pg_temp.f('new_grant')->>'grantId')::uuid,pg_temp.scope(),'{"clientId":"96000000-0000-4000-8000-000000000010","text":"Wait for uncertain creation"}');
select throws_ok($$select public.fmat_runtime_successor('claim',(pg_temp.f('new_grant')->>'grantId')::uuid,pg_temp.scope(),jsonb_build_object('generation',2,'messageId',pg_temp.f('third_message')->>'id'))$$,'P0001','RECONCILIATION_PENDING','started uncertainty cannot be reassigned or mislabeled as revoked authority');
select is((select creation_key::text from fmat.conversation_successors where conversation_id=pg_temp.scope() and generation=2),pg_temp.f('reassigned')->>'creationKey','uncertain creation identity remains frozen');
select is((select status from fmat.runtime_messages where id=(pg_temp.f('third_message')->>'id')::uuid),'pending','later valid input remains pending during reconciliation');
select * from finish();
rollback;
