begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values('91000000-0000-4000-8000-000000000001','recover@fixture.test',now());
insert into auth.sessions(id,user_id) values('91000000-0000-4000-8000-000000000002','91000000-0000-4000-8000-000000000001');
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('91000000-0000-4000-8000-000000000003','recover@fixture.test',repeat('f',64),now()+interval '1 day','fixture');
insert into fmat.hosts(id,email,invitation_id) values('91000000-0000-4000-8000-000000000001','recover@fixture.test','91000000-0000-4000-8000-000000000003');
create temporary table fixture(name text primary key,value jsonb);
insert into fixture select 'grant',public.fmat_conversation_access('open',jsonb_build_object('kind','host','subject','91000000-0000-4000-8000-000000000001','sessionId','91000000-0000-4000-8000-000000000002','expiresAt',now()+interval '1 hour'),'{"audience":"host_setup"}');
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;
create function pg_temp.scope() returns uuid language sql as $$select (pg_temp.f('grant')->>'conversationId')::uuid$$;
create function pg_temp.grant_id() returns uuid language sql as $$select (pg_temp.f('grant')->>'grantId')::uuid$$;
insert into fixture values('input','{"expectedGeneration":0,"idempotencyKey":"91000000-0000-4000-8000-000000000004","evidence":{"generation":0,"sessionId":"wrun_recovery_fixture","eventId":"event_terminal","tailIndex":24,"usage":{"inputTokens":400,"outputTokens":30,"cacheReadTokens":20,"cacheWriteTokens":10}}}');
create function pg_temp.recover(jsonb default '{}') returns jsonb language sql as $$select fmat.conversation_recovery_begin(pg_temp.grant_id(),pg_temp.scope(),pg_temp.f('input')||$1)$$;

select ok(not has_function_privilege(r,'public.fmat_conversation_recovery(text,uuid,uuid,jsonb)','EXECUTE'),r||' cannot supply recovery evidence') from unnest(array['anon','authenticated']) r;
select ok(has_function_privilege('service_role','public.fmat_conversation_recovery(text,uuid,uuid,jsonb)','EXECUTE'),'server role may use guarded wrapper');
select ok(not has_function_privilege(r,'fmat.conversation_recovery_read(uuid,uuid,jsonb)','EXECUTE'),r||' cannot bypass wrapper') from unnest(array['anon','authenticated','service_role']) r;
create function pg_temp.status(jsonb default '{}') returns jsonb language sql as $$select public.fmat_conversation_recovery('read',pg_temp.grant_id(),pg_temp.scope(),$1)$$;
select is(pg_temp.status()->>'generation','0','initial generation status');
select is(pg_temp.status()->'sessionId','null'::jsonb,'unbound initial status');
select is(pg_temp.status()->'receipt','null'::jsonb,'no invented recovery receipt');
select throws_ok($$select public.fmat_conversation_recovery('force',pg_temp.grant_id(),pg_temp.scope(),'{}')$$,'P0001','NOT_FOUND','unknown operations denied');
select throws_ok($$select public.fmat_conversation_recovery('read',gen_random_uuid(),pg_temp.scope(),'{}')$$,'P0001','UNAUTHORIZED','foreign grant denied');
select throws_ok(format('select pg_temp.status(%L::jsonb)',p),'P0001','INVALID_INPUT','invalid status input '||p::text) from (values
 ('{"sessionId":"foreign"}'::jsonb),('{"expectedGeneration":0}'),('{"expectedGeneration":-1,"idempotencyKey":"91000000-0000-4000-8000-000000000004"}'),('{"expectedGeneration":9007199254740991,"idempotencyKey":"91000000-0000-4000-8000-000000000004"}'),('{"expectedGeneration":0,"idempotencyKey":"bad"}')) x(p);
insert into fixture select 'message',public.fmat_runtime_message('accept',pg_temp.grant_id(),pg_temp.scope(),'{"clientId":"91000000-0000-4000-8000-000000000005","text":"Retained pending text"}');
select lives_ok($$select public.fmat_runtime_message('deliver',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('messageId',pg_temp.f('message')->>'id','sessionId','wrun_recovery_fixture'))$$,'bind exact original runtime');
select is(pg_temp.status()->>'sessionId','wrun_recovery_fixture','server status has exact stored binding');
insert into fixture select 'receipt',public.fmat_conversation_recovery('begin',pg_temp.grant_id(),pg_temp.scope(),pg_temp.f('input'));
select is(pg_temp.status()->>'generation','1','wrapper advances one generation');
select is(pg_temp.status()->>'recoveryId',pg_temp.f('receipt')->>'recoveryId','current recovery is discoverable after reload');
select is(pg_temp.status(pg_temp.f('input')-'evidence')->'receipt',pg_temp.f('receipt'),'lost response reconciles original request without terminal reinspection');
select is(pg_temp.status()->'retiredUsage','{"inputTokens":400,"outputTokens":30}'::jsonb,'retired cumulative allowance is retained');
select is(pg_temp.status()->'liveUsage','{"inputTokens":0,"outputTokens":0}'::jsonb,'new generation has no fabricated usage');
select throws_ok($$select pg_temp.status(jsonb_set(pg_temp.f('input')-'evidence','{expectedGeneration}','1'))$$,'P0001','IDEMPOTENCY_CONFLICT','same retry key cannot change observed generation');
select throws_ok($$select pg_temp.status(jsonb_set(pg_temp.f('input')-'evidence','{idempotencyKey}','"91000000-0000-4000-8000-000000000099"'))$$,'P0001','STALE_REVISION','another retry cannot replace successor');
select is((select count(*) from fmat.conversation_recoveries where conversation_id=pg_temp.scope()),1::bigint,'reads do not create more transitions');
select is((select status from fmat.runtime_messages where id=(pg_temp.f('message')->>'id')::uuid),'pending','status does not replay or settle original input');
update fmat.conversation_grants set revoked_at=clock_timestamp() where id=pg_temp.grant_id();
select throws_ok($$select pg_temp.status()$$,'P0001','UNAUTHORIZED','revoked reader denied');
select throws_ok($$select pg_temp.status(pg_temp.f('input')-'evidence')$$,'P0001','UNAUTHORIZED','revocation denies saved retry receipt');
select * from finish();
rollback;
