begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temporary table invitation_delivery_fixture(name text primary key,value jsonb);
insert into invitation_delivery_fixture values('issue',public.fmat_invitation_operator('issue','delivery-sql','{"project":"abcdefghijklmnopqrst","email":"fixture@example.test","tokenHash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","delivery":"cloudflare","origin":"https://fixture.example","accountId":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","idempotencyKey":"e2000000-0000-4000-8000-000000000001"}'));
create function pg_temp.item(n text) returns jsonb language sql as $$select value from invitation_delivery_fixture where name=n$$;
insert into invitation_delivery_fixture values('lease',public.fmat_invitation_delivery('claim','{"workerId":"delivery-sql"}','{}')->'job');
create function pg_temp.call(op text,input jsonb default '{}') returns jsonb language sql as $$select public.fmat_invitation_delivery(op,pg_temp.item('lease'),input)$$;
select ok(not has_function_privilege('service_role','fmat.require_invitation_delivery_lease(jsonb)','EXECUTE'),'private lease helper is not exposed');
select throws_ok($$select public.fmat_invitation_delivery('claim','{"workerId":"x","extra":true}','{}')$$,'P0001','INVALID_INPUT','claim rejects extra lease fields');
select throws_ok($$select public.fmat_invitation_delivery('load',pg_temp.item('lease')||'{"workerId":"wrong"}','{}')$$,'P0001','LEASE_LOST','wrong worker cannot read code derivation context');
select throws_ok($$select pg_temp.call('dispatch')$$,'P0001','INVALID_INPUT','unprepared dispatch denied');
select throws_ok($$update fmat.invitation_deliveries set prepared_basis=repeat('a',64) where invitation_id=(pg_temp.item('issue')->>'invitationId')::uuid$$,'23514',null,'basis without fingerprint rejected');
select throws_ok($$update fmat.invitation_deliveries set prepared_fingerprint=repeat('a',64) where invitation_id=(pg_temp.item('issue')->>'invitationId')::uuid$$,'23514',null,'fingerprint without basis rejected');
insert into invitation_delivery_fixture values('loaded',pg_temp.call('load'));
select throws_ok($$select pg_temp.call('prepare',jsonb_build_object('basis',pg_temp.item('loaded')->>'basis','tokenHash',repeat('b',64),'fingerprint',repeat('c',64)))$$,'P0001','INVALID_INPUT','mismatched derived token hash denied');
insert into invitation_delivery_fixture values('prepared',pg_temp.call('prepare',jsonb_build_object('basis',pg_temp.item('loaded')->>'basis','tokenHash',repeat('a',64),'fingerprint',repeat('c',64))));
select is(pg_temp.item('prepared')->>'phase','prepared','preparation persists before dispatch');
select throws_ok($$select pg_temp.call('prepare',jsonb_build_object('basis',pg_temp.item('loaded')->>'basis','tokenHash',repeat('a',64),'fingerprint',repeat('d',64)))$$,'P0001','IDEMPOTENCY_CONFLICT','changed message fingerprint denied');
select throws_ok($$update fmat.invitation_deliveries set prepared_fingerprint=repeat('d',64) where invitation_id=(pg_temp.item('issue')->>'invitationId')::uuid$$,'P0001','IMMUTABLE_DELIVERY','prepared content cannot change');
select is(pg_temp.call('dispatch')->>'phase','dispatch','first dispatch grants one send');
select is(pg_temp.call('dispatch')->>'phase','dispatched','repeated dispatch does not grant another send');
select throws_ok($$select pg_temp.call('retry')$$,'P0001','DELIVERY_RECONCILIATION_REQUIRED','dispatched message cannot return to retry');
select throws_ok($$update fmat.invitation_deliveries set dispatch_lease_token=gen_random_uuid() where invitation_id=(pg_temp.item('issue')->>'invitationId')::uuid$$,'P0001','IMMUTABLE_DELIVERY','dispatch fence cannot change');
select throws_ok($$select pg_temp.call('record','{"outcome":"sent"}')$$,'P0001','INVALID_PROVIDER_EVIDENCE','sent requires provider evidence');
select throws_ok($$select pg_temp.call('record','{"outcome":"uncertain","reason":"arbitrary"}')$$,'P0001','INVALID_PROVIDER_EVIDENCE','uncertainty reason is bounded');
select is(pg_temp.call('record','{"outcome":"sent","providerReference":"synthetic-id"}')->>'recorded','true','valid provider outcome recorded');
select is((select phase from fmat.invitation_deliveries where invitation_id=(pg_temp.item('issue')->>'invitationId')::uuid),'sent','delivery retains accepted outcome');
select is((select status from fmat.jobs where id=(pg_temp.item('lease')->>'jobId')::uuid),'complete','outcome completes job atomically');
select throws_ok($$select pg_temp.call('load')$$,'P0001','LEASE_LOST','completed lease cannot resume');
select * from finish();rollback;
