begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temporary table invitation_fixture(name text primary key,value jsonb);
create function pg_temp.issue(p_patch jsonb default '{}') returns jsonb language sql as $$
 select public.fmat_invitation_operator('issue','operator-test','{"project":"local","email":"invitation@example.test","tokenHash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","delivery":"manual","origin":"http://localhost:3000","idempotencyKey":"e1000000-0000-4000-8000-000000000001"}'::jsonb||p_patch)
$$;
create function pg_temp.item(n text) returns jsonb language sql as $$select value from invitation_fixture where name=n$$;
select ok(not has_table_privilege('anon','fmat.invitation_deliveries','SELECT'),'no public invitation delivery reads');
select ok(not has_table_privilege('service_role','fmat.invitation_deliveries','UPDATE'),'service key must use RPC');
select ok(not has_function_privilege('anon','public.fmat_invitation_operator(text,text,jsonb)','EXECUTE'),'anon cannot act as operator');
select ok(not has_function_privilege('authenticated','public.fmat_invitation_operator(text,text,jsonb)','EXECUTE'),'host sessions cannot act as operator');
select ok(has_function_privilege('service_role','public.fmat_invitation_operator(text,text,jsonb)','EXECUTE'),'service authority owns operator RPC');
select ok(not has_function_privilege('service_role','fmat.invitation_status(uuid)','EXECUTE'),'private status helper not exposed');
select ok((select relrowsecurity from pg_class where oid='fmat.invitation_deliveries'::regclass),'delivery RLS enabled');
select throws_ok($$select public.fmat_invitation_operator('issue','', '{}')$$,'P0001','FORBIDDEN','empty audit identity rejected');
select throws_ok($$select public.fmat_invitation_operator('approve','op', '{}')$$,'P0001','INVALID_INPUT','arbitrary operations rejected');
select throws_ok($$select pg_temp.issue('{"expiresAt":"2099-01-01"}')$$,'P0001','INVALID_INPUT','caller cannot choose expiry');
select throws_ok($$select pg_temp.issue('{"code":"AAAAAAAAAAAAAAAA"}')$$,'P0001','INVALID_INPUT','plaintext code rejected');
select throws_ok($$select pg_temp.issue('{"delivery":"cloudflare"}')$$,'P0001','INVALID_INPUT','local issuance cannot send mail');
select throws_ok($$select pg_temp.issue('{"project":"mriseqztcwmezvtawnbo","delivery":"cloudflare","origin":"https://release.findmeatime.com"}')$$,'P0001','INVALID_INPUT','remote email needs account configuration');
select throws_ok($$select pg_temp.issue('{"origin":"https://attacker.test/?token=code"}')$$,'P0001','INVALID_INPUT','origin cannot carry code or query');
select throws_ok($$select pg_temp.issue('{"email":"UPPER@example.test"}')$$,'P0001','INVALID_INPUT','recipient must be normalized');
insert into invitation_fixture values('manual',pg_temp.issue());
select is(pg_temp.item('manual')->>'status','active','issued invitation active');
insert into invitation_fixture values('recovered',public.fmat_invitation_operator('recover','second-operator',jsonb_build_object('project','local','invitationId',pg_temp.item('manual')->>'invitationId')));
select is(pg_temp.item('recovered')->>'operator','operator-test','recovery retains original derivation operator');
select is(pg_temp.item('recovered')->>'idempotencyKey','e1000000-0000-4000-8000-000000000001','recovery retains original retry identity');
select is(pg_temp.item('recovered')->>'tokenHash',repeat('a',64),'private recovery returns hash for in-memory derivation verification');
select ok(not(pg_temp.item('recovered') ? 'code'),'database never returns a readable code');
select throws_ok($$select public.fmat_invitation_operator('recover','op',jsonb_build_object('project','mriseqztcwmezvtawnbo','invitationId',pg_temp.item('manual')->>'invitationId'))$$,'P0001','NOT_FOUND','cross-project recovery denied');
select throws_ok($$select public.fmat_invitation_operator('recover','op',jsonb_build_object('project','local','invitationId',pg_temp.item('manual')->>'invitationId','idempotencyKey','e1000000-0000-4000-8000-000000000009'))$$,'P0001','INVALID_INPUT','recovery cannot replace issue identity');

select is(pg_temp.item('manual')->>'deliveryStatus','manual','manual issuance has no provider status');
select is((select expires_at-created_at from fmat.invitations where id=(pg_temp.item('manual')->>'invitationId')::uuid),interval '7 days','expiry exactly seven days from database issuance');
select is(pg_temp.issue(),pg_temp.item('manual'),'retry preserves original invitation and expiry');
select is((select count(*)::int from fmat.invitation_deliveries where operator_id='operator-test'),1,'one durable invitation intent');
select is((select count(*)::int from fmat.jobs where payload->>'invitationId'=pg_temp.item('manual')->>'invitationId'),0,'manual issue creates no email job');
select ok(not(pg_temp.item('manual') ?| array['tokenHash','code','issueKey','providerReference']),'status excludes private material');
select throws_ok($$select pg_temp.issue('{"email":"changed@example.test"}')$$,'P0001','IDEMPOTENCY_CONFLICT','changed recipient conflicts');
select throws_ok($$select pg_temp.issue('{"tokenHash":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}')$$,'P0001','IDEMPOTENCY_CONFLICT','changed key material cannot replace code');
select throws_ok($$select public.fmat_invitation_operator('status','op',jsonb_build_object('project','mriseqztcwmezvtawnbo','invitationId',pg_temp.item('manual')->>'invitationId'))$$,'P0001','NOT_FOUND','cross-project status denied');
select throws_ok($$select public.fmat_command('invite_issue','{"kind":"operator","id":"op"}','{"idempotencyKey":"legacy"}')$$,'P0001','FORBIDDEN','legacy issue cannot bypass dedicated boundary');
select throws_ok($$select public.fmat_command('invitation_create','{"kind":"operator","id":"op"}','{"idempotencyKey":"legacy"}')$$,'P0001','FORBIDDEN','legacy alias denied');
select throws_ok($$select public.fmat_command('invite_revoke','{"kind":"operator","id":"op"}','{"idempotencyKey":"legacy"}')$$,'P0001','FORBIDDEN','legacy revocation denied');
insert into invitation_fixture values('email',pg_temp.issue(jsonb_build_object('project','mriseqztcwmezvtawnbo','origin','https://release.findmeatime.com','delivery','cloudflare','accountId',repeat('1',32),'tokenHash',repeat('b',64),'idempotencyKey','e1000000-0000-4000-8000-000000000002')));
select is(pg_temp.item('email')->>'deliveryStatus','pending','remote invitation queues delivery');
select is((select count(*)::int from fmat.jobs where kind='invitation_delivery' and payload->>'invitationId'=pg_temp.item('email')->>'invitationId'),1,'one durable email job');
select throws_ok($$update fmat.invitation_deliveries set origin='https://changed.test' where invitation_id=(pg_temp.item('email')->>'invitationId')::uuid$$,'P0001','IMMUTABLE_DELIVERY','frozen origin cannot change');
insert into invitation_fixture values('revoked',public.fmat_invitation_operator('revoke','operator-test',jsonb_build_object('project','mriseqztcwmezvtawnbo','invitationId',pg_temp.item('email')->>'invitationId','idempotencyKey','e1000000-0000-4000-8000-000000000003')));
select is(pg_temp.item('revoked')->>'status','revoked','revocation blocks redemption');
select throws_ok($$select public.fmat_invitation_operator('recover','op',jsonb_build_object('project','mriseqztcwmezvtawnbo','invitationId',pg_temp.item('email')->>'invitationId'))$$,'P0001','INVITATION_INVALID','revoked invitation cannot recover');
select is(pg_temp.item('revoked')->>'deliveryStatus','suppressed','revocation suppresses undispatched delivery');
select is(public.fmat_invitation_operator('revoke','operator-test',jsonb_build_object('project','mriseqztcwmezvtawnbo','invitationId',pg_temp.item('email')->>'invitationId','idempotencyKey','e1000000-0000-4000-8000-000000000003')),pg_temp.item('revoked'),'revocation retry is stable');
update fmat.invitations set expires_at=clock_timestamp()-interval '1 second' where id=(pg_temp.item('manual')->>'invitationId')::uuid;
select is(pg_temp.issue()->>'status','expired','issuance retry reads current expiry without reissuing');
select throws_ok($$select public.fmat_invitation_operator('recover','op',jsonb_build_object('project','local','invitationId',pg_temp.item('manual')->>'invitationId'))$$,'P0001','INVITATION_INVALID','expired invitation cannot recover');
select is((select count(*)::int from fmat.audit_events where operation='invitation_issue' and actor->>'id'='operator-test'),2,'retries do not repeat issue audit effects');
select * from finish();rollback;
