begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) select ('b0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'link'||n||'@example.test',now() from generate_series(1,8)n;
insert into auth.sessions(id,user_id) select ('b1000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,('b0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid from generate_series(1,8)n;
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) select ('b2000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'link'||n||'@example.test',md5(n::text)||md5(n::text),now()+interval '1 day','fixture' from generate_series(1,7)n;
insert into fmat.hosts(id,email,invitation_id) select ('b0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'link'||n||'@example.test',('b2000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid from generate_series(1,7)n;
insert into fmat.photon_receivers values('b3000000-0000-4000-8000-000000000001','b4000000-0000-4000-8000-000000000001',true,now());
create function pg_temp.credential(n integer) returns jsonb language sql as $$select jsonb_build_object('kind','host','subject','b0000000-0000-4000-8000-'||lpad(n::text,12,'0'),'sessionId','b1000000-0000-4000-8000-'||lpad(n::text,12,'0'),'expiresAt',now()+interval '1 hour')$$;
create function pg_temp.input(n integer) returns jsonb language sql as $$select jsonb_build_object('phone','+1555010000'||n,'spaceId','any;-;+1555010000'||n,'line','shared','browserHash',repeat('b',64),'codeHash',repeat('c',64),'encryptedCode',repeat('e',40),'challengeId','b5000000-0000-4000-8000-'||lpad(n::text,12,'0'),'idempotencyKey','b6000000-0000-4000-8000-'||lpad(n::text,12,'0'))$$;
create function pg_temp.link(op text,n integer,input jsonb default '{}') returns jsonb language sql as $$select public.fmat_photon_link(op,pg_temp.credential(n),'b3000000-0000-4000-8000-000000000001',input)$$;
create function pg_temp.delivery(op text,input jsonb default '{}') returns jsonb language sql as $$select public.fmat_photon_link_delivery(op,'b3000000-0000-4000-8000-000000000001',input)$$;
create temporary table fixture(name text primary key,value jsonb);
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;

create function pg_temp.receive(n integer,key text,overrides jsonb default '{}') returns jsonb language sql as $$
 select public.fmat_photon_ingress('b3000000-0000-4000-8000-000000000001','b4000000-0000-4000-8000-000000000001',
 jsonb_build_object('messageId',key,'senderId','+1555010000'||n,'line','shared','spaceId','any;-;+1555010000'||n,'text','Synthetic private preference',
 'occurredAt',coalesce((select occurred_at from fmat.photon_inbox where message_id=key),clock_timestamp()))||overrides)
$$;
create function pg_temp.dispatch() returns text language sql as $$select public.fmat_photon_dispatch('b3000000-0000-4000-8000-000000000001')->>'outcome'$$;
create function pg_temp.check_input(key text) returns jsonb language sql as $$select public.fmat_conversation_check(r.grant_id,r.conversation_id) from fmat.photon_inbox i join fmat.runtime_messages r on r.id=i.runtime_message_id where i.message_id=key$$;
create function pg_temp.tool(key text,op text,input jsonb default '{}') returns jsonb language sql as $$select public.fmat_conversation_tool(r.grant_id,r.conversation_id,op,input) from fmat.photon_inbox i join fmat.runtime_messages r on r.id=i.runtime_message_id where i.message_id=key$$;
create function pg_temp.settle(key text) returns void language sql as $$update fmat.runtime_messages set status='completed',settled_at=clock_timestamp() where id=(select runtime_message_id from fmat.photon_inbox where message_id=key)$$;
select ok(not has_function_privilege('anon','public.fmat_photon_dispatch(uuid)','execute'),'anonymous cannot dispatch');
select ok(not has_function_privilege('authenticated','public.fmat_photon_dispatch(uuid)','execute'),'browser cannot dispatch');
select ok(has_function_privilege('service_role','public.fmat_photon_dispatch(uuid)','execute'),'internal dispatch is callable');
select ok(not has_function_privilege('service_role','fmat.photon_execution_actor(jsonb)','execute'),'private authority helper cannot be invoked by service role');
select pg_temp.receive(1,'before-link');
select pg_temp.link('start',1,pg_temp.input(1));
select pg_temp.link('start',2,pg_temp.input(2));
select pg_temp.delivery('claim');
select pg_temp.link('verify',1,pg_temp.input(1));
select pg_temp.link('verify',2,pg_temp.input(2));
select is(pg_temp.dispatch(),'idle','unlinked receipt does not gain later authority');
select pg_temp.receive(1,'before-link');
select is((select link_id from fmat.photon_inbox where message_id='before-link'),null,'retry cannot rebind old input');
select pg_temp.receive(1,'wrong-line','{"line":"+15550109999"}');
select pg_temp.receive(1,'wrong-space','{"spaceId":"any;-;+15550100002"}');
select pg_temp.receive(3,'wrong-sender');
select pg_temp.receive(1,'old-provider-time',jsonb_build_object('occurredAt',clock_timestamp()-interval '1 day'));
select pg_temp.receive(1,'future-provider-time',jsonb_build_object('occurredAt',clock_timestamp()+interval '1 day'));
select is((select count(*)::integer from fmat.photon_inbox where link_id is not null),0,'only exact post-link routes can bind');
insert into fixture values('web',public.fmat_conversation_access('open',pg_temp.credential(1),'{"audience":"host_setup"}'));
select pg_temp.receive(1,'first');select pg_temp.receive(1,'second');
select is(pg_temp.dispatch(),'accepted','linked receipt accepted');
select is(pg_temp.check_input('first')->>'conversationId',pg_temp.f('web')->>'conversationId','phone uses canonical web conversation');
select is(pg_temp.check_input('first')#>>'{actor,channel}','imessage','actor carries verified channel attribution');
select is(pg_temp.dispatch(),'idle','pending first runtime turn holds second input');
select pg_temp.receive(2,'other-host');
select is(pg_temp.dispatch(),'accepted','busy host does not starve another host');
select isnt(pg_temp.check_input('other-host')->>'conversationId',pg_temp.f('web')->>'conversationId','hosts have separate runtime scopes');
select throws_ok($$select public.fmat_conversation_check((pg_temp.check_input('first')->>'grantId')::uuid,(pg_temp.check_input('other-host')->>'conversationId')::uuid)$$,'P0001','UNAUTHORIZED','cross-host grant denied');
select throws_ok($$select public.fmat_conversation_access('open',(select credential from fmat.conversation_grants where id=(pg_temp.check_input('first')->>'grantId')::uuid),'{"audience":"host_setup"}')$$,'P0001','UNAUTHORIZED','browser credential path never accepts private link credential');
select lives_ok($$select pg_temp.tool('first','setup_read')$$,'phone can read its setup');
select lives_ok($$select pg_temp.tool('first','setup_draft',jsonb_build_object('expectedRevision',0,'patch','{"displayName":"Fixture host"}'::jsonb,'unresolved','[]'::jsonb,'idempotencyKey','phone-fixture'))$$,'authorized model can draft');
select lives_ok($$select pg_temp.tool('first','setup_draft',jsonb_build_object('expectedRevision',0,'patch','{"displayName":"Fixture host"}'::jsonb,'unresolved','[]'::jsonb,'idempotencyKey','phone-fixture'))$$,'tool retry retains one effect');
select is((select count(*)::integer from fmat.setup_turns),1,'one setup turn after replay');
select is((select channel from fmat.setup_turns limit 1),'imessage','setup history records actual channel');
select is((select display_name from fmat.hosts where id=(pg_temp.credential(1)->>'subject')::uuid),null,'model draft cannot confirm settings');
select throws_ok($$select pg_temp.tool('first','setup_confirm')$$,'P0001','FORBIDDEN','model cannot confirm');
select throws_ok($$select pg_temp.tool('first','proposal_approve')$$,'P0001','FORBIDDEN','setup cannot approve booking');
select pg_temp.receive(1,'first');
select is((select count(*)::integer from fmat.runtime_messages),2,'provider replay creates no second input');
select is((select count(*)::integer from fmat.queue_publications p join fmat.jobs j on p.job_id=j.id where j.status='complete' and p.acknowledged_at is null),0,'terminal transport publications acknowledged');
select pg_temp.settle('first');select is(pg_temp.dispatch(),'accepted','next receipt proceeds after settled turn');
select is((select message_id from fmat.photon_inbox where runtime_message_id=(select id from fmat.runtime_messages where conversation_id=(pg_temp.f('web')->>'conversationId')::uuid and status='pending')),'second','receipt FIFO maintained');
-- The phone is an independent linked identity: signing out of the browser
-- cannot silently unlink it, while account and admission revocation still do.
delete from auth.sessions where user_id=(pg_temp.credential(1)->>'subject')::uuid;
select lives_ok($$select pg_temp.check_input('second')$$,'browser logout does not revoke established phone link');
update auth.users set banned_until=clock_timestamp()+interval '1 hour' where id=(pg_temp.credential(1)->>'subject')::uuid;
select throws_ok($$select pg_temp.check_input('second')$$,'P0001','UNAUTHORIZED','account ban revokes execution');
update auth.users set banned_until=null,deleted_at=clock_timestamp() where id=(pg_temp.credential(1)->>'subject')::uuid;
select throws_ok($$select pg_temp.check_input('second')$$,'P0001','UNAUTHORIZED','account deletion revokes execution');
update auth.users set deleted_at=null,email='changed@example.test' where id=(pg_temp.credential(1)->>'subject')::uuid;
select throws_ok($$select pg_temp.check_input('second')$$,'P0001','UNAUTHORIZED','changed admitted email denies stale link');
update auth.users set email='link1@example.test' where id=(pg_temp.credential(1)->>'subject')::uuid;
update fmat.hosts set revoked_at=clock_timestamp() where id=(pg_temp.credential(1)->>'subject')::uuid;
select throws_ok($$select pg_temp.check_input('second')$$,'P0001','UNAUTHORIZED','admission revocation denies execution');
update fmat.hosts set revoked_at=null where id=(pg_temp.credential(1)->>'subject')::uuid;
select pg_temp.receive(1,'queued-unlink');
update fmat.photon_links set revoked_at=clock_timestamp() where host_id=(pg_temp.credential(1)->>'subject')::uuid;
select throws_ok($$select pg_temp.tool('second','setup_read')$$,'P0001','UNAUTHORIZED','unlink revokes already accepted input');
select pg_temp.settle('second');
select is(pg_temp.dispatch(),'revoked','queued unlinked input suppressed');
select is((select runtime_message_id from fmat.photon_inbox where message_id='queued-unlink'),null,'revoked input never reaches runtime');
select pg_temp.settle('other-host');
select pg_temp.receive(2,'old-receiver');
update fmat.photon_receivers set receiver_id='b4000000-0000-4000-8000-000000000002';
select throws_ok($$select pg_temp.check_input('other-host')$$,'P0001','UNAUTHORIZED','receiver rotation revokes prior execution grant');
select is(pg_temp.dispatch(),'revoked','old receiver receipt cannot execute through replacement');
update fmat.photon_receivers set receiver_id='b4000000-0000-4000-8000-000000000001';
select pg_temp.receive(2,'expired');
update fmat.photon_inbox set received_at=clock_timestamp()-interval '2 hours' where message_id='expired';
select is(pg_temp.dispatch(),'revoked','old queued input exceeds one-hour execution lifetime');
select pg_temp.receive(2,'disabled');update fmat.photon_receivers set enabled=false;
select is(pg_temp.dispatch(),'revoked','disabled receiver prevents execution');
update fmat.photon_receivers set enabled=true;
select pg_temp.receive(2,'active-worker');
update fmat.jobs set status='running',lease_token=gen_random_uuid(),lease_until=clock_timestamp()+interval '1 minute',worker_id='fixture' where dedupe_key='photon-ingress:'||(select id::text from fmat.photon_inbox where message_id='active-worker');
select is(pg_temp.dispatch(),'idle','another active job lease is respected');
update fmat.jobs set lease_until=clock_timestamp()-interval '1 second' where worker_id='fixture';
select is(pg_temp.dispatch(),'accepted','expired transport job lease recovers atomically');
select pg_temp.settle('active-worker');
select pg_temp.receive(2,'old-link-queued');
select pg_temp.link('unlink',2,jsonb_build_object('linkId',(select id from fmat.photon_links where host_id=(pg_temp.credential(2)->>'subject')::uuid and revoked_at is null)));
update fmat.photon_link_challenges set created_at=created_at-interval '61 seconds',expires_at=expires_at-interval '61 seconds' where host_id=(pg_temp.credential(2)->>'subject')::uuid;
insert into fixture values('replacement',pg_temp.input(2)||jsonb_build_object('challengeId',gen_random_uuid(),'idempotencyKey',gen_random_uuid()));
select pg_temp.link('start',2,pg_temp.f('replacement'));select pg_temp.delivery('claim');select pg_temp.link('verify',2,pg_temp.f('replacement'));
select is(pg_temp.dispatch(),'revoked','same phone relink cannot authorize an older frozen receipt');
select throws_ok($$select pg_temp.check_input('active-worker')$$,'P0001','UNAUTHORIZED','same phone relink cannot resurrect an old grant');
select pg_temp.receive(2,'new-link');select is(pg_temp.dispatch(),'accepted','new link authorizes only new input');
update fmat.conversation_grants set expires_at=clock_timestamp()-interval '1 second' where id=(select r.grant_id from fmat.runtime_messages r join fmat.photon_inbox i on i.runtime_message_id=r.id where i.message_id='new-link');
select throws_ok($$select pg_temp.check_input('new-link')$$,'P0001','UNAUTHORIZED','grant expiry also checked at tool boundary');
select is((select count(*)::integer from fmat.booking_attempts),0,'all setup execution creates no booking');
select is((select count(*)::integer from fmat.jobs where status='complete' and result->>'outcome'='revoked'),5,'suppression terminal and auditable without private text');
select * from finish();rollback;
