begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.id(prefix text,n integer) returns uuid language sql as $$select (prefix||'-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,email,email_confirmed_at) select pg_temp.id('c8000000',n),'contact'||n||'@example.test',now() from generate_series(1,11)n;
insert into auth.sessions(id,user_id) select pg_temp.id('c8100000',n),pg_temp.id('c8000000',n) from generate_series(1,11)n;
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) select pg_temp.id('c8200000',n),'contact'||n||'@example.test',md5(n::text)||md5(n::text),now()+interval '1 day','fixture' from generate_series(1,10)n;
insert into fmat.hosts(id,email,invitation_id) select pg_temp.id('c8000000',n),'contact'||n||'@example.test',pg_temp.id('c8200000',n) from generate_series(1,10)n;
insert into fmat.photon_receivers values(pg_temp.id('c8300000',1),pg_temp.id('c8400000',1),true,now());
create function pg_temp.credential(n integer) returns jsonb language sql as $$select jsonb_build_object('kind','host','subject',pg_temp.id('c8000000',n),'sessionId',pg_temp.id('c8100000',n),'expiresAt',now()+interval '1 hour')$$;
insert into fmat.photon_link_challenges(id,host_id,project_id,credential,browser_hash,phone,line,space_id,code_hash,request_key,consumed_at,delivery_status)
 select pg_temp.id('c8500000',n),pg_temp.id('c8000000',n),pg_temp.id('c8300000',1),pg_temp.credential(n),repeat('b',64),'+155502000'||lpad(n::text,2,'0'),'shared','any;-;+155502000'||lpad(n::text,2,'0'),repeat('c',64),gen_random_uuid(),now(),'accepted' from generate_series(1,10)n;
insert into fmat.photon_links(id,host_id,project_id,phone,line,space_id,challenge_id)
 select pg_temp.id('c8600000',n),host_id,project_id,phone,line,space_id,id from fmat.photon_link_challenges join generate_series(1,10)n on id=pg_temp.id('c8500000',n);
create function pg_temp.input(n integer) returns jsonb language sql as $$select jsonb_build_object('linkId',pg_temp.id('c8600000',n),'idempotencyKey',pg_temp.id('c8700000',n))$$;
create function pg_temp.request(n integer) returns jsonb language sql as $$select public.fmat_photon_contact('request',pg_temp.credential(n),pg_temp.id('c8300000',1),pg_temp.input(n))$$;
create function pg_temp.state(n integer) returns jsonb language sql as $$select public.fmat_photon_contact('read',pg_temp.credential(n),pg_temp.id('c8300000',1),pg_temp.input(n)-'idempotencyKey')$$;
create function pg_temp.delivery(op text,input jsonb default '{}') returns jsonb language sql as $$select public.fmat_photon_contact_delivery(op,pg_temp.id('c8300000',1),input)$$;
create temporary table fixture(name text primary key,value jsonb);
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;
create function pg_temp.lease(text) returns jsonb language sql as $$select jsonb_build_object('shareId',pg_temp.f($1)->>'shareId','leaseToken',pg_temp.f($1)->>'leaseToken')$$;
select ok(not has_function_privilege('anon','public.fmat_photon_contact(text,jsonb,uuid,jsonb)','execute'),'anonymous request denied');
select ok(not has_function_privilege('authenticated','public.fmat_photon_contact(text,jsonb,uuid,jsonb)','execute'),'authenticated cannot forge server identity');
select ok(not has_function_privilege('authenticated','public.fmat_photon_contact_delivery(text,uuid,jsonb)','execute'),'users cannot claim work');
select ok(has_function_privilege('service_role','public.fmat_photon_contact(text,jsonb,uuid,jsonb)','execute'),'narrow server command granted');
select ok(not has_function_privilege('service_role','fmat.photon_contact_authorized(fmat.photon_contact_shares)','execute'),'internal authority helper private');
select ok(not has_table_privilege('service_role','fmat.photon_contact_shares','select'),'no direct share reads');
select ok(not has_table_privilege('authenticated','fmat.photon_contact_request_keys','insert'),'no direct retry writes');
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('fmat.photon_contact_shares'::regclass,'fmat.photon_contact_request_keys'::regclass)),'both tables RLS enabled');
select ok(not has_function_privilege('service_role','fmat.wake_photon_contacts()','execute'),'application cannot invoke scheduler directly');
select ok(not has_function_privilege('authenticated','public.fmat_photon_contact_snapshot(integer)','execute'),'cross-tenant contact snapshot is service-only');
select ok(has_function_privilege('service_role','public.fmat_photon_contact_snapshot(integer)','execute'),'operator can read bounded contact snapshot');
select is((select count(*)::integer from cron.job where jobname='fmat-photon-contacts' and active and schedule='* * * * *'),1,'one recurring contact recovery schedule');
select is(fmat.wake_photon_contacts(),null::bigint,'idle schedule creates no HTTP wakeup');
select throws_ok($$select public.fmat_photon_contact_snapshot(21)$$,'P0001','INVALID_INPUT','snapshot limit bounded');
select throws_ok($$select public.fmat_photon_contact_snapshot(null)$$,'P0001','INVALID_INPUT','snapshot null limit denied');
select is(pg_temp.state(1),null::jsonb,'linking alone creates no intent');
select throws_ok($$select pg_temp.request(11)$$,'P0001','HOST_NOT_ADMITTED','unadmitted account rejected');
select throws_ok($$select public.fmat_photon_contact('request','{"kind":"guest"}',pg_temp.id('c8300000',1),pg_temp.input(1))$$,'P0001','FORBIDDEN','guest rejected');
select throws_ok($$select public.fmat_photon_contact('request',pg_temp.credential(2),pg_temp.id('c8300000',1),pg_temp.input(1))$$,'P0001','NOT_FOUND','cross-host link denied');
select throws_ok($$select public.fmat_photon_contact('request',pg_temp.credential(1),pg_temp.id('c8300000',1),pg_temp.input(1)||'{"phone":"+15550100001"}')$$,'P0001','INVALID_INPUT','client route rejected');
select throws_ok($$select public.fmat_photon_contact('request',pg_temp.credential(1),pg_temp.id('c8300000',1),pg_temp.input(1)-'idempotencyKey')$$,'P0001','INVALID_INPUT','retry key required');
insert into fixture values('one',pg_temp.request(1));
select is(fmat.wake_photon_contacts(),null::bigint,'pending local work with no Vault target makes no network request');
-- pg_net sends only after commit. This entire test rolls back, so synthetic
-- scheduler configuration can be verified without any external HTTP request.
select vault.create_secret('https://contact-fixture.invalid/api/internal/conversations/dispatch','fmat_runtime_dispatch_url');
select vault.create_secret(repeat('a',64),'fmat_runtime_dispatch_secret');
insert into fixture values('wake',to_jsonb(fmat.wake_photon_contacts()));
select is((select url from net.http_request_queue where id=(pg_temp.f('wake')#>>'{}')::bigint),'https://contact-fixture.invalid/api/internal/photon/contacts','scheduled recovery targets exact protected contact endpoint');
select is((select method from net.http_request_queue where id=(pg_temp.f('wake')#>>'{}')::bigint),'POST','scheduler uses POST');
select is((select headers->>'Authorization' from net.http_request_queue where id=(pg_temp.f('wake')#>>'{}')::bigint),'Bearer '||repeat('a',64),'scheduler authenticates with configured secret');
select vault.update_secret((select id from vault.secrets where name='fmat_runtime_dispatch_url'),'https://wrong-fixture.invalid/unrelated');
select throws_ok($$select fmat.wake_photon_contacts()$$,'P0001','INVALID_DISPATCH_CONFIGURATION','invalid wake target fails closed');
delete from vault.secrets where name in ('fmat_runtime_dispatch_url','fmat_runtime_dispatch_secret');
select is(public.fmat_photon_contact_snapshot(0)->>'scope','photon_contacts','snapshot scope explicit');
select is(public.fmat_photon_contact_snapshot(0)#>>'{coverage,deviceDelivery}','not_observed','no inferred device delivery');
select is(public.fmat_photon_contact_snapshot(0)#>>'{coverage,contactSaving}','not_observed','no inferred contact saving');
select is(pg_temp.request(1),pg_temp.f('one'),'lost response repeats saved result');
select is(public.fmat_photon_contact('request',pg_temp.credential(1),pg_temp.id('c8300000',1),pg_temp.input(1)||jsonb_build_object('idempotencyKey',pg_temp.id('c8700000',20))),pg_temp.f('one'),'different key shares same one intent');
select is((select count(*)::integer from fmat.photon_contact_shares),1,'one durable work item');
select is((select count(*)::integer from fmat.audit_events where operation='photon_contact_requested'),1,'one creation audit');
select is((select count(*)::integer from jsonb_object_keys(pg_temp.state(1))),4,'view only exposes four approved fields');
select ok(pg_temp.state(1)::text not like '%155502%' and pg_temp.state(1)::text not like '%credential%','private route and credential omitted');
insert into fixture values('claim',pg_temp.delivery('claim'));
select is(pg_temp.f('claim')->>'action','send','queued intent can be claimed');
select is(pg_temp.delivery('claim')->>'action','idle','active lease excludes competitor');
select throws_ok($$select pg_temp.delivery('finish',pg_temp.lease('claim')||'{"status":"accepted"}')$$,'P0001','INVALID_INPUT','cannot accept before dispatch');
select is(pg_temp.delivery('dispatch',pg_temp.lease('claim'))->>'authorized','true','current authority marks dispatch');
select is(pg_temp.state(1)->>'status','uncertain','in-flight share never promises acceptance');
select is(public.fmat_photon_contact_snapshot(0)#>>'{signals,2,count}','1','in-flight share visible as uncertain to operators');
select is(public.fmat_photon_contact_snapshot(0)#>'{signals,2,samples}','[]'::jsonb,'aggregate mode omits identifiers');
select throws_ok($$select pg_temp.delivery('dispatch',pg_temp.lease('claim'))$$,'P0001','REVISION_CONFLICT','lost dispatch response cannot authorize another call');
select throws_ok($$select pg_temp.delivery('finish',pg_temp.lease('claim')||'{"status":"retry"}')$$,'P0001','INVALID_INPUT','dispatched share cannot return to queue');
select throws_ok($$select pg_temp.delivery('finish',pg_temp.lease('claim')||'{"status":"failed"}')$$,'P0001','INVALID_INPUT','native failure after dispatch is uncertain');
select lives_ok($$select pg_temp.delivery('finish',pg_temp.lease('claim')||'{"status":"accepted"}')$$,'current worker records acknowledgement');
select is(pg_temp.state(1)->>'status','accepted','accepted is observable');
select is(pg_temp.delivery('claim')->>'action','idle','terminal share never repeats');
select throws_ok($$select pg_temp.delivery('finish',pg_temp.lease('claim')||'{"status":"uncertain"}')$$,'P0001','REVISION_CONFLICT','completed lease fenced');

select pg_temp.request(2);
insert into fixture values('crash',pg_temp.delivery('claim'));
select pg_temp.delivery('dispatch',pg_temp.lease('crash'));
update fmat.photon_contact_shares set lease_until=now()-interval '1 second' where link_id=pg_temp.id('c8600000',2);
select throws_ok($$select pg_temp.delivery('finish',pg_temp.lease('crash')||'{"status":"accepted"}')$$,'P0001','REVISION_CONFLICT','late acknowledgement cannot settle expired lease');
select is(pg_temp.delivery('claim')->>'action','uncertain','crash after dispatch becomes permanent uncertainty');
select is(pg_temp.delivery('claim')->>'action','idle','uncertain native share cannot resend');
select is(pg_temp.state(2)->>'status','uncertain','uncertainty survives status read');

select pg_temp.request(3);
insert into fixture values('preflight',pg_temp.delivery('claim'));
update fmat.photon_contact_shares set lease_until=now()-interval '1 second' where link_id=pg_temp.id('c8600000',3);
insert into fixture values('recovered',pg_temp.delivery('claim'));
select is(pg_temp.f('recovered')->>'action','send','crash before dispatch recoverable');
select isnt(pg_temp.f('preflight')->>'leaseToken',pg_temp.f('recovered')->>'leaseToken','recovery rotates ownership');
select throws_ok($$select pg_temp.delivery('dispatch',pg_temp.lease('preflight'))$$,'P0001','REVISION_CONFLICT','old worker cannot dispatch');
select pg_temp.delivery('finish',pg_temp.lease('recovered')||'{"status":"retry"}');
select is(pg_temp.delivery('claim')->>'action','idle','preflight retry observes cooldown');
update fmat.photon_contact_shares set available_at=now()-interval '1 second' where link_id=pg_temp.id('c8600000',3);
insert into fixture values('last',pg_temp.delivery('claim'));
select pg_temp.delivery('finish',pg_temp.lease('last')||'{"status":"retry"}');
select is(pg_temp.state(3)->>'status','failed','three claims exhaust preflight budget');
select is((select attempts from fmat.photon_contact_shares where link_id=pg_temp.id('c8600000',3)),3,'attempt bound retained');

select pg_temp.request(4);
insert into fixture values('unlink',pg_temp.delivery('claim'));
select public.fmat_photon_link('unlink',pg_temp.credential(4),pg_temp.id('c8300000',1),pg_temp.input(4)-'idempotencyKey');
select is(pg_temp.delivery('dispatch',pg_temp.lease('unlink'))->>'authorized','false','unlink during preflight denies native operation');
select is((select status from fmat.photon_contact_shares where link_id=pg_temp.id('c8600000',4)),'revoked','revocation committed rather than rolled back by an exception');
select throws_ok($$select pg_temp.state(4)$$,'P0001','NOT_FOUND','old link cannot be read after unlink');
select pg_temp.request(5);
delete from auth.sessions where id=pg_temp.id('c8100000',5);
select is(pg_temp.delivery('claim')->>'action','revoked','queued logout fences delivery');
select pg_temp.request(6);
insert into fixture values('route',pg_temp.delivery('claim'));
update fmat.photon_links set line='+15550299999' where id=pg_temp.id('c8600000',6);
select is(pg_temp.delivery('dispatch',pg_temp.lease('route'))->>'authorized','false','changed sender route cannot redirect share');
select pg_temp.request(7);
update fmat.hosts set revoked_at=now() where id=pg_temp.id('c8000000',7);
select is(pg_temp.delivery('claim')->>'action','revoked','admission revocation fences queued work');
select pg_temp.request(8);
insert into fixture values('receiver',pg_temp.delivery('claim'));
update fmat.photon_receivers set enabled=false where project_id=pg_temp.id('c8300000',1);
select is(pg_temp.delivery('dispatch',pg_temp.lease('receiver'))->>'authorized','false','disabled receiver fences before dispatch');
select throws_ok($$select pg_temp.request(9)$$,'P0001','CONFIGURATION_UNAVAILABLE','disabled receiver denies new request');
update fmat.photon_receivers set enabled=true where project_id=pg_temp.id('c8300000',1);
select pg_temp.request(9);
update auth.sessions set not_after=now()-interval '1 second' where id=pg_temp.id('c8100000',9);
select is(pg_temp.delivery('claim')->>'action','revoked','expired session fences queued work');

-- A later link cannot reuse any old browser retry identity, including aliases.
update fmat.photon_links set revoked_at=now() where id=pg_temp.id('c8600000',1);
insert into fmat.photon_link_challenges(id,host_id,project_id,credential,browser_hash,phone,line,space_id,code_hash,request_key,consumed_at,delivery_status)
 select pg_temp.id('c8500000',20),host_id,project_id,credential,browser_hash,phone,line,space_id,code_hash,gen_random_uuid(),now(),'accepted' from fmat.photon_link_challenges where id=pg_temp.id('c8500000',1);
insert into fmat.photon_links(id,host_id,project_id,phone,line,space_id,challenge_id) select pg_temp.id('c8600000',20),host_id,project_id,phone,line,space_id,id from fmat.photon_link_challenges where id=pg_temp.id('c8500000',20);
select throws_ok($$select public.fmat_photon_contact('request',pg_temp.credential(1),pg_temp.id('c8300000',1),pg_temp.input(1)||jsonb_build_object('linkId',pg_temp.id('c8600000',20)))$$,'P0001','IDEMPOTENCY_CONFLICT','original retry key cannot target replacement link');
select throws_ok($$select public.fmat_photon_contact('request',pg_temp.credential(1),pg_temp.id('c8300000',1),pg_temp.input(20))$$,'P0001','IDEMPOTENCY_CONFLICT','duplicate key alias cannot target replacement link');
create function pg_temp.rollback_request() returns void language plpgsql as $$begin perform pg_temp.request(10);raise exception 'ROLLBACK_FIXTURE';end;$$;
select throws_ok($$select pg_temp.rollback_request()$$,'P0001','ROLLBACK_FIXTURE','injected failure rolls back publication and audit');
select is((select count(*)::integer from fmat.photon_contact_shares where host_id=pg_temp.id('c8000000',10)),0,'rolled back request left no work');
select is((select count(*)::integer from fmat.audit_events where actor->>'id'=pg_temp.id('c8000000',10)::text and operation='photon_contact_requested'),0,'rolled back request left no audit');
select pg_temp.request(10);
insert into fixture values('crash-budget',pg_temp.delivery('claim'));
select throws_ok($$select public.fmat_photon_contact_delivery('dispatch',pg_temp.id('c8300000',2),pg_temp.lease('crash-budget'))$$,'P0001','NOT_FOUND','worker project cannot be transferred');
select throws_ok($$select pg_temp.delivery('dispatch',pg_temp.lease('crash-budget')-'leaseToken')$$,'P0001','INVALID_INPUT','missing worker lease rejected');
update fmat.photon_contact_shares set lease_until=now()-interval '1 second' where link_id=pg_temp.id('c8600000',10);
select pg_temp.delivery('claim');
update fmat.photon_contact_shares set lease_until=now()-interval '1 second' where link_id=pg_temp.id('c8600000',10);
select pg_temp.delivery('claim');
update fmat.photon_contact_shares set lease_until=now()-interval '1 second' where link_id=pg_temp.id('c8600000',10);
select is(pg_temp.delivery('claim')->>'action','failed','repeated pre-dispatch process loss exhausts bounded claims');
select is(pg_temp.state(10)->>'status','failed','crash exhaustion remains visible');
select is((select attempts from fmat.photon_contact_shares where link_id=pg_temp.id('c8600000',10)),3,'crash recovery never exceeds three claims');
select is(public.fmat_photon_contact_snapshot(20)#>>'{signals,1,count}','2','failed preflight and crash budgets visible');
select is(public.fmat_photon_contact_snapshot(20)#>>'{signals,2,count}','1','terminal uncertainty visible separately');
select ok(public.fmat_photon_contact_snapshot(20)::text not like '%155502%' and public.fmat_photon_contact_snapshot(20)::text not like '%sessionId%','snapshot omits recipient and credentials');
select is((select count(*)::integer from fmat.audit_events where operation like 'photon_contact_%' and (metadata::text like '%155502%' or metadata::text like '%sessionId%')),0,'audit has no private route or session');
select is((select count(*)::integer from fmat.booking_attempts),0,'contact sharing creates no booking');
select * from finish();
rollback;
