begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) select ('b0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'link'||n||'@example.test',now() from generate_series(1,8)n;
insert into auth.sessions(id,user_id) select ('b1000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,('b0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid from generate_series(1,8)n;
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) select ('b2000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'link'||n||'@example.test',md5(n::text)||md5(n::text),now()+interval '1 day','fixture' from generate_series(1,7)n;
insert into fmat.hosts(id,email,invitation_id) select ('b0000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'link'||n||'@example.test',('b2000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid from generate_series(1,7)n;
insert into fmat.photon_receivers values('b3000000-0000-4000-8000-000000000001','b4000000-0000-4000-8000-000000000001',true,now());
create function pg_temp.credential(n integer) returns jsonb language sql as $$select jsonb_build_object('kind','host','subject','b0000000-0000-4000-8000-'||lpad(n::text,12,'0'),'sessionId','b1000000-0000-4000-8000-'||lpad(n::text,12,'0'),'expiresAt',now()+interval '1 hour')$$;
create function pg_temp.input(n integer) returns jsonb language sql as $$select jsonb_build_object('phone','+1555010000'||n,'spaceId','any;-;+1555010000'||n,'line','shared','browserHash',repeat('b',64),'codeHash',repeat('c',64),'encryptedCode',repeat('e',40),'challengeId','b5000000-0000-4000-8000-'||lpad(n::text,12,'0'),'idempotencyKey','b6000000-0000-4000-8000-'||lpad(n::text,12,'0'))$$;
create function pg_temp.link(op text,n integer,input jsonb default '{}') returns jsonb language sql as $$select public.fmat_photon_link(op,pg_temp.credential(n),'b3000000-0000-4000-8000-000000000001',input)$$;
create function pg_temp.delivery(op text,input jsonb default '{}') returns jsonb language sql as $$select public.fmat_photon_link_delivery(op,'b3000000-0000-4000-8000-000000000001',input)$$;
create temporary table fixture(name text primary key,value jsonb);
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;
select ok(not has_function_privilege('anon','public.fmat_photon_link(text,jsonb,uuid,jsonb)','execute'),'anonymous cannot forge linking authority');
select ok(not has_function_privilege('authenticated','public.fmat_photon_link_delivery(text,uuid,jsonb)','execute'),'user cannot claim delivery');
select ok(has_function_privilege('service_role','public.fmat_photon_link(text,jsonb,uuid,jsonb)','execute'),'service can use narrow linking command');
select ok(not has_table_privilege('service_role','fmat.photon_link_challenges','select'),'no direct challenge table access');
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('fmat.photon_links'::regclass,'fmat.photon_link_challenges'::regclass,'fmat.photon_link_attempts'::regclass,'fmat.photon_link_preferences'::regclass)),'all linking tables use RLS');
select throws_ok($$select pg_temp.link('start',8,pg_temp.input(8))$$,'P0001','HOST_NOT_ADMITTED','unadmitted account denied');
select is(pg_temp.link('start',1,pg_temp.input(1))#>>'{challenge,status}','prepared','commits durable intent before sending');
select is(pg_temp.link('start',1,pg_temp.input(1))#>>'{challenge,id}',pg_temp.input(1)->>'challengeId','start retry reuses intent');
select is((select count(*)::integer from fmat.photon_link_challenges),1,'one challenge despite replay');
select throws_ok($$select pg_temp.link('start',1,pg_temp.input(1)||'{"phone":"+15550100009"}')$$,'P0001','IDEMPOTENCY_CONFLICT','retry cannot change recipient');
select throws_ok($$select pg_temp.link('start',1,pg_temp.input(1)||jsonb_build_object('idempotencyKey',gen_random_uuid(),'challengeId',gen_random_uuid()))$$,'P0001','IMESSAGE_LIMIT','host resend cooldown');
select throws_ok($$select pg_temp.link('verify',1,pg_temp.input(1))$$,'P0001','CHALLENGE_INVALID','unsent code cannot link');
insert into fixture values('claim',pg_temp.delivery('claim')->0);
select is(pg_temp.f('claim')->>'action','send','first claim sends');
select is(jsonb_array_length(pg_temp.delivery('claim')),0,'active lease excludes competing claim');
select is(pg_temp.link('read',1,pg_temp.input(1))#>>'{challenge,status}','uncertain','send outcome uncertain before external action');
select throws_ok($$select pg_temp.delivery('finish',jsonb_build_object('challengeId',pg_temp.input(1)->>'challengeId','status','accepted'))$$,'P0001','REVISION_CONFLICT','missing lease never authorizes finish');
select lives_ok($$select pg_temp.delivery('authorize',pg_temp.f('claim'))$$,'current authority permits dispatch');
insert into auth.sessions(id,user_id) values('b1000000-0000-4000-8000-000000000009',(pg_temp.credential(1)->>'subject')::uuid);
select throws_ok($$select public.fmat_photon_link('verify',pg_temp.credential(1)||'{"sessionId":"b1000000-0000-4000-8000-000000000009"}','b3000000-0000-4000-8000-000000000001',pg_temp.input(1))$$,'P0001','CHALLENGE_INVALID','another login session in the same browser denied');
select throws_ok($$select pg_temp.link('verify',2,pg_temp.input(1))$$,'P0001','CHALLENGE_INVALID','wrong host denied');
select throws_ok($$select pg_temp.link('verify',1,pg_temp.input(1)||jsonb_build_object('browserHash',repeat('a',64)))$$,'P0001','CHALLENGE_INVALID','wrong browser denied');
select throws_ok($$select public.fmat_photon_link('verify',pg_temp.credential(1),'b3000000-0000-4000-8000-000000000002',pg_temp.input(1))$$,'P0001','CONFIGURATION_UNAVAILABLE','project transfer denied');
select is(pg_temp.link('verify',1,pg_temp.input(1)||jsonb_build_object('codeHash',repeat('d',64)))->>'outcome','invalid_code','wrong code recorded');
select is(pg_temp.link('verify',1,pg_temp.input(1)||jsonb_build_object('codeHash',repeat('d',64)))#>>'{challenge,remainingAttempts}','4','retry does not spend another guess');
select throws_ok($$select pg_temp.link('verify',1,pg_temp.input(1))$$,'P0001','IDEMPOTENCY_CONFLICT','same attempt ID cannot try another code');
select lives_ok($$select pg_temp.delivery('finish',pg_temp.f('claim')||'{"status":"accepted","providerReference":"fixture-message"}')$$,'records acceptance');
update fmat.photon_link_challenges set checked_at=now()-interval '1 minute';
insert into fixture values('reconcile',pg_temp.delivery('claim')->0);
select is(pg_temp.f('reconcile')->>'action','reconcile','restart reconciles instead of sending');
select is(pg_temp.f('reconcile')->>'encryptedCode',null,'reconciliation never retrieves code');
select throws_ok($$select pg_temp.delivery('finish',pg_temp.f('claim')||'{"status":"failed"}')$$,'P0001','REVISION_CONFLICT','old worker fenced');
select lives_ok($$select pg_temp.delivery('finish',pg_temp.f('reconcile')||'{"status":"uncertain"}')$$,'uncertain poll recorded');
select is(pg_temp.link('read',1,pg_temp.input(1))#>>'{challenge,status}','accepted','uncertain poll retains prior acceptance');
select is(pg_temp.link('verify',1,pg_temp.input(1)||jsonb_build_object('idempotencyKey','b7000000-0000-4000-8000-000000000001'))->>'outcome','linked','correct code links once');
select is(pg_temp.link('verify',1,pg_temp.input(1)||jsonb_build_object('idempotencyKey','b7000000-0000-4000-8000-000000000001'))->>'outcome','linked','lost verification acknowledgement reuses result');
select is((select count(*)::integer from fmat.photon_links),1,'only one link');
select is((select encrypted_code from fmat.photon_link_challenges limit 1),null,'consumption erases encrypted code');
select ok(pg_temp.link('read',1)::text not like '%15550100001%','browser state masks phone');
select ok(pg_temp.link('read',1)::text not like '%credential%','browser state omits authority');
select throws_ok($$select pg_temp.link('verify',1,pg_temp.input(1)||jsonb_build_object('idempotencyKey',gen_random_uuid()))$$,'P0001','CHALLENGE_INVALID','consumed challenge cannot be reused with fresh key');
insert into fixture values('link',pg_temp.link('read',1)->'link');
select lives_ok($$select pg_temp.link('unlink',1,jsonb_build_object('linkId',pg_temp.f('link')->>'id'))$$,'explicit unlink');
select throws_ok($$select pg_temp.link('verify',1,pg_temp.input(1)||jsonb_build_object('idempotencyKey','b7000000-0000-4000-8000-000000000001'))$$,'P0001','CHALLENGE_INVALID','replay cannot resurrect unlinked identity');
-- Five distinct guesses lock the challenge; no plaintext code is retained.
select lives_ok($$select pg_temp.link('start',2,pg_temp.input(2))$$,'second host start');
select pg_temp.delivery('claim');
select pg_temp.link('verify',2,pg_temp.input(2)||jsonb_build_object('codeHash',repeat('d',64),'idempotencyKey',gen_random_uuid())) from generate_series(1,5);
select is(pg_temp.link('read',2,pg_temp.input(2))#>>'{challenge,status}','locked','fifth guess locks');
select throws_ok($$select pg_temp.link('verify',2,pg_temp.input(2))$$,'P0001','CHALLENGE_INVALID','correct code after limit denied');
select is((select encrypted_code from fmat.photon_link_challenges where host_id=(pg_temp.credential(2)->>'subject')::uuid),null,'locked secret erased');
-- Cancel and explicit skip invalidate outstanding challenges.
select pg_temp.link('start',3,pg_temp.input(3));
select pg_temp.delivery('claim');
select pg_temp.link('cancel',3,pg_temp.input(3));
select throws_ok($$select pg_temp.link('verify',3,pg_temp.input(3))$$,'P0001','CHALLENGE_INVALID','cancelled old number cannot link');
select is(pg_temp.link('skip',3)->>'skipped','true','skip persisted');
-- Expiry and logout are checked again after a claimed intent.
select pg_temp.link('start',4,pg_temp.input(4));
insert into fixture values('expired',pg_temp.delivery('claim')->0);
update fmat.photon_link_challenges set created_at=now()-interval '11 minutes',expires_at=now()-interval '1 minute' where host_id=(pg_temp.credential(4)->>'subject')::uuid;
select throws_ok($$select pg_temp.delivery('authorize',pg_temp.f('expired'))$$,'P0001','FORBIDDEN','expired before dispatch');
select throws_ok($$select pg_temp.link('verify',4,pg_temp.input(4))$$,'P0001','CHALLENGE_INVALID','expired correct code denied');
select pg_temp.link('start',5,pg_temp.input(5));
insert into fixture values('logout',pg_temp.delivery('claim')->0);
delete from auth.sessions where user_id=(pg_temp.credential(5)->>'subject')::uuid;
select throws_ok($$select pg_temp.delivery('authorize',pg_temp.f('logout'))$$,'P0001','UNAUTHORIZED','logout fences pending delivery');
-- Successful provider acceptance does not bypass a known failure.
select pg_temp.link('start',6,pg_temp.input(6));
insert into fixture values('failed',pg_temp.delivery('claim')->0);
select pg_temp.delivery('finish',pg_temp.f('failed')||'{"status":"failed"}');
select throws_ok($$select pg_temp.link('verify',6,pg_temp.input(6))$$,'P0001','CHALLENGE_INVALID','failed send cannot link');
select is((select count(*)::integer from fmat.booking_attempts),0,'linking creates no booking');
select is((select count(*)::integer from fmat.setup_turns),0,'protected inputs never enter transcript');
select is((select count(*)::integer from fmat.audit_events where metadata::text like '%code%' or metadata::text like '%155501%'),0,'audit contains no codes or phone');
-- Hourly caps survive cancellation and changing the phone number.
do $$begin
 for i in 1..5 loop
  perform pg_temp.link('start',7,pg_temp.input(7)||jsonb_build_object('challengeId',gen_random_uuid(),'idempotencyKey',gen_random_uuid()));
  update fmat.photon_link_challenges set created_at=created_at-interval '61 seconds',expires_at=expires_at-interval '61 seconds' where host_id=(pg_temp.credential(7)->>'subject')::uuid;
 end loop;
end$$;
select is((select count(*)::integer from fmat.photon_link_challenges where host_id=(pg_temp.credential(7)->>'subject')::uuid),5,'five distinct durable attempts retained');
select throws_ok($$select pg_temp.link('start',7,pg_temp.input(7)||jsonb_build_object('challengeId',gen_random_uuid(),'idempotencyKey',gen_random_uuid(),'phone','+15550100009','spaceId','any;-;+15550100009'))$$,'P0001','IMESSAGE_LIMIT','hourly host cap cannot be bypassed by number changes');
select is((select count(*)::integer from fmat.photon_link_challenges where host_id=(pg_temp.credential(7)->>'subject')::uuid and revoked_at is not null and encrypted_code is null),4,'replacement erases each prior challenge');
-- Simulate a process dying after claim but before acknowledgement.
insert into fixture select 'crash',value from jsonb_array_elements(pg_temp.delivery('claim')) value where value->>'hostId'=pg_temp.credential(7)->>'subject';
update fmat.photon_link_challenges set lease_until=now()-interval '1 second',checked_at=now()-interval '1 minute' where id=(pg_temp.f('crash')->>'challengeId')::uuid;
insert into fixture select 'recovered',value from jsonb_array_elements(pg_temp.delivery('claim')) value where value->>'hostId'=pg_temp.credential(7)->>'subject';
select is(pg_temp.f('recovered')->>'action','reconcile','expired lease never authorizes blind resend');
select is(pg_temp.f('recovered')->>'encryptedCode',null,'recovery does not disclose code');
select throws_ok($$select pg_temp.delivery('finish',pg_temp.f('crash')||'{"status":"accepted"}')$$,'P0001','REVISION_CONFLICT','dead process lease fenced');
insert into fmat.photon_link_challenges(id,host_id,project_id,credential,browser_hash,phone,line,space_id,code_hash,request_key,created_at,expires_at,revoked_at)
select gen_random_uuid(),(pg_temp.credential(1)->>'subject')::uuid,'b3000000-0000-4000-8000-000000000001',pg_temp.credential(1),repeat('b',64),'+15550199999','shared','any;-;+15550199999',repeat('c',64),gen_random_uuid(),now()-make_interval(mins=>n+1),now()+make_interval(mins=>9-n),now() from generate_series(1,5)n;
select throws_ok($$select pg_temp.link('start',3,pg_temp.input(3)||jsonb_build_object('challengeId',gen_random_uuid(),'idempotencyKey',gen_random_uuid(),'phone','+15550199999','spaceId','any;-;+15550199999'))$$,'P0001','IMESSAGE_LIMIT','recipient hourly cap survives changing the requesting host');
update fmat.photon_receivers set enabled=false;
select throws_ok($$select pg_temp.delivery('authorize',pg_temp.f('recovered'))$$,'P0001','FORBIDDEN','disabled receiver fences delivery');
select is((select count(*)::integer from cron.job where jobname='fmat-photon-links' and active),1,'one recovery schedule installed');
select * from finish();
rollback;
