begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into fmat.photon_receivers(project_id,receiver_id,enabled) values
('a1000000-0000-4000-8000-000000000001','a2000000-0000-4000-8000-000000000001',true),
('a1000000-0000-4000-8000-000000000002','a2000000-0000-4000-8000-000000000002',true);
create function pg_temp.input() returns jsonb language sql as $$ select '{"messageId":"opaque-message:1","senderId":"+15550100001","spaceId":"any;-;+15550100001","line":"shared","text":"Synthetic preference","occurredAt":"2026-10-07T00:00:00Z"}'::jsonb $$;
create function pg_temp.ingest(jsonb default pg_temp.input()) returns jsonb language sql as $$
select public.fmat_photon_ingress('a1000000-0000-4000-8000-000000000001','a2000000-0000-4000-8000-000000000001',$1) $$;
select ok(not has_function_privilege('anon','public.fmat_photon_ingress(uuid,uuid,jsonb)','EXECUTE'),'anonymous cannot forge transport evidence');
select ok(not has_function_privilege('authenticated','public.fmat_photon_ingress(uuid,uuid,jsonb)','EXECUTE'),'signed-in accounts cannot forge transport evidence');
select ok(has_function_privilege('service_role','public.fmat_photon_ingress(uuid,uuid,jsonb)','EXECUTE'),'receiver uses narrow service RPC');
select ok(not has_table_privilege('service_role','fmat.photon_inbox','SELECT'),'transport payload has no direct service table grant');
select ok((select relrowsecurity from pg_class where oid='fmat.photon_inbox'::regclass),'inbox RLS enabled');
select ok((select relrowsecurity from pg_class where oid='fmat.photon_receivers'::regclass),'receiver registry RLS enabled');
select is(pg_temp.ingest()->>'duplicate','false','first receipt committed');
select is(pg_temp.ingest()->>'duplicate','true','duplicate receipt reuses original');
select is((select count(*)::integer from fmat.photon_inbox),1,'one inbox record');
select is((select count(*)::integer from fmat.jobs where kind='photon_ingress'),1,'one durable job');
select is((select count(*)::integer from fmat.queue_publications p join fmat.jobs j on j.id=p.job_id where j.kind='photon_ingress'),1,'one queue wakeup');
select ok((select bool_and(jsonb_object_length=1) from (select count(*) as jsonb_object_length from fmat.jobs j,lateral jsonb_object_keys(j.payload) k where j.kind='photon_ingress' group by j.id) x),'jobs contain only inbox reference');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"text":"changed"}')$$,'P0001','IDEMPOTENCY_CONFLICT','same provider ID cannot change text');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"senderId":"+15550100002"}')$$,'P0001','IDEMPOTENCY_CONFLICT','same provider ID cannot transfer sender');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"spaceId":"another"}')$$,'P0001','IDEMPOTENCY_CONFLICT','same provider ID cannot transfer space');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"line":"another"}')$$,'P0001','IDEMPOTENCY_CONFLICT','same provider ID cannot transfer line');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"occurredAt":"2026-10-07T00:01:00Z"}')$$,'P0001','IDEMPOTENCY_CONFLICT','same provider ID cannot change occurrence');
select lives_ok($$select public.fmat_photon_ingress('a1000000-0000-4000-8000-000000000002','a2000000-0000-4000-8000-000000000002',pg_temp.input())$$,'same opaque ID in another project has separate scope');
select throws_ok($$select public.fmat_photon_ingress('a1000000-0000-4000-8000-000000000001','a2000000-0000-4000-8000-000000000002',pg_temp.input())$$,'P0001','CONFIGURATION_UNAVAILABLE','receiver cannot cross projects');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"hostId":"forged"}')$$,'P0001','INVALID_INPUT','transport cannot assert host authority');
select throws_ok($$select pg_temp.ingest(pg_temp.input()-'senderId')$$,'P0001','INVALID_INPUT','missing sender rejected');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"text":null}')$$,'P0001','INVALID_INPUT','null text rejected');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||jsonb_build_object('text',repeat('x',4001)))$$,'P0001','INVALID_INPUT','oversized text rejected');
select throws_ok($$select pg_temp.ingest(pg_temp.input()||'{"occurredAt":"infinity"}')$$,'P0001','INVALID_INPUT','unbounded occurrence rejected');
select lives_ok($$select pg_temp.ingest(pg_temp.input()||'{"messageId":"opaque-message:2"}')$$,'next receipt');
select ok((select a.received_order<b.received_order from fmat.photon_inbox a join fmat.photon_inbox b using(project_id) where a.project_id='a1000000-0000-4000-8000-000000000001' and a.message_id='opaque-message:1' and b.message_id='opaque-message:2'),'receipt order persisted');
savepoint before_receipt;
select pg_temp.ingest(pg_temp.input()||'{"messageId":"rolled-back"}');
rollback to savepoint before_receipt;
select is((select count(*)::integer from fmat.photon_inbox where message_id='rolled-back'),0,'rollback leaves no receipt');
select is((select count(*)::integer from fmat.jobs where kind='photon_ingress'),3,'rollback leaves no job');
update fmat.photon_receivers set enabled=false where project_id='a1000000-0000-4000-8000-000000000001';
select throws_ok($$select pg_temp.ingest()$$,'P0001','CONFIGURATION_UNAVAILABLE','disabled receiver rejects replay too');
select is((select count(*)::integer from fmat.hosts),0,'transport creates no host');
select is((select count(*)::integer from fmat.setup_channel_links),0,'transport creates no link');
select is((select count(*)::integer from fmat.conversation_grants),0,'transport creates no execution grant');
select is((select count(*)::integer from fmat.booking_attempts),0,'transport creates no booking');
select * from finish();
rollback;
