begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values('d0000000-0000-4000-8000-000000000001','intake@fixture.test',now());
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('d1000000-0000-4000-8000-000000000001','intake@fixture.test',repeat('e',64),now()+interval '1 day','intake-test');
insert into fmat.hosts(id,email,invitation_id,handle,display_name,rules,conflict_calendar_ids,booking_calendar_id) values
('d0000000-0000-4000-8000-000000000001','intake@fixture.test','d1000000-0000-4000-8000-000000000001','intake-fixture','Private Host','{"timezone":"Asia/Seoul","durationMinutes":30,"preferences":"PRIVATE"}',array['private-calendar'],'private-calendar');
insert into fmat.calendar_connections(id,principal_kind,principal_id,provider_subject,scopes,encrypted_credential,generation) values
('d2000000-0000-4000-8000-000000000001','host','d0000000-0000-4000-8000-000000000001','private-subject',array['https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar.events'],'encrypted-private-fixture','d3000000-0000-4000-8000-000000000001');
create temporary table fixture(name text primary key,value jsonb);
insert into fixture values('details','{"requesterName":"요청자","requesterEmail":"requester@fixture.test","purpose":"회의 계획","timezone":"Asia/Seoul","durationMinutes":30,"windows":[]}');
insert into fixture select 'context',public.fmat_public_intake('context',null,'{"handle":"intake-fixture"}');
create function pg_temp.input() returns jsonb language sql as $$select (select value->'grant' from fixture where name='context')||jsonb_build_object('handle','intake-fixture','details',(select value from fixture where name='details'))$$;
select ok(not has_function_privilege('anon','public.fmat_public_intake(text,text,jsonb)','EXECUTE'),'anonymous cannot read provider context or forge readiness');
select ok(not has_function_privilege('authenticated','public.fmat_public_intake(text,text,jsonb)','EXECUTE'),'ordinary Auth cannot forge a public principal');
select ok(has_function_privilege('service_role','public.fmat_public_intake(text,text,jsonb)','EXECUTE'),'only server can adapt intake');
select is((select value->'profile' from fixture where name='context'),'{"handle":"intake-fixture","displayName":"Private Host","timezone":"Asia/Seoul","durationMinutes":30}'::jsonb,'public profile excludes all private policy/calendar identity');
select is(public.fmat_public_intake('resume',repeat('a',64),'{"handle":"intake-fixture"}'),null::jsonb,'unused proof has no request');
select throws_ok($$select public.fmat_public_intake('create',null,pg_temp.input())$$,'P0001','UNAUTHORIZED','creation needs opaque proof');
select throws_ok($$select public.fmat_public_intake('create',repeat('a',64),pg_temp.input()||'{"rulesVersion":99}')$$,'P0001','REVISION_CONFLICT','changed host policy denies stale creation');
select throws_ok($$select public.fmat_public_intake('create',repeat('a',64),pg_temp.input()||'{"generation":"d3000000-0000-4000-8000-000000000099"}')$$,'P0001','REVISION_CONFLICT','replacement grant denies stale creation');
select throws_ok($$select public.fmat_public_intake('create',repeat('a',64),jsonb_set(pg_temp.input(),'{details,hostApproved}','true'))$$,'P0001','INVALID_INPUT','intake cannot supply approval');
insert into fixture select 'created',public.fmat_public_intake('create',repeat('a',64),pg_temp.input());
select is((select count(*)::int from fmat.requests where token_hash=repeat('a',64)),1,'one request created');
select is((select status from fmat.requests where token_hash=repeat('a',64)),'gathering','missing time/mode remain gathering');
select ok((select contact_verified_email is null and host_approved_version is null and requester_agreed_version is null from fmat.requests where token_hash=repeat('a',64)),'claims create no identity or decision authority');
select ok((select token_expires_at<=created_at+interval '30 days' and expires_at=created_at+interval '7 days' from fmat.requests where token_hash=repeat('a',64)),'bounded credentials and request expiry');
select is(public.fmat_public_intake('create',repeat('a',64),pg_temp.input()),(select value from fixture where name='created'),'same submission replays one result');
select is(public.fmat_public_intake('resume',repeat('a',64),'{"handle":"intake-fixture"}'),(select value from fixture where name='created'),'lost response recovers without resubmitting details');
select throws_ok($$select public.fmat_public_intake('create',repeat('a',64),jsonb_set(pg_temp.input(),'{details,purpose}','"changed"'))$$,'P0001','IDEMPOTENCY_CONFLICT','different submission cannot replace committed intent');
select is(public.fmat_public_intake('resume',repeat('b',64),'{"handle":"intake-fixture"}'),null::jsonb,'another browser gains no request');
select throws_ok($$select public.fmat_public_intake('resume',repeat('a',64),'{"handle":"another-fixture"}')$$,'P0001','NOT_FOUND','proof cannot cross handles');
update fmat.calendar_connections set revoked_at=now(),encrypted_credential=null where principal_id='d0000000-0000-4000-8000-000000000001';
select throws_ok($$select public.fmat_public_intake('context',null,'{"handle":"intake-fixture"}')$$,'P0001','NOT_FOUND','disconnected host cannot accept new intake');
select is(public.fmat_public_intake('replay',repeat('a',64),pg_temp.input()),(select value from fixture where name='created'),'provider outage does not lose committed request');
update fmat.calendar_connections set revoked_at=null,encrypted_credential='encrypted-private-fixture' where principal_id='d0000000-0000-4000-8000-000000000001';
update auth.users set banned_until=now()+interval '1 day' where id='d0000000-0000-4000-8000-000000000001';
select throws_ok($$select public.fmat_public_intake('context',null,'{"handle":"intake-fixture"}')$$,'P0001','NOT_FOUND','banned host cannot publish');
select throws_ok($$select public.fmat_public_intake('create',repeat('b',64),pg_temp.input())$$,'P0001','NOT_FOUND','banned host cannot receive a new request');
update auth.users set banned_until=null where id='d0000000-0000-4000-8000-000000000001';
update fmat.requests set status='withdrawn',token_revoked_at=now(),private_notes='PRIVATE HISTORY' where token_hash=repeat('a',64);
select is(public.fmat_public_intake('resume',repeat('a',64),'{"handle":"intake-fixture"}')->>'closed','true','closed recovery yields only a receipt destination');
select is((select count(*)::int from jsonb_object_keys(public.fmat_public_intake('resume',repeat('a',64),'{"handle":"intake-fixture"}'))),3,'recovery reveals no transcript, contact, policy, or provider tokens');
update fmat.requests set token_expires_at=now()-interval '1 second' where token_hash=repeat('a',64);
select throws_ok($$select public.fmat_public_intake('resume',repeat('a',64),'{"handle":"intake-fixture"}')$$,'P0001','NOT_FOUND','expired proof cannot restore a cookie');
update fmat.requests set token_hash=repeat('c',64),token_expires_at=now()+interval '1 day' where token_hash=repeat('a',64);
select throws_ok($$select public.fmat_public_intake('resume',repeat('a',64),'{"handle":"intake-fixture"}')$$,'P0001','NOT_FOUND','rotated proof is not mistaken for an unused attempt');
select throws_ok($$select public.fmat_public_intake('create',repeat('a',64),pg_temp.input())$$,'P0001','NOT_FOUND','rotated creation receipt cannot restore authority');
select is((select count(*)::int from fmat.requests where host_id='d0000000-0000-4000-8000-000000000001'),1,'all denied/replayed operations leave one request');
select * from finish();
rollback;
