begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select ok((select relrowsecurity from pg_class where oid='fmat.request_closures'::regclass),'closure records use RLS');
select ok(not has_table_privilege('anon','fmat.request_closures','SELECT'),'anonymous clients cannot read closure inputs');
select ok(not has_table_privilege('authenticated','fmat.request_closures','SELECT'),'authenticated clients cannot read closure inputs directly');
select ok(not has_function_privilege('anon','public.fmat_request_lifecycle(text,jsonb,jsonb)','EXECUTE'),'anonymous RPC bypass denied');
select ok(not has_function_privilege('authenticated','public.fmat_request_lifecycle(text,jsonb,jsonb)','EXECUTE'),'ordinary Auth RPC bypass denied');
select ok(has_function_privilege('service_role','public.fmat_request_lifecycle(text,jsonb,jsonb)','EXECUTE'),'only service adapter receives RPC grant');
select ok(not has_function_privilege('service_role','fmat.request_lifecycle_view(uuid,text)','EXECUTE'),'minimal status helper is internal');
select throws_ok($$select public.fmat_request_lifecycle(null,'{}','{}')$$,'P0001','INVALID_INPUT','unknown operation cannot act');
select throws_ok($$select public.fmat_request_lifecycle('withdraw','{"kind":"host"}','{}')$$,'P0001','FORBIDDEN','host cannot impersonate requester withdrawal');
select throws_ok($$select public.fmat_request_lifecycle('decline','{"kind":"guest"}','{}')$$,'P0001','FORBIDDEN','guest cannot decline as host');
select throws_ok($$select public.fmat_command('host_decline','{}','{}')$$,'P0001','FORBIDDEN','old decline is retired before replay');
select throws_ok($$select public.fmat_command('requester_withdraw','{}','{}')$$,'P0001','FORBIDDEN','old withdrawal is retired before replay');
select throws_ok($$select public.fmat_command('mutation_replay','{}','{"operation":"host_decline"}')$$,'P0001','FORBIDDEN','old decline receipt cannot bypass current explicit authority');
select * from finish();
rollback;
