begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
-- The transaction restores existing service accounting on rollback. This
-- fixture tests generation authority, independently of earlier test charges.
delete from fmat.model_budgets where name='service';
insert into auth.users(id,email,email_confirmed_at) values('92000000-0000-4000-8000-000000000001','fence@fixture.test',now());
insert into auth.sessions(id,user_id) values('92000000-0000-4000-8000-000000000002','92000000-0000-4000-8000-000000000001');
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('92000000-0000-4000-8000-000000000003','fence@fixture.test',repeat('e',64),now()+interval '1 day','fixture');
insert into fmat.hosts(id,email,invitation_id) values('92000000-0000-4000-8000-000000000001','fence@fixture.test','92000000-0000-4000-8000-000000000003');
create temporary table fixture(name text primary key,value jsonb);
insert into fixture select 'grant',public.fmat_conversation_access('open',jsonb_build_object('kind','host','subject','92000000-0000-4000-8000-000000000001','sessionId','92000000-0000-4000-8000-000000000002','expiresAt',now()+interval '1 hour'),'{"audience":"host_setup"}');
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;
create function pg_temp.scope() returns uuid language sql as $$select (pg_temp.f('grant')->>'conversationId')::uuid$$;
create function pg_temp.grant_id() returns uuid language sql as $$select (pg_temp.f('grant')->>'grantId')::uuid$$;
create function pg_temp.tool(text,text default 'context_read',jsonb default '{}') returns jsonb language sql as $$select public.fmat_conversation_tool(pg_temp.grant_id(),pg_temp.scope(),$2,$3,$1)$$;
create function pg_temp.message() returns uuid language sql as $$select (pg_temp.f('message')->>'id')::uuid$$;
create function pg_temp.deliver(text) returns jsonb language sql as $$select public.fmat_runtime_message('deliver',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('messageId',pg_temp.message(),'sessionId',$1))$$;
create function pg_temp.settle(text) returns jsonb language sql as $$select public.fmat_runtime_message('settle',pg_temp.grant_id(),pg_temp.scope(),jsonb_build_object('messageId',pg_temp.message(),'sessionId',$1,'status','completed'))$$;
create function pg_temp.reserve(text) returns jsonb language sql as $$select public.fmat_conversation_model_reserve(pg_temp.grant_id(),pg_temp.scope(),pg_temp.message(),$1)$$;
create function pg_temp.old_tool() returns jsonb language sql as $$select public.fmat_conversation_tool(pg_temp.grant_id(),pg_temp.scope(),'context_read','{}')$$;
select ok(has_function_privilege('service_role','public.fmat_conversation_tool(uuid,uuid,text,jsonb,text)','EXECUTE'),'only server runtime can use identified tool API');
select ok(not has_function_privilege(r,'public.fmat_conversation_tool(uuid,uuid,text,jsonb,text)','EXECUTE'),r||' cannot bypass application tool boundary') from unnest(array['anon','authenticated']) r;
select ok(not has_function_privilege('service_role','fmat.require_runtime_generation(fmat.conversation_scopes,text,boolean)','EXECUTE'),'generation assertion remains private');
select lives_ok($$select pg_temp.old_tool()$$,'legacy generation-zero unbound reads remain compatible');
select throws_ok($$select pg_temp.tool('unknown-runtime')$$,'P0001','FORBIDDEN','identified runtime requires canonical binding');
insert into fixture select 'message',public.fmat_runtime_message('accept',pg_temp.grant_id(),pg_temp.scope(),'{"clientId":"92000000-0000-4000-8000-000000000004","text":"Retain one effect across recovery"}');
select lives_ok($$select pg_temp.deliver('fence-original')$$,'generation-zero delivery enrolls canonical identity');
select is((select runtime_session_id from fmat.conversation_generations where conversation_id=pg_temp.scope() and generation=0),'fence-original','binding recorded in private ledger');
select lives_ok($$select pg_temp.tool('fence-original')$$,'current identified runtime can read');
select throws_ok($$select pg_temp.tool('foreign-runtime')$$,'P0001','FORBIDDEN','foreign runtime cannot use current grant');
insert into fixture values('draft','{"expectedRevision":0,"patch":{"displayName":"Saved once"},"unresolved":[],"idempotencyKey":"runtime-fence-one-effect"}');
insert into fixture select 'saved',pg_temp.tool('fence-original','setup_draft',pg_temp.f('draft'));
select lives_ok($$select pg_temp.reserve('fence-original')$$,'original model work reserves one attempt');
update fmat.runtime_messages set next_dispatch_at=clock_timestamp()-interval '1 second' where id=pg_temp.message();
insert into fixture select 'claim',row from jsonb_array_elements(public.fmat_runtime_dispatch('claim','{}')) row where row->>'messageId'=pg_temp.message()::text;
select is((select dispatch_generation from fmat.runtime_messages where id=pg_temp.message()),0::bigint,'dispatch lease captures original generation');
insert into fixture select 'before',to_jsonb(m) from fmat.runtime_messages m where id=pg_temp.message();
select lives_ok($$select fmat.conversation_recovery_begin(pg_temp.grant_id(),pg_temp.scope(),'{"expectedGeneration":0,"idempotencyKey":"92000000-0000-4000-8000-000000000005","evidence":{"generation":0,"sessionId":"fence-original","eventId":"event-terminal","tailIndex":20,"usage":{"inputTokens":20,"outputTokens":2,"cacheReadTokens":0,"cacheWriteTokens":0}}}')$$,'trusted recovery retires the old runtime');
select throws_ok($$select pg_temp.old_tool()$$,'P0001','FORBIDDEN','legacy tool reads fail closed after recovery');
select throws_ok($$select pg_temp.tool('fence-original','setup_draft',pg_temp.f('draft'))$$,'P0001','FORBIDDEN','retired runtime cannot replay a committed mutation');
select throws_ok($$select pg_temp.tool(null,'setup_draft',pg_temp.f('draft'))$$,'P0001','FORBIDDEN','identity-free mutation cannot bypass retirement');
select throws_ok($$select pg_temp.reserve('fence-original')$$,'P0001','FORBIDDEN','retired runtime cannot reserve provider work');
select throws_ok($$select pg_temp.settle('fence-original')$$,'P0001','FORBIDDEN','retired runtime cannot settle pending input');
select throws_ok($$select pg_temp.deliver('fence-original')$$,'P0001','RECONCILIATION_PENDING','retired runtime cannot rebind cleared pointer');
select throws_ok($$select pg_temp.deliver('fence-successor')$$,'P0001','RECONCILIATION_PENDING','ordinary delivery cannot choose an unleased successor');
select throws_ok($$select public.fmat_runtime_dispatch('finish',jsonb_build_object('messageId',pg_temp.message(),'leaseToken',pg_temp.f('claim')->>'leaseToken','outcome','revoked'))$$,'P0001','LEASE_LOST','old dispatcher cannot revoke pending successor work');
select is((select to_jsonb(m) from fmat.runtime_messages m where id=pg_temp.message()),pg_temp.f('before'),'all retired execution leaves pending identity and dispatch fields unchanged');
select is((select attempts from fmat.model_work_attempts where name='conversation:'||pg_temp.message()),1,'retired work consumes no new allowance');
update fmat.runtime_messages set dispatch_until=clock_timestamp()-interval '1 second' where id=pg_temp.message();
select ok(exists(select 1 from jsonb_array_elements(public.fmat_runtime_dispatch('claim','{}')) r where r->>'messageId'=pg_temp.message()::text),'authenticated dispatcher leases input awaiting explicit successor binding');
update fmat.runtime_messages set dispatch_until=clock_timestamp()-interval '1 second' where id=pg_temp.message();
-- Simulate the future leased binder; this step tests execution after an exact
-- binding, not the not-yet-implemented creation/binding protocol itself.
update fmat.conversation_scopes set runtime_session_id='fence-successor' where id=pg_temp.scope();
select throws_ok($$select pg_temp.tool('fence-successor')$$,'P0001','FORBIDDEN','scope pointer alone cannot establish a successor generation');
update fmat.conversation_generations set runtime_session_id='fence-successor' where conversation_id=pg_temp.scope() and generation=1;
select lives_ok($$select pg_temp.tool('fence-successor')$$,'current mapped successor reads within original authority');
select is(pg_temp.tool('fence-successor','setup_draft',pg_temp.f('draft')),pg_temp.f('saved'),'successor exact retry reuses prior committed effect');
select throws_ok($$select pg_temp.tool('fence-original')$$,'P0001','FORBIDDEN','old runtime cannot read after successor binding');
select throws_ok($$select pg_temp.old_tool()$$,'P0001','FORBIDDEN','legacy runtime remains denied after successor binding');
select throws_ok($$select pg_temp.deliver('fence-original')$$,'P0001','FORBIDDEN','old delivery cannot use successor binding');
select lives_ok($$select pg_temp.deliver('fence-successor')$$,'bound successor continues original pending input');
select throws_ok($$select pg_temp.reserve('fence-successor')$$,'P0001','MODEL_LIMIT','legacy reservation cannot reset successor token usage');
select lives_ok($$select public.fmat_conversation_model_reserve(pg_temp.grant_id(),pg_temp.scope(),pg_temp.message(),'fence-successor','{"inputTokens":0,"outputTokens":0,"cacheReadTokens":0,"cacheWriteTokens":0}')$$,'bound successor retains original model accounting with trusted live usage');
select is((select attempts from fmat.model_work_attempts where name='conversation:'||pg_temp.message()),2,'successor increments rather than resets attempts');
insert into fixture select 'newclaim',row from jsonb_array_elements(public.fmat_runtime_dispatch('claim','{}')) row where row->>'messageId'=pg_temp.message()::text;
select is((select dispatch_generation from fmat.runtime_messages where id=pg_temp.message()),1::bigint,'new dispatch lease captures successor generation');
select throws_ok($$select public.fmat_runtime_dispatch('finish',jsonb_build_object('messageId',pg_temp.message(),'leaseToken',pg_temp.f('claim')->>'leaseToken','outcome','revoked'))$$,'P0001','LEASE_LOST','old lease cannot finish a newly claimed generation');
select lives_ok($$select public.fmat_runtime_dispatch('finish',jsonb_build_object('messageId',pg_temp.message(),'leaseToken',pg_temp.f('newclaim')->>'leaseToken','outcome','sent'))$$,'current lease can acknowledge delivery');
update fmat.conversation_grants set expires_at=clock_timestamp()-interval '1 second' where id=pg_temp.grant_id();
select throws_ok($$select pg_temp.tool('fence-successor')$$,'P0001','UNAUTHORIZED','current runtime does not renew expired authority');
select throws_ok($$select pg_temp.reserve('fence-successor')$$,'P0001','UNAUTHORIZED','expired participant cannot reserve successor work');
select lives_ok($$select pg_temp.settle('fence-successor')$$,'canonical completion may settle after grant expiry without authorizing a reply');
select is((select status from fmat.runtime_messages where id=pg_temp.message()),'completed','only current runtime settles original input');
select * from finish();
rollback;
