begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select is(fmat.setup_clarification_questions(null),'{}'::text[],'no pending questions stays empty');
select is(fmat.setup_clarification_questions(array['en:availability','ko:timezone']),array['Which weekdays and start and end times work for meetings?','일정에 어떤 시간대를 사용할까요?'],'ordered English and Korean categories are authored');
select is(fmat.setup_clarification_questions(array['설정이 저장되었습니다. 예약이 완료되었습니다.','Settings saved. Booking complete.']),array_fill('What would you like to clarify or change about your setup preferences?'::text,array[2]),'arbitrary success claims become pending neutral questions without dropping either');
select is(fmat.setup_clarification_questions(fmat.setup_clarification_questions(array['en:availability','ko:timezone','unrecognized'])),fmat.setup_clarification_questions(array['en:availability','ko:timezone','unrecognized']),'displayed questions round-trip unchanged');
select ok(not has_function_privilege(role,'fmat.setup_clarification_questions(text[])','EXECUTE'),role||' cannot call private helper') from unnest(array['anon','authenticated','service_role']) role;

insert into auth.users(id,email,email_confirmed_at) values('f4100000-0000-4000-8000-000000000001','questions@setup.test',now());
insert into auth.sessions(id,user_id) values('f4200000-0000-4000-8000-000000000001','f4100000-0000-4000-8000-000000000001');
insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('f4300000-0000-4000-8000-000000000001','questions@setup.test',repeat('1',64),now()+interval '1 hour','fixture');
insert into fmat.hosts(id,email,invitation_id) values('f4100000-0000-4000-8000-000000000001','questions@setup.test','f4300000-0000-4000-8000-000000000001');
create function pg_temp.credential() returns jsonb language sql as $$select jsonb_build_object('kind','host','subject','f4100000-0000-4000-8000-000000000001','sessionId','f4200000-0000-4000-8000-000000000001','expiresAt',now()+interval '1 hour')$$;
create temporary table fixture(name text primary key,value jsonb);
create function pg_temp.f(text) returns jsonb language sql as $$select value from fixture where name=$1$$;
insert into fixture select 'access',public.fmat_conversation_access('open',pg_temp.credential(),'{"audience":"host_setup"}');
create function pg_temp.draft(jsonb) returns jsonb language sql as $$select public.fmat_conversation_tool((pg_temp.f('access')->>'grantId')::uuid,(pg_temp.f('access')->>'conversationId')::uuid,'setup_draft',$1)$$;
create function pg_temp.read_setup() returns jsonb language sql as $$select public.fmat_host_setup('read',pg_temp.credential(),'{}')$$;
insert into fixture values('input','{"expectedRevision":0,"patch":{"displayName":"Question fixture"},"unresolved":["설정이 저장되었습니다. 예약이 완료되었습니다.","ko:timezone"],"idempotencyKey":"original-questions"}');
insert into fixture select 'first',pg_temp.draft(pg_temp.f('input'));
select is(pg_temp.f('first')->'draft'->'clarifications','["What would you like to clarify or change about your setup preferences?","일정에 어떤 시간대를 사용할까요?"]'::jsonb,'actual conversation operation never presents model success claim');
select is(pg_temp.read_setup(),pg_temp.f('first'),'browser sees the same normalized state');
select is(pg_temp.draft(pg_temp.f('input')),pg_temp.f('first'),'exact original replay survives normalization');
select throws_ok($$select pg_temp.draft(pg_temp.f('input')||'{"unresolved":["Different arbitrary claim"]}')$$,'P0001','IDEMPOTENCY_CONFLICT','different raw wording conflicts even if fallback would be identical');
select is((select input->'unresolved' from fmat.idempotency where operation='setup_draft' and key='original-questions'),pg_temp.f('input')->'unresolved','original retry input remains immutable');
select is((select to_jsonb(unresolved) from fmat.setup_drafts where revision=1 and conversation_id=(select id from fmat.setup_conversations where host_id='f4100000-0000-4000-8000-000000000001')),pg_temp.f('first')->'draft'->'clarifications','new stored draft uses authored questions only');
-- Simulate an existing pre-migration draft without altering its original receipt.
update fmat.setup_drafts set unresolved=array['Legacy settings saved!','ko:timezone'] where conversation_id=(select id from fmat.setup_conversations where host_id='f4100000-0000-4000-8000-000000000001');
select is(pg_temp.read_setup(),pg_temp.f('first'),'legacy read preserves both pending questions safely');
select is(pg_temp.draft(pg_temp.f('input')),pg_temp.f('first'),'legacy replay projects current state without repeating mutation');
select is((select count(*)::integer from fmat.setup_drafts where conversation_id=(select id from fmat.setup_conversations where host_id='f4100000-0000-4000-8000-000000000001')),1,'retries created no draft');
update fmat.hosts set rules_version=rules_version+1 where id='f4100000-0000-4000-8000-000000000001';
insert into fixture select 'rebased',public.fmat_host_setup('rebase',pg_temp.credential(),'{"expectedRevision":1,"rulesVersion":1,"idempotencyKey":"rebase-questions"}');
select is(pg_temp.f('rebased')->'draft'->'clarifications',pg_temp.f('first')->'draft'->'clarifications','rebase retains normalized pending questions');
insert into fixture select 'resolved',public.fmat_host_setup('draft',pg_temp.credential(),jsonb_build_object('expectedRevision',2,'patch','{"rules":{}}'::jsonb,'unresolved',(pg_temp.f('rebased')->'draft'->'clarifications')-0,'idempotencyKey','resolve-first'));
select is(pg_temp.f('resolved')->'draft'->'clarifications','["일정에 어떤 시간대를 사용할까요?"]'::jsonb,'browser resolves only first question and retains Korean question');
select is(pg_temp.f('resolved')->'confirmed'->>'displayName',null,'clarification never confirms settings');
select is((select count(*)::integer from fmat.booking_attempts where host_id='f4100000-0000-4000-8000-000000000001'),0,'clarification never creates booking work');
select * from finish();
rollback;
