import {verifyCalendarReadRecovery} from './calendar-read-recovery.ts';
import {cleanupBrowserHostSql} from './browser-cleanup.ts';
import {verifyOvernightHours} from './overnight-hours.ts';
import {verifyLandingWaitlist} from './landing-waitlist.ts';
import {verifyReceiptSnapshotOrdering} from './conversation-snapshot-order.ts';
import {verifyConversationRecoveryControls} from './conversation-recovery.ts';
import {verifyHistoricalBusyReplay} from './conversation-busy-replay.ts';
import {verifyRequesterRecovery} from './requester-recovery.ts';
import {verifyRequesterEmail,emailInbox,emailReceiver} from './requester-email.ts';
import {verifyConversationReconnect} from './conversation-reconnect.ts';
import {verifyWeeklyPreview} from './weekly-preview.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {randomUUID,createHash,randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {startBrowserRuntime} from '../runtime/fixture-server.ts';
import {chromium,expect} from '@playwright/test';
import {TokenCipher} from '../../lib/server/calendar/encryption.ts';
import {beginIMessageEntry,cleanupIMessageEntry} from './imessage-entry.ts';
import {photonProject} from './setup-imessage.ts';
import {verifyPublicIntake} from './public-intake.ts';
import {verifyNoHistory} from './setup-no-history.ts';
import {LocalSql} from '../integration/local-sql.ts';

test('browser access verifies Google PKCE, invitation, logout, and request cookies without leaking credentials', {timeout:300000}, async()=>{
  const local=JSON.parse(execFileSync('supabase',['status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
  assert.ok(['localhost','127.0.0.1'].includes(new URL(local.API_URL).hostname));
  const origin='http://localhost:3000';
  const runtime=await startBrowserRuntime(local,origin);
  const child=spawn(process.execPath,['node_modules/next/dist/bin/next','start','apps/web','-p','3000'],{env:{...process.env,NODE_OPTIONS:'--import='+new URL('./google-fixture.mjs',import.meta.url).href,AGENTMAIL_INBOX_ID:emailInbox,AGENTMAIL_RECEIVER_ID:emailReceiver,OPENAI_API_KEY:'browser-ranking-fixture',OPENAI_MODEL:'gpt-6-luna',PHOTON_PROJECT_ID:photonProject,PHOTON_PROJECT_SECRET:'browser-photon-fixture',GOOGLE_CLIENT_ID:'test-client',GOOGLE_CLIENT_SECRET:'test-secret',TOKEN_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64'),APP_ORIGIN:origin,EVE_LOCAL_ORIGIN:runtime.origin,SUPABASE_URL:local.API_URL,SUPABASE_SECRET_KEY:local.SERVICE_ROLE_KEY,SUPABASE_PUBLISHABLE_KEY:local.ANON_KEY},stdio:['ignore','pipe','pipe']});
  let log='';child.stdout.on('data',v=>log+=v);child.stderr.on('data',v=>log+=v);
  const sql=new LocalSql();const email=`browser-${randomUUID()}@example.test`,invitation=randomUUID(),requestId=randomUUID();
  const token=randomBytes(32).toString('base64url'),code='ABCDEFGHIJKLMNOP';let userId:string|undefined,callback='';
  let entry:Awaited<ReturnType<typeof beginIMessageEntry>>|undefined,primaryFailure:unknown;
  const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(20000);
  page.on('request',request=>{if(request.url().startsWith(origin+'/auth/callback?code='))callback=request.url();});
  const adminHeaders={apikey:local.SERVICE_ROLE_KEY,authorization:'Bearer '+local.SERVICE_ROLE_KEY,'content-type':'application/json'};
  await mkdir('.local/rebuild/browser-screenshots',{recursive:true});
  try {
    for(let i=0;i<100;i++){assert.equal(child.exitCode,null,log.slice(-2000));try{if((await fetch(origin+'/api/health')).ok)break;}catch{}await delay(100);}
    await verifyLandingWaitlist(page,context,origin,sql);
    await page.goto(origin+'/app');await page.getByRole('button',{name:'Continue with Google'}).waitFor();
    assert.equal(await page.getByLabel('Email address').count(),0,'No email login field');
    await page.keyboard.press('Tab');assert.equal(await page.getByRole('link',{name:'Find Me a Time'}).evaluate(e=>e===document.activeElement),true);
    await page.keyboard.press('Tab');assert.equal(await page.getByRole('button',{name:'Continue with Google'}).evaluate(e=>e===document.activeElement),true);
    assert.notEqual(await page.getByRole('button',{name:'Continue with Google'}).evaluate(e=>getComputedStyle(e).outlineStyle),'none');
    await page.screenshot({path:'.local/rebuild/browser-screenshots/host-desktop.png',fullPage:true});
    const csrf=await context.request.post(origin+'/api/browser/auth/start',{headers:{origin:'https://wrong.test'},data:{email}});assert.equal(csrf.status(),403);
    for(const data of [{email},{provider:'github'},{redirectTo:'https://wrong.test'}])assert.equal((await context.request.post(origin+'/api/browser/auth/start',{headers:{origin},data})).status(),400);
    await page.goto(origin+'/auth/callback?error=access_denied&error_description=private-provider-error&next=https://wrong.test');
    await page.getByRole('alert').filter({hasText:'Google sign-in wasn’t completed'}).waitFor();assert.equal(new URL(page.url()).pathname,'/app');assert.equal(new URL(page.url()).search,'');assert.equal(await page.getByText('private-provider-error').count(),0);
    entry=await beginIMessageEntry(page,context,local,sql);
    // Fixture only at the completed Google-provider boundary. Real local Auth
    // still validates PKCE, issues the session and enforces one-time code use.
    const created=await fetch(local.API_URL+'/auth/v1/admin/users',{method:'POST',headers:adminHeaders,body:JSON.stringify({email,email_confirm:true,app_metadata:{provider:'google',providers:['google']}})});
    assert.equal(created.status,200);userId=(await created.json()).id;
    await page.route(local.API_URL+'/auth/v1/authorize?*',async route=>{
      const authorize=new URL(route.request().url());
      assert.equal(authorize.searchParams.get('provider'),'google');assert.equal(authorize.searchParams.get('redirect_to'),origin+'/auth/callback');assert.equal(authorize.searchParams.get('code_challenge_method'),'s256');assert.equal(authorize.searchParams.get('prompt'),'select_account');
      assert.deepEqual(authorize.searchParams.get('scopes')?.split(' '),['openid','email','profile']);
      const challenge=authorize.searchParams.get('code_challenge')!;assert.match(challenge,/^[A-Za-z0-9_-]{43}$/u);
      const authCode=randomUUID();
      await sql.query(`insert into auth.flow_state(id,user_id,auth_code,code_challenge_method,code_challenge,provider_type,provider_access_token,provider_refresh_token,authentication_method,created_at,updated_at,auth_code_issued_at) values('${randomUUID()}','${userId}','${authCode}','s256','${challenge}','google','','','oauth',now(),now(),now());`);
      callback=origin+'/auth/callback?code='+authCode;
      const wrong=await browser.newContext();const rejected=await wrong.request.get(callback,{maxRedirects:0});assert.equal(rejected.headers().location,origin+'/app?auth=expired');assert.equal((await wrong.request.get(origin+'/api/browser/host/state')).status(),401);await wrong.close();
      await route.fulfill({status:302,headers:{location:callback}});
    });
    const reviewTarget={requestId:randomUUID(),audience:'host_private'},reviewPath='/app?request='+reviewTarget.requestId+'&audience=host_private';
    await page.goto(origin+reviewPath);await page.getByRole('button',{name:'Continue with Google'}).waitFor();
    // Denial retains the target for a retry without allowing an arbitrary URL.
    assert.equal((await context.request.post(origin+'/api/browser/auth/start',{headers:{origin},data:{target:reviewTarget}})).status(),200);
    const returnCookie=(await context.cookies()).find(c=>c.name==='fmat-host-return');assert.equal(returnCookie?.httpOnly,true);assert.equal(returnCookie?.sameSite,'Lax');
    await page.goto(origin+'/auth/callback?error=access_denied');await page.getByRole('alert').filter({hasText:'Google sign-in wasn’t completed'}).waitFor();
    assert.equal(new URL(page.url()).pathname+new URL(page.url()).search,reviewPath);assert.equal((await context.cookies()).some(c=>c.name==='fmat-host-return'),false);
    await page.getByRole('button',{name:'Continue with Google'}).click();await page.getByRole('heading',{name:'Your invitation, please.'}).waitFor();
    assert.equal(new URL(page.url()).pathname+new URL(page.url()).search,reviewPath);assert.equal((await context.cookies()).some(c=>c.name==='fmat-host-return'),false);
    await page.goto(origin+'/app');await page.getByRole('heading',{name:'Your invitation, please.'}).waitFor();
    await page.unroute(local.API_URL+'/auth/v1/authorize?*');
    assert.equal((await context.request.post(origin+'/api/browser/imessage/continue',{headers:{origin},data:{idempotencyKey:randomUUID()}})).status(),403,'Sign-in alone cannot start private proof');
    const row=await sql.query(`select id from auth.users where email='${email}';`);assert.match(row,/^[a-f0-9-]{36}$/u);userId=row;
    await sql.query(`insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('${invitation}','${email}','${createHash('sha256').update(code).digest('hex')}',now()+interval '1 day','browser-test');`);
    await page.getByLabel('Invitation code').fill('ZZZZ-ZZZZ-ZZZZ-ZZZZ');await page.getByRole('button',{name:'Use invitation'}).click();await page.getByRole('alert').filter({hasText:'This invitation cannot be used'}).waitFor();
    await page.getByLabel('Invitation code').fill('ABCD-EFGH-IJKL-MNOP');await page.getByRole('button',{name:'Use invitation'}).click();await page.getByRole('heading',{name:'Welcome to your workspace.'}).waitFor();
    await page.reload();await page.getByRole('heading',{name:'Welcome to your workspace.'}).waitFor();
    await entry.finish(userId);await entry.cleanup();entry=undefined;
    const calendarStart=await context.request.post(origin+'/api/browser/calendar/start',{headers:{origin},data:{}});assert.equal(calendarStart.status(),200);
    const consentUrl=new URL((await calendarStart.json()).url),state=consentUrl.searchParams.get('state')!;
    assert.equal(consentUrl.origin,'https://accounts.google.com');assert.equal(consentUrl.searchParams.get('code_challenge_method'),'S256');
    assert.equal(consentUrl.searchParams.get('redirect_uri'),origin+'/connections/google/callback');assert.ok(consentUrl.searchParams.get('scope')?.includes('calendar.events'));
    assert.ok((await context.cookies()).some(c=>c.name==='fmat-google-'+state&&c.httpOnly&&c.sameSite==='Lax'));
    const wrongBrowser=await browser.newContext();const wrongCallback=await wrongBrowser.request.get(origin+'/connections/google/callback?state='+state+'&error=access_denied',{maxRedirects:0});assert.equal(wrongCallback.headers().location,origin+'/app?calendar=expired');await wrongBrowser.close();
    await page.goto(origin+'/connections/google/callback?state='+state+'&error=access_denied');await expect(page.getByRole('status').filter({hasText:'Google connection was skipped.'})).toBeFocused();
    assert.equal(new URL(page.url()).search,'');assert.equal((await context.cookies()).some(c=>c.name==='fmat-google-'+state),false);
    const replayedCalendar=await context.request.get(origin+'/connections/google/callback?state='+state+'&error=access_denied',{maxRedirects:0});assert.equal(replayedCalendar.headers().location,origin+'/app?calendar=expired');
    await page.goto(origin+'/app?calendar=connected');
    await expect(page.getByRole('status').filter({hasText:'Google access could not be confirmed.'})).toBeFocused();
    assert.equal(await page.getByText('Google connection saved.',{exact:true}).count(),0,'A forged return query cannot claim verified connection');
    await page.getByRole('region',{name:'Google Calendar connection'}).scrollIntoViewIfNeeded();
    await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-connection.png',fullPage:true});
    // Actual browser routes + local database, with Google metadata fixture at the outbound HTTP boundary.
    const calendarCipher=new TokenCipher({TOKEN_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64')});
    const encryptedCalendar=calendarCipher.seal({accessToken:'browser-calendar-fixture',refreshToken:'browser-refresh-fixture',expiresAt:Date.now()+3600000,subject:'browser-google',scopes:['openid','email','https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar.events']},'google:host:'+userId);
    await sql.query(`insert into fmat.calendar_connections(principal_kind,principal_id,provider_subject,scopes,encrypted_credential) values('host','${userId}','browser-google',array['https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar.events'],'${encryptedCalendar}');`);
    const beforeReturn=await (await context.request.get(origin+'/api/browser/setup/read')).json();
    await page.goto(origin+'/app?calendar=connected');await expect(page.getByRole('status').filter({hasText:'Google connection saved.'})).toBeFocused();
    const afterReturn=await (await context.request.get(origin+'/api/browser/setup/read')).json();assert.deepEqual(afterReturn.draft,beforeReturn.draft);assert.deepEqual(afterReturn.progress,beforeReturn.progress);
    await verifyCalendarReadRecovery(page);
    const choices=page.getByRole('region',{name:'Calendar choices'});await choices.getByRole('checkbox').first().waitFor();
    assert.equal(await choices.getByRole('checkbox',{checked:true}).count(),0,'No conflicts silently selected');
    assert.equal(await choices.getByRole('radio',{checked:true}).count(),0,'Primary is never a silent destination');
    assert.equal(await choices.getByRole('radio',{name:'My calendar (read-only)',exact:true}).isDisabled(),true);
    assert.equal(await choices.getByRole('button',{name:'Confirm calendar choices'}).isDisabled(),true);
    const catalog=await context.request.get(origin+'/api/browser/calendar/list');assert.equal(catalog.status(),200);assert.match(catalog.headers()['cache-control'],/private.*no-store/u);const catalogData=await catalog.json();
    assert.ok(!JSON.stringify(catalogData).includes('browser-calendar-fixture'));assert.ok(!JSON.stringify(catalogData).includes('encryptedCredential'));
    const invalidChoice={generation:catalogData.generation,rulesVersion:catalogData.rulesVersion,conflictCalendarIds:['personal@example.test'],bookingCalendarId:'readonly@example.test'};
    assert.equal((await context.request.post(origin+'/api/browser/calendar/select',{headers:{origin:'https://wrong.test'},data:invalidChoice})).status(),403);
    assert.equal((await context.request.post(origin+'/api/browser/calendar/select',{headers:{origin},data:invalidChoice})).status(),400);
    await choices.getByRole('checkbox').first().focus();await page.keyboard.press('Space');assert.equal(await choices.getByRole('checkbox').first().isChecked(),true);
    await choices.getByRole('radio',{name:'My calendar',exact:true}).check();await choices.getByRole('button',{name:'Confirm calendar choices'}).click();
    await choices.getByRole('status').filter({hasText:'Calendar choices saved.'}).waitFor();
    assert.equal(await sql.query(`select booking_calendar_id from fmat.hosts where id='${userId}';`),'personal@example.test');
    await expect(choices.getByRole('checkbox')).toHaveCount(0);await page.getByRole('region',{name:'Setup guide'}).getByRole('button',{name:'Skip analysis and choose preferences'}).waitFor();await expect(page.getByRole('region',{name:'Setup guide'}).getByText('Would you like suggestions from selected calendars, or choose preferences yourself?',{exact:true})).toBeFocused();
    await page.reload();await choices.getByRole('button',{name:'Change calendar choices'}).click();await choices.getByRole('checkbox',{checked:true}).waitFor();assert.equal(await choices.getByRole('radio',{checked:true}).count(),1);
    assert.notEqual(await choices.getByRole('radio',{checked:true}).evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)','Selected booking destination has a visible filled state');
    await choices.scrollIntoViewIfNeeded();await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-choices-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});await choices.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-choices-mobile.png',fullPage:true});
    await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='2';});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.evaluate(()=>{document.documentElement.style.zoom='';});
    await choices.getByRole('checkbox').first().uncheck();await choices.getByRole('button',{name:'Cancel calendar edits'}).click();await expect(choices.getByRole('button',{name:'Change calendar choices'})).toBeFocused();await expect(choices.getByRole('checkbox')).toHaveCount(0);
    await choices.getByRole('button',{name:'Change calendar choices'}).click();await expect(choices.getByRole('checkbox').first()).toBeChecked();await choices.getByRole('button',{name:'Close without saving'}).click();
    const setup=page.getByRole('region',{name:'Your meeting setup'});
    await setup.getByRole('button',{name:'Reload setup'}).click();
    const guide=setup.getByRole('region',{name:'Setup guide'});
    await guide.getByRole('button',{name:'Skip analysis and choose preferences'}).click();await setup.getByRole('status').filter({hasText:'Your setup choice is remembered.'}).waitFor();await page.reload();await guide.getByRole('button',{name:'Choose my booking profile'}).waitFor();assert.equal(await guide.getByRole('button',{name:'Skip analysis and choose preferences'}).count(),0);
    await setup.getByRole('button',{name:'Edit profile',exact:true}).click();await setup.getByLabel('Display name',{exact:true}).fill('Browser host');await setup.getByLabel('Booking name',{exact:true}).fill('browser-'+userId.slice(0,8));
    await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();await expect(setup.getByRole('status').filter({hasText:'Draft updated.'})).toBeFocused();
    await guide.scrollIntoViewIfNeeded();await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-guide-desktop.png',fullPage:true});await page.setViewportSize({width:320,height:844});await guide.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(const button of await guide.getByRole('button').all())assert.equal(await button.evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-guide-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});
    await guide.getByRole('button',{name:'Choose my own schedule'}).click();await guide.getByRole('button',{name:'Enter my schedule'}).waitFor();await page.reload();await guide.getByRole('button',{name:'Enter my schedule'}).click();
    assert.equal(await setup.getByLabel('Meeting duration (minutes)',{exact:true}).inputValue(),'');assert.equal(await setup.getByLabel('Window start 1',{exact:true}).inputValue(),'');assert.equal(await setup.getByRole('checkbox',{checked:true}).count(),0);
    await setup.getByRole('button',{name:'Cancel edit'}).click();await guide.getByRole('button',{name:'Show schedule suggestions again'}).click();await guide.getByRole('button',{name:'Use this meeting week'}).waitFor();
    const analysis=page.getByRole('region',{name:'Calendar suggestions'});
    await analysis.getByRole('button',{name:'Explore calendar suggestions'}).click();await analysis.getByRole('checkbox',{name:'Temporarily unavailable',exact:true}).check();await analysis.getByLabel('Analysis timezone',{exact:true}).fill('Asia/Seoul');
    await analysis.getByRole('button',{name:'Analyze these calendars and dates'}).click();await analysis.getByRole('alert').waitFor();
    await page.reload();await analysis.getByRole('status').filter({hasText:'Analysis did not complete.'}).waitFor();await analysis.getByRole('button',{name:'Explore calendar suggestions'}).click();assert.equal(await analysis.getByRole('checkbox',{checked:true}).count(),0,'Scan choices are explicit');await analysis.getByRole('checkbox',{name:'My calendar',exact:true}).first().check();await analysis.getByLabel('Analysis timezone',{exact:true}).fill('Asia/Seoul');await analysis.getByRole('button',{name:'Analyze these calendars and dates'}).click();await analysis.getByRole('status').filter({hasText:'Your private suggestions are ready.'}).waitFor();
    await guide.getByText('Your Calendar suggestions are ready. Review them below before choosing new defaults.',{exact:true}).waitFor();assert.equal(await guide.getByRole('button',{name:'Use this meeting week'}).count(),0,'Ready evidence takes precedence over starter guesses');
    await analysis.getByText('“Library meeting room” · 8 entries',{exact:true}).waitFor();assert.equal(await sql.query(`select rules is null from fmat.hosts where id='${userId}';`),'t');
    await page.setViewportSize({width:320,height:844});await analysis.getByRole('button',{name:'Use suggested schedule in draft'}).scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await analysis.getByRole('button',{name:'Use suggested schedule in draft'}).evaluate(e=>e.scrollWidth>e.clientWidth),false);assert.ok((await analysis.getByRole('button',{name:'Use suggested schedule in draft'}).boundingBox())!.x+(await analysis.getByRole('button',{name:'Use suggested schedule in draft'}).boundingBox())!.width<=(await analysis.boundingBox())!.x+(await analysis.boundingBox())!.width);await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-analysis-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-analysis-desktop.png',fullPage:true});
    await analysis.getByRole('button',{name:'Review and edit suggestions'}).click();const scanReview=analysis.getByRole('form',{name:'Review Calendar suggestions'});
    await scanReview.getByLabel('Suggested start 1',{exact:true}).fill('14:00');await scanReview.getByLabel('Suggested end 1',{exact:true}).fill('16:00');assert.match(await scanReview.getByRole('figure',{name:'Your suggested week preview'}).innerText(),/14:00–16:00/);await scanReview.getByRole('button',{name:'Continue suggestion review'}).click();assert.equal(await scanReview.getByRole('radio',{checked:true}).count(),0,'Evidence never preselects meeting mode');await scanReview.getByRole('radio',{name:'Either',exact:true}).check();await scanReview.getByRole('button',{name:'Continue suggestion review'}).click();assert.equal(await scanReview.getByRole('radio',{checked:true}).count(),0,'Evidence never preselects a place policy');await scanReview.getByRole('radio',{name:'Choose or enter preferred places',exact:true}).check();assert.equal(await scanReview.getByRole('checkbox',{checked:true}).count(),0,'Observed places need explicit selection');await scanReview.getByRole('checkbox',{name:'Choose candidate 1',exact:true}).check();await scanReview.getByLabel('Preferred place 1',{exact:true}).fill('Library lounge');
    await page.setViewportSize({width:320,height:844});await scanReview.getByLabel('Preferred place 1',{exact:true}).scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/scan-place-mobile.png',fullPage:true});await scanReview.getByRole('button',{name:'Continue suggestion review'}).click();await scanReview.getByRole('button',{name:'Use reviewed suggestions in draft'}).scrollIntoViewIfNeeded();assert.equal(await scanReview.getByRole('button',{name:'Use reviewed suggestions in draft'}).evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/scan-review-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await scanReview.scrollIntoViewIfNeeded();await page.screenshot({path:'.local/rebuild/browser-screenshots/scan-review-desktop.png',fullPage:true});
    await scanReview.getByRole('button',{name:'Use reviewed suggestions in draft'}).click();await analysis.getByRole('status').filter({hasText:'Suggested preferences added to your draft.'}).waitFor();
    const reviewed=(await (await context.request.get(origin+'/api/browser/setup/read')).json()).draft;assert.deepEqual(reviewed.settings.rules.locations,['Library lounge']);assert.equal(reviewed.origins['rules.locations'].source,'calendar_edited');assert.equal(reviewed.origins['rules.availability'].source,'calendar_edited');assert.equal(reviewed.origins['rules.durationMinutes'].source,'starter');assert.equal(await setup.getByRole('button',{name:'Confirm these meeting settings'}).count(),0,'Travel answers still required');
assert.equal(await sql.query(`select rules is null from fmat.hosts where id='${userId}';`),'t','Using analysis changes only the private draft');
    await setup.getByRole('button',{name:'Edit schedule',exact:true}).click();await setup.getByLabel('Meeting timezone',{exact:true}).fill('Asia/Seoul');await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();await expect(setup.getByRole('status').filter({hasText:'Draft updated.'})).toBeFocused();
    await setup.getByRole('button',{name:'Edit mode',exact:true}).click();assert.equal(await setup.getByRole('radio',{name:'Either',exact:true}).isChecked(),true,'Prior explicit review choice is reused');await setup.getByRole('radio',{name:'Online only',exact:true}).check();await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();await setup.getByRole('button',{name:'Confirm these meeting settings'}).waitFor();
    await sql.query(`update fmat.hosts set rules_version=rules_version+1 where id='${userId}';`);
    await setup.getByRole('button',{name:'Reload setup'}).click();await setup.getByRole('button',{name:'Refresh my draft'}).waitFor();assert.equal(await setup.getByRole('button',{name:'Confirm these meeting settings'}).count(),0);
    await setup.getByRole('button',{name:'Refresh my draft'}).click();await setup.getByRole('button',{name:'Confirm these meeting settings'}).waitFor();await setup.getByText('Browser host · browser-'+userId.slice(0,8),{exact:true}).waitFor();
    const draftBeforeConsent=(await (await context.request.get(origin+'/api/browser/setup/read')).json()).draft.revision;
    const setupConsent=await context.request.post(origin+'/api/browser/calendar/start',{headers:{origin},data:{}});assert.equal(setupConsent.status(),200);
    await page.goto(origin+'/connections/google/callback?state='+new URL((await setupConsent.json()).url).searchParams.get('state')+'&error=access_denied');await expect(page.getByRole('status').filter({hasText:'Google connection was skipped.'})).toBeFocused();await setup.getByRole('button',{name:'Confirm these meeting settings'}).waitFor();assert.equal((await (await context.request.get(origin+'/api/browser/setup/read')).json()).draft.revision,draftBeforeConsent);
    assert.equal(await sql.query(`select rules is null from fmat.hosts where id='${userId}';`),'t','Drafts never save settings');
    assert.equal(await setup.getByRole('button',{name:'Edit travel',exact:true}).count(),0,'Online-only skips physical travel');
    await setup.scrollIntoViewIfNeeded();await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-review-desktop.png',fullPage:true});
    await page.setViewportSize({width:320,height:844});await setup.getByRole('button',{name:'Confirm these meeting settings'}).scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-review-mobile.png',fullPage:true});
    await setup.getByRole('button',{name:'Confirm these meeting settings'}).click();await setup.getByRole('status').filter({hasText:'Settings confirmed.'}).waitFor();
    assert.equal(await sql.query(`select rules->>'meetingMode' from fmat.hosts where id='${userId}';`),'online');
    await page.reload();await setup.getByText('Your settings are confirmed.',{exact:true}).waitFor();
    await setup.getByRole('button',{name:'Edit mode',exact:true}).click();await setup.getByRole('radio',{name:'Either',exact:true}).check();await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();await expect(setup.getByRole('status').filter({hasText:'Draft updated.'})).toBeFocused();assert.equal(await setup.getByRole('button',{name:'Confirm these meeting settings'}).count(),0,'Physical mode needs explicit location and travel answers');
    await setup.getByRole('button',{name:'Edit location',exact:true}).click();await setup.getByRole('radio',{name:'Decide per meeting',exact:true}).check();await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();await expect(setup.getByRole('status').filter({hasText:'Draft updated.'})).toBeFocused();
    await guide.getByRole('button',{name:'Choose transportation'}).click();assert.equal(await setup.getByRole('radio',{checked:true}).count(),0);assert.equal(await setup.getByLabel('Extra travel buffer (minutes)',{exact:true}).count(),0,'Transportation is asked separately');await setup.getByRole('radio',{name:'Depends on the trip',exact:true}).check();await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();
    await guide.getByRole('button',{name:'Use 15 extra travel minutes'}).waitFor();await page.reload();await guide.getByRole('button',{name:'Use 15 extra travel minutes'}).waitFor();assert.equal(await guide.getByRole('button',{name:'Choose transportation'}).count(),0,'Recorded transportation is reused');await guide.getByRole('button',{name:'Adjust extra travel buffer'}).click();assert.equal(await setup.getByRole('radio').count(),0);await setup.getByLabel('Extra travel buffer (minutes)',{exact:true}).fill('15');await setup.getByRole('button',{name:'Use these preferences in my draft'}).scrollIntoViewIfNeeded();assert.equal(await setup.getByRole('button',{name:'Use these preferences in my draft'}).evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-travel-mobile.png',fullPage:true});await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();await setup.getByRole('button',{name:'Confirm these meeting settings'}).waitFor();
    await setup.getByRole('button',{name:'Confirm these meeting settings'}).click();await setup.getByRole('status').filter({hasText:'Settings confirmed.'}).waitFor();assert.equal(await sql.query(`select rules->>'travelMode' from fmat.hosts where id='${userId}';`),'PER_TRIP');assert.equal(await sql.query(`select rules->>'travelBufferMinutes' from fmat.hosts where id='${userId}';`),'15');

    await setup.getByRole('button',{name:'Edit schedule',exact:true}).click();
    await verifyOvernightHours(page,setup,context,origin);
    await verifyPublicIntake(browser,origin,sql,userId,page);
    await verifyRequesterRecovery(browser,origin,sql,userId,local);
    await page.setViewportSize({width:1280,height:900});
    await page.getByRole('button',{name:'Manage Google connection',exact:true}).click();await page.getByRole('button',{name:'Disconnect Google',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Google access has been disconnected'})).toBeFocused();assert.equal(await choices.count(),0);
    assert.equal((await context.request.get(origin+'/api/browser/calendar/list')).status(),409);
    await verifyConversationReconnect(page);
    const composer=page.getByLabel('Message your scheduling assistant');
    await sql.query(`insert into fmat.conversation_budgets values('host:${userId}',clock_timestamp(),20,clock_timestamp(),20) on conflict(name) do update set minute_used=20,minute_started_at=clock_timestamp();`);
    const throttled=page.waitForResponse(r=>r.url().includes('/conversations/')&&r.url().endsWith('/messages')&&r.request().method()==='POST');
    await composer.fill('Help me plan a focused week.');await page.getByRole('button',{name:'Send',exact:true}).click();
    assert.equal((await throttled).status(),429);
    await page.getByRole('alert').filter({hasText:'Too many messages right now'}).waitFor();
    assert.equal(await composer.inputValue(),'Help me plan a focused week.');
    await sql.query(`update fmat.conversation_budgets set minute_started_at=clock_timestamp()-interval '61 seconds' where name='host:${userId}';`);
    await page.getByRole('button',{name:'Retry same message'}).click();
    await page.getByText('Reply 1: Help me plan a focused week.',{exact:true}).waitFor();
    await page.reload();await page.getByText('Reply 1: Help me plan a focused week.',{exact:true}).waitFor();
    // Lose only the browser acknowledgment: the server still accepted the input.
    let lost=false;
    await page.route('**/api/browser/conversations/*/messages',async route=>{if(lost)return route.continue();lost=true;await route.fetch();await route.abort('failed');});
    await composer.fill('A second question after reconnect.');await page.getByRole('button',{name:'Send',exact:true}).click();
    await page.getByRole('button',{name:'Retry same message'}).waitFor();await page.getByRole('button',{name:'Retry same message'}).click();
    await page.getByText('Reply 2: A second question after reconnect.',{exact:true}).waitFor();
    await page.unroute('**/api/browser/conversations/*/messages');
    assert.equal(await sql.query(`select count(*) from fmat.runtime_messages m join fmat.conversation_scopes c on c.id=m.conversation_id where c.host_id='${userId}' and c.audience='host_setup';`),'2','Uncertain acknowledgment retries the same input');
    // Replay after a dropped stream reconstructs each message exactly once.
    let dropped=false;
    await page.route('**/api/browser/conversations/*/stream?*',async route=>{if(dropped)return route.continue();dropped=true;await route.abort('failed');});
    await page.reload();await page.getByText('Reply 2: A second question after reconnect.',{exact:true}).waitFor();
    assert.equal(await page.getByText('Reply 1: Help me plan a focused week.',{exact:true}).count(),1);
    assert.equal(await page.locator('.chat-text').count(),4);
    await page.unroute('**/api/browser/conversations/*/stream?*');
    await page.screenshot({path:'.local/rebuild/browser-screenshots/chat-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/rebuild/browser-screenshots/chat-mobile.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='2';});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:'.local/rebuild/browser-screenshots/chat-css-zoom-200.png',fullPage:true});
    await page.evaluate(()=>{document.documentElement.style.zoom='';});
    // A durable model denial settles the turn without disabling structured edits.
    const allowance=await sql.query(`select reserved_cents from fmat.model_budgets where name='host:${userId}';`);
    await sql.query(`update fmat.model_budgets set reserved_cents=3000 where name='host:${userId}';`);
    await composer.fill('A model-limited browser question.');await page.getByRole('button',{name:'Send',exact:true}).click();
    const failure=page.getByRole('alert').filter({hasText:'The response could not be completed. Your saved changes are preserved.'});
    await failure.waitFor();
    assert.equal(await sql.query(`select m.status from fmat.runtime_messages m join fmat.conversation_scopes c on c.id=m.conversation_id where c.host_id='${userId}' and m.text='A model-limited browser question.';`),'failed');
    assert.equal(await sql.query(`select count(*) from fmat.model_work_attempts w join fmat.runtime_messages m on w.name='conversation:'||m.id::text join fmat.conversation_scopes c on c.id=m.conversation_id where c.host_id='${userId}' and m.text='A model-limited browser question.';`),'0');
    await verifyHistoricalBusyReplay(page);
    await verifyReceiptSnapshotOrdering(page);
    await verifyConversationRecoveryControls(page);
    await page.reload();await failure.waitFor();await page.getByRole('button',{name:'Reconnect now'}).click();await failure.waitFor();
    await setup.getByRole('button',{name:'Edit schedule',exact:true}).click();
    await verifyWeeklyPreview(page,setup,context,origin);
    await setup.getByLabel('Meeting duration (minutes)').fill('45');
    await setup.getByRole('button',{name:'Use these preferences in my draft'}).click();
    await expect(setup.getByRole('status').filter({hasText:'Draft updated.'})).toBeFocused();
    const recovered=(await (await context.request.get(origin+'/api/browser/setup/read')).json()).draft;
    assert.equal(recovered.settings.rules.durationMinutes,45,'Structured changes remain available after model exhaustion');
    for(const [section,title] of [['profile','Your booking profile'],['schedule','Your meeting week'],['mode','How would you like to meet?'],['location','Where would you like to meet?'],['travel','How do you travel?']]){
      const trigger=setup.getByRole('button',{name:'Edit '+section,exact:true});await expect(trigger).toBeVisible();await expect(trigger).toBeEnabled();await trigger.focus();await expect(trigger).toBeFocused();await page.keyboard.press('Enter');
      const titleElement=setup.locator('legend').filter({hasText:title}).first();await expect(titleElement).toBeFocused();assert.notEqual(await titleElement.evaluate(e=>getComputedStyle(e).outlineStyle),'none');
      await setup.getByRole('button',{name:'Cancel edit'}).click();await expect(trigger).toBeFocused();
    }
    const retainedSetup=await (await context.request.get(origin+'/api/browser/setup/read')).json();
    const repeatConsent=await context.request.post(origin+'/api/browser/calendar/start',{headers:{origin},data:{}});assert.equal(repeatConsent.status(),200);
    const repeatState=new URL((await repeatConsent.json()).url).searchParams.get('state');
    await page.goto(origin+'/connections/google/callback?state='+repeatState+'&error=access_denied');
    const returnNotice=page.getByRole('status').filter({hasText:'Google connection was skipped.'});await expect(returnNotice).toBeFocused();
    const resumedSetup=await (await context.request.get(origin+'/api/browser/setup/read')).json();assert.deepEqual(resumedSetup.draft,retainedSetup.draft);assert.deepEqual(resumedSetup.progress,retainedSetup.progress);
    await page.setViewportSize({width:320,height:844});await returnNotice.focus();await expect(returnNotice).toBeInViewport();await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-return-focus-320.png'});
    await expect(setup.getByRole('button',{name:'Edit schedule',exact:true})).toBeVisible();await expect(setup.getByRole('button',{name:'Edit schedule',exact:true})).toBeEnabled();await setup.getByRole('button',{name:'Edit schedule',exact:true}).focus();await expect(setup.getByRole('button',{name:'Edit schedule',exact:true})).toBeFocused();await page.keyboard.press('Enter');const editHeading=setup.locator('legend').filter({hasText:/^Your meeting week$/});await expect(editHeading).toBeFocused();await expect(editHeading).toBeInViewport();await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-editor-focus-320.png'});
    await setup.getByRole('button',{name:'Cancel edit'}).click();await expect(setup.getByRole('button',{name:'Edit schedule',exact:true})).toBeFocused();
    await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='2';});
    await expect(setup.getByRole('button',{name:'Edit profile',exact:true})).toBeVisible();await expect(setup.getByRole('button',{name:'Edit profile',exact:true})).toBeEnabled();await setup.getByRole('button',{name:'Edit profile',exact:true}).focus();await expect(setup.getByRole('button',{name:'Edit profile',exact:true})).toBeFocused();await page.keyboard.press('Enter');const zoomHeading=setup.locator('legend').filter({hasText:/^Your booking profile$/});await expect(zoomHeading).toBeFocused();await expect(zoomHeading).toBeInViewport();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/setup-editor-focus-zoom.png'});await setup.getByRole('button',{name:'Cancel edit'}).click();await page.evaluate(()=>{document.documentElement.style.zoom='';});
    await sql.query(`update fmat.model_budgets set reserved_cents=${Number(allowance)} where name='host:${userId}';`);
    assert.equal(await page.evaluate(()=>document.cookie),'');
    const cookies=await context.cookies();assert.ok(cookies.some(c=>c.name.startsWith('fmat-auth')&&c.httpOnly&&c.sameSite==='Lax'));
    const hostResponse=await context.request.get(origin+'/api/browser/host/state');assert.equal(hostResponse.status(),200);assert.match(hostResponse.headers()['cache-control'],/private.*no-store/u);
    const copied=await browser.newContext();await copied.addCookies(cookies);
    await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('button',{name:'Continue with Google'}).waitFor();
    assert.equal((await context.request.get(origin+'/api/browser/host/state')).status(),401);
    assert.equal((await copied.request.get(origin+'/api/browser/host/state')).status(),401,'Logout invalidates a copied, unexpired session');await copied.close();
    assert.ok(callback);const replay=await context.request.get(callback,{maxRedirects:0});assert.equal(replay.status(),303);assert.equal(replay.headers().location,origin+'/app?auth=expired');
    const forged=await browser.newContext();await forged.addCookies([{name:'fmat-auth',value:'base64-forged',url:origin}]);assert.equal((await forged.request.get(origin+'/api/browser/host/state')).status(),401);await forged.close();
    await sql.query(`insert into fmat.requests(id,host_id,details,token_hash,expires_at) values('${requestId}','${userId}','{"purpose":"A protected discussion"}','${createHash('sha256').update(token).digest('hex')}',now()+interval '1 day');`);
    await page.goto(origin+'/booking/'+requestId);await page.getByRole('heading',{name:'This link is private.'}).waitFor();
    await page.goto(origin+'/booking/'+requestId+'#token='+token);await page.getByRole('heading',{name:'A protected discussion'}).waitFor();
    assert.equal(new URL(page.url()).hash,'');assert.equal(await page.evaluate(()=>document.cookie),'');
    await page.reload();await page.getByRole('heading',{name:'A protected discussion'}).waitFor();
    const guestResponse=await context.request.get(origin+'/api/browser/guest/state?requestId='+requestId);assert.match(guestResponse.headers()['cache-control'],/private.*no-store/u);
    assert.ok((await context.cookies()).some(c=>c.name==='fmat-request-'+requestId&&c.httpOnly&&c.sameSite==='Lax'));
    const other=await browser.newContext();const denied=await other.request.get(origin+'/api/browser/guest/state?requestId='+requestId);assert.equal(denied.status(),401);await other.close();
    await verifyRequesterEmail(page,context,sql,requestId);
    const guestConsent=await context.request.post(origin+'/api/browser/calendar/start',{headers:{origin},data:{requestId}});assert.equal(guestConsent.status(),200);
    const guestConsentUrl=new URL((await guestConsent.json()).url);assert.deepEqual(guestConsentUrl.searchParams.get('scope')?.split(' '),['openid','email','https://www.googleapis.com/auth/calendar.events.freebusy','https://www.googleapis.com/auth/calendar.calendarlist.readonly']);
    await page.goto(origin+'/connections/google/callback?state='+guestConsentUrl.searchParams.get('state')+'&error=access_denied');await expect(page.getByRole('status').filter({hasText:'Google connection was skipped.'})).toBeFocused();assert.equal(new URL(page.url()).pathname,'/booking/'+requestId);
    const requesterWindows=[{start:new Date(Date.now()+86400000).toISOString(),end:new Date(Date.now()+90000000).toISOString()}];
    const requesterEncrypted=calendarCipher.seal({accessToken:'browser-requester-fixture',refreshToken:'browser-requester-refresh',expiresAt:Date.now()+3600000,subject:'browser-requester',scopes:['openid','email','https://www.googleapis.com/auth/calendar.events.freebusy','https://www.googleapis.com/auth/calendar.calendarlist.readonly']},'google:guest:'+requestId);
    await sql.query(`update fmat.requests set availability_mode='calendar',details=details||'${JSON.stringify({windows:requesterWindows,timezone:'Asia/Seoul'})}'::jsonb where id='${requestId}';insert into fmat.calendar_connections(principal_kind,principal_id,provider_subject,scopes,encrypted_credential,guest_authority_key) values('guest','${requestId}','browser-requester',array['https://www.googleapis.com/auth/calendar.events.freebusy','https://www.googleapis.com/auth/calendar.calendarlist.readonly'],'${requesterEncrypted}','${createHash('sha256').update(token).digest('hex')}');`);
    await page.reload();const availability=page.getByRole('region',{name:'Your availability'});await availability.getByRole('checkbox').first().waitFor();
    assert.equal(await availability.getByRole('checkbox',{checked:true}).count(),0);await availability.getByRole('checkbox').first().check();await availability.getByRole('button',{name:'Confirm availability calendars'}).click();await availability.getByRole('status').filter({hasText:'Calendar choices saved for this request.'}).waitFor();
    await availability.getByRole('button',{name:'Check my calendars'}).click();await availability.getByRole('status').filter({hasText:'Your selected calendars were checked'}).waitFor();
    await availability.getByRole('checkbox',{name:'Temporarily unavailable'}).check();await availability.getByRole('button',{name:'Confirm availability calendars'}).click();await availability.getByRole('status').filter({hasText:'Calendar choices saved for this request.'}).waitFor();
    await availability.getByRole('button',{name:'Check my calendars'}).click();await availability.getByRole('alert').filter({hasText:'Calendar-dependent scheduling stays paused'}).waitFor();
    assert.equal(await sql.query(`select availability_failed from fmat.requests where id='${requestId}';`),'t');
    await availability.getByRole('button',{name:'Check my calendars'}).click();await availability.getByRole('status').filter({hasText:'Your selected calendars were checked'}).waitFor();
    assert.equal(await availability.getByRole('alert').count(),0);assert.equal(await sql.query(`select availability_failed from fmat.requests where id='${requestId}';`),'f');
    await availability.getByRole('button',{name:'Check my calendars'}).click();await availability.getByRole('alert').filter({hasText:'Calendar-dependent scheduling stays paused'}).waitFor();
    await availability.getByRole('button',{name:'Enter availability manually'}).click();await availability.getByLabel('Availability timezone').fill('Asia/Seoul');
    await availability.scrollIntoViewIfNeeded();await page.screenshot({path:'.local/rebuild/browser-screenshots/requester-availability-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});await availability.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/requester-availability-mobile.png',fullPage:true});
    await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await availability.getByRole('button',{name:'Use these times instead of Google Calendar'}).evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/requester-availability-320.png',fullPage:true});await page.setViewportSize({width:1280,height:900});
    await availability.getByRole('button',{name:'Use these times instead of Google Calendar'}).click();await availability.getByRole('status').filter({hasText:'Your entered times now replace Google Calendar checks'}).waitFor();
    assert.equal(await sql.query(`select availability_mode from fmat.requests where id='${requestId}';`),'manual');assert.equal(await sql.query(`select encrypted_credential is null from fmat.calendar_connections where principal_id='${requestId}';`),'t');
    await composer.fill('A private requester question.');await page.getByRole('button',{name:'Send',exact:true}).click();
    await page.getByText('Reply 1: A private requester question.',{exact:true}).waitFor();
    assert.equal(await page.getByText('Help me plan a focused week.',{exact:true}).count(),0,'Host setup never enters requester history');
    await page.reload();await page.getByText('Reply 1: A private requester question.',{exact:true}).waitFor();
    await sql.query(`update fmat.requests set status='declined',token_revoked_at=now() where id='${requestId}';`);
    await page.getByRole('heading',{name:'Meeting status'}).waitFor();assert.equal(await page.locator('.chat-text').count(),0,'Revocation removes existing transcript without a reload');assert.equal(await page.getByText('A protected discussion').count(),0);
    await page.setViewportSize({width:390,height:844});await page.goto(origin+'/app');await page.getByRole('button',{name:'Continue with Google'}).waitFor();
    await page.screenshot({path:'.local/rebuild/browser-screenshots/host-mobile.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='2';});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:'.local/rebuild/browser-screenshots/host-css-zoom-200.png',fullPage:true});
    await page.evaluate(()=>{document.documentElement.style.zoom='';});await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'Not invited yet? Join the waitlist'}).click();await page.getByLabel('Email address').fill(email);await page.getByRole('button',{name:'Join the waitlist',exact:true}).click();await page.getByRole('status').filter({hasText:'You’re on the list'}).waitFor();
    assert.equal(await sql.query(`select count(*) from fmat.waitlist where email='${email}';`),'1');
    const repeated=await context.request.post(origin+'/api/browser/waitlist',{headers:{origin},data:{email:' '+email.toUpperCase()+' ',name:'',idempotencyKey:randomUUID()}});assert.equal(repeated.status(),200);
    assert.equal(await sql.query(`select count(*) from fmat.waitlist where email='${email}';`),'1');
    await verifyNoHistory(browser,origin,local,sql);
  }catch(error){
    primaryFailure=error;
    await writeFile('.local/rebuild/photon-browser-failure.log',String(error instanceof Error?error.stack:error));
    // Capture control state without cookies, tokens, URLs or entered content.
    const controls=await page.locator('[aria-label="Private scheduling review"]').evaluateAll(regions=>regions.map(region=>({
      busy:region.getAttribute('aria-busy'),forms:Array.from(region.querySelectorAll('form')).map(form=>({
        name:form.getAttribute('aria-label'),
        choices:Array.from(form.querySelectorAll('[role="radio"],[role="checkbox"]')).map(element=>({role:element.getAttribute('role'),checked:element.getAttribute('aria-checked'),disabled:element.matches(':disabled'),value:element.getAttribute('value')})),
        reasons:Array.from(form.querySelectorAll('textarea')).map(element=>({length:element.value.length,disabled:element.disabled})),
        submit:Array.from(form.querySelectorAll('button[type="submit"]')).map(element=>({disabled:element.matches(':disabled')})),
      })),
    }))).catch(()=>[]);
    await writeFile('.local/rebuild/browser-control-failure.json',JSON.stringify(controls,null,2));throw error;
  }finally{
    await page.screenshot({path:'.local/rebuild/browser-screenshots/last-state.png',fullPage:true}).catch(()=>{});
    await browser.close();await runtime.stop();if(child.exitCode===null){const closed=once(child,'close');child.kill('SIGTERM');await closed;}await writeFile('.local/rebuild/browser-server.log',log);
    await cleanupIMessageEntry(sql).catch(()=>{});
    userId ||= await sql.query(`select id from auth.users where email='${email}';`);
    const cleanupId=userId||'00000000-0000-4000-8000-000000000000';
    await sql.query(cleanupBrowserHostSql(cleanupId,requestId,invitation,email)).catch(error=>{
      if(primaryFailure!==undefined)throw new AggregateError([primaryFailure,error],'Browser assertion and fixture cleanup both failed');
      throw error;
    }).finally(()=>sql.close());
    if(userId)await fetch(local.API_URL+'/auth/v1/admin/users/'+userId,{method:'DELETE',headers:adminHeaders});
  }
});
