import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {randomUUID,createHash,randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {startBrowserRuntime} from '../runtime/fixture-server.ts';
import {chromium} from '@playwright/test';
import {TokenCipher} from '../../lib/server/calendar/encryption.ts';
import {LocalSql} from '../integration/local-sql.ts';

test('browser access verifies email, invitation, logout, and request cookies without leaking credentials', {timeout:300000}, async()=>{
  const local=JSON.parse(execFileSync('supabase',['status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
  assert.ok(['localhost','127.0.0.1'].includes(new URL(local.API_URL).hostname));
  const origin='http://localhost:3000';
  const runtime=await startBrowserRuntime(local,origin);
  const child=spawn(process.execPath,['node_modules/next/dist/bin/next','start','apps/web','-p','3000'],{env:{...process.env,NODE_OPTIONS:'--import='+new URL('./google-fixture.mjs',import.meta.url).href,GOOGLE_CLIENT_ID:'test-client',GOOGLE_CLIENT_SECRET:'test-secret',TOKEN_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64'),APP_ORIGIN:origin,EVE_LOCAL_ORIGIN:runtime.origin,SUPABASE_URL:local.API_URL,SUPABASE_SECRET_KEY:local.SERVICE_ROLE_KEY,SUPABASE_PUBLISHABLE_KEY:local.ANON_KEY},stdio:['ignore','pipe','pipe']});
  let log='';child.stdout.on('data',v=>log+=v);child.stderr.on('data',v=>log+=v);
  const sql=new LocalSql();const email=`browser-${randomUUID()}@example.test`,invitation=randomUUID(),requestId=randomUUID();
  const token=randomBytes(32).toString('base64url'),code='ABCDEFGHIJKLMNOP';let userId:string|undefined,callback='';
  const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(20000);
  page.on('request',request=>{if(request.url().startsWith(origin+'/auth/callback?code='))callback=request.url();});
  const adminHeaders={apikey:local.SERVICE_ROLE_KEY,authorization:'Bearer '+local.SERVICE_ROLE_KEY,'content-type':'application/json'};
  await mkdir('.local/rebuild/browser-screenshots',{recursive:true});
  try {
    for(let i=0;i<100;i++){assert.equal(child.exitCode,null,log.slice(-2000));try{if((await fetch(origin+'/api/health')).ok)break;}catch{}await delay(100);}
    await page.goto(origin+'/app');await page.getByLabel('Email address').waitFor();
    await page.keyboard.press('Tab');assert.equal(await page.getByRole('link',{name:'Find Me a Time'}).evaluate(e=>e===document.activeElement),true);
    await page.keyboard.press('Tab');assert.equal(await page.getByLabel('Email address').evaluate(e=>e===document.activeElement),true);
    await page.keyboard.press('Tab');assert.equal(await page.getByRole('button',{name:'Email me a sign-in link'}).evaluate(e=>e===document.activeElement),true);
    assert.notEqual(await page.getByRole('button',{name:'Email me a sign-in link'}).evaluate(e=>getComputedStyle(e).outlineStyle),'none');
    await page.screenshot({path:'.local/rebuild/browser-screenshots/host-desktop.png',fullPage:true});
    const csrf=await context.request.post(origin+'/api/browser/auth/start',{headers:{origin:'https://wrong.test'},data:{email}});assert.equal(csrf.status(),403);
    await page.getByLabel('Email address').fill(email);await page.getByRole('button',{name:'Email me a sign-in link'}).click();
    await page.getByRole('status').filter({hasText:'Check your email'}).waitFor();
    let link='';
    for(let n=0;n<50;n++){
      const list=await fetch(local.MAILPIT_URL+'/api/v1/messages').then(r=>r.json());
      const found=list.messages.find((m:{To:{Address:string}[]})=>m.To.some(to=>to.Address===email));
      if(found){const mail=await fetch(local.MAILPIT_URL+'/api/v1/message/'+found.ID).then(r=>r.json());link=mail.Text.match(/https?:\/\/[^\s<>]+\/auth\/v1\/verify[^\s<>]+/u)?.[0]??'';if(link)break;}await delay(100);
    }
    assert.ok(link,'Local Auth email contains a sign-in link');
    await page.goto(link);await page.getByRole('heading',{name:'Your invitation, please.'}).waitFor();
    const row=await sql.query(`select id from auth.users where email='${email}';`);assert.match(row,/^[a-f0-9-]{36}$/u);userId=row;
    await sql.query(`insert into fmat.invitations(id,email,token_hash,expires_at,issued_by) values('${invitation}','${email}','${createHash('sha256').update(code).digest('hex')}',now()+interval '1 day','browser-test');`);
    await page.getByLabel('Invitation code').fill('ZZZZ-ZZZZ-ZZZZ-ZZZZ');await page.getByRole('button',{name:'Use invitation'}).click();await page.getByRole('alert').filter({hasText:'This invitation cannot be used'}).waitFor();
    await page.getByLabel('Invitation code').fill('ABCD-EFGH-IJKL-MNOP');await page.getByRole('button',{name:'Use invitation'}).click();await page.getByRole('heading',{name:'Welcome to your workspace.'}).waitFor();
    await page.reload();await page.getByRole('heading',{name:'Welcome to your workspace.'}).waitFor();
    const calendarStart=await context.request.post(origin+'/api/browser/calendar/start',{headers:{origin},data:{}});assert.equal(calendarStart.status(),200);
    const consentUrl=new URL((await calendarStart.json()).url),state=consentUrl.searchParams.get('state')!;
    assert.equal(consentUrl.origin,'https://accounts.google.com');assert.equal(consentUrl.searchParams.get('code_challenge_method'),'S256');
    assert.equal(consentUrl.searchParams.get('redirect_uri'),origin+'/connections/google/callback');assert.ok(consentUrl.searchParams.get('scope')?.includes('calendar.events'));
    assert.ok((await context.cookies()).some(c=>c.name==='fmat-google-'+state&&c.httpOnly&&c.sameSite==='Lax'));
    const wrongBrowser=await browser.newContext();const wrongCallback=await wrongBrowser.request.get(origin+'/connections/google/callback?state='+state+'&error=access_denied',{maxRedirects:0});assert.equal(wrongCallback.headers().location,origin+'/app?calendar=expired');await wrongBrowser.close();
    await page.goto(origin+'/connections/google/callback?state='+state+'&error=access_denied');await page.getByRole('status').filter({hasText:'Google connection was skipped.'}).waitFor();
    assert.equal(new URL(page.url()).search,'');assert.equal((await context.cookies()).some(c=>c.name==='fmat-google-'+state),false);
    const replayedCalendar=await context.request.get(origin+'/connections/google/callback?state='+state+'&error=access_denied',{maxRedirects:0});assert.equal(replayedCalendar.headers().location,origin+'/app?calendar=expired');
    await page.goto(origin+'/app?calendar=connected');
    await page.getByRole('status').filter({hasText:'Google access could not be confirmed.'}).waitFor();
    assert.equal(await page.getByText('Google connection saved.',{exact:true}).count(),0,'A forged return query cannot claim verified connection');
    await page.getByRole('region',{name:'Google Calendar connection'}).scrollIntoViewIfNeeded();
    await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-connection.png',fullPage:true});
    // Actual browser routes + local database, with Google metadata fixture at the outbound HTTP boundary.
    const calendarCipher=new TokenCipher({TOKEN_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64')});
    const encryptedCalendar=calendarCipher.seal({accessToken:'browser-calendar-fixture',refreshToken:'browser-refresh-fixture',expiresAt:Date.now()+3600000,subject:'browser-google',scopes:['openid','email','https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar.events']},'google:host:'+userId);
    await sql.query(`insert into fmat.calendar_connections(principal_kind,principal_id,provider_subject,scopes,encrypted_credential) values('host','${userId}','browser-google',array['https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar.events'],'${encryptedCalendar}');`);
    await page.reload();const choices=page.getByRole('region',{name:'Calendar choices'});await choices.getByRole('checkbox').first().waitFor();
    assert.equal(await choices.getByRole('checkbox',{checked:true}).count(),0,'No conflicts silently selected');
    assert.equal(await choices.getByRole('radio',{checked:true}).count(),0,'Primary is never a silent destination');
    assert.equal(await choices.getByRole('radio',{name:'My calendar (read-only)',exact:true}).isDisabled(),true);
    assert.equal(await choices.getByRole('button',{name:'Confirm calendar choices'}).isDisabled(),true);
    const catalog=await context.request.get(origin+'/api/browser/calendar/list');assert.equal(catalog.status(),200);assert.match(catalog.headers()['cache-control'],/private.*no-store/u);const catalogData=await catalog.json();
    assert.ok(!JSON.stringify(catalogData).includes('browser-calendar-fixture'));assert.ok(!JSON.stringify(catalogData).includes('encryptedCredential'));
    const invalidChoice={generation:catalogData.generation,rulesVersion:catalogData.rulesVersion,conflictCalendarIds:['personal@example.test'],bookingCalendarId:'readonly@example.test'};
    assert.equal((await context.request.post(origin+'/api/browser/calendar/select',{headers:{origin:'https://wrong.test'},data:invalidChoice})).status(),403);
    assert.equal((await context.request.post(origin+'/api/browser/calendar/select',{headers:{origin},data:invalidChoice})).status(),400);
    await choices.getByRole('checkbox').first().focus();await page.keyboard.press('Space');assert.equal(await choices.getByRole('checkbox').first().isChecked(),true);
    await choices.getByRole('radio',{name:'My calendar',exact:true}).check();await choices.getByRole('button',{name:'Confirm calendar choices'}).click();
    await choices.getByRole('status').filter({hasText:'Calendar choices saved.'}).waitFor();
    assert.equal(await sql.query(`select booking_calendar_id from fmat.hosts where id='${userId}';`),'personal@example.test');
    await page.reload();await choices.getByRole('checkbox',{checked:true}).waitFor();assert.equal(await choices.getByRole('radio',{checked:true}).count(),1);
    assert.notEqual(await choices.getByRole('radio',{checked:true}).evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)','Selected booking destination has a visible filled state');
    await choices.scrollIntoViewIfNeeded();await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-choices-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});await choices.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/rebuild/browser-screenshots/calendar-choices-mobile.png',fullPage:true});
    await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='2';});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.evaluate(()=>{document.documentElement.style.zoom='';});
    await page.getByRole('button',{name:'Disconnect Google',exact:true}).click();await page.getByRole('status').filter({hasText:'Google access has been disconnected'}).waitFor();assert.equal(await choices.count(),0);
    assert.equal((await context.request.get(origin+'/api/browser/calendar/list')).status(),409);
    const composer=page.getByLabel('Message your scheduling assistant');
    await composer.fill('Help me plan a focused week.');await page.getByRole('button',{name:'Send',exact:true}).click();
    await page.getByText('Reply 1: Help me plan a focused week.',{exact:true}).waitFor();
    await page.reload();await page.getByText('Reply 1: Help me plan a focused week.',{exact:true}).waitFor();
    // Lose only the browser acknowledgment: the server still accepted the input.
    let lost=false;
    await page.route('**/api/browser/conversations/*/messages',async route=>{if(lost)return route.continue();lost=true;await route.fetch();await route.abort('failed');});
    await composer.fill('A second question after reconnect.');await page.getByRole('button',{name:'Send',exact:true}).click();
    await page.getByRole('button',{name:'Retry same message'}).waitFor();await page.getByRole('button',{name:'Retry same message'}).click();
    await page.getByText('Reply 2: A second question after reconnect.',{exact:true}).waitFor();
    await page.unroute('**/api/browser/conversations/*/messages');
    assert.equal(await sql.query(`select count(*) from fmat.runtime_messages m join fmat.conversation_scopes c on c.id=m.conversation_id where c.host_id='${userId}' and c.audience='host_setup';`),'2','Uncertain acknowledgment retries the same input');
    // Replay after a dropped stream reconstructs each message exactly once.
    let dropped=false;
    await page.route('**/api/browser/conversations/*/stream?*',async route=>{if(dropped)return route.continue();dropped=true;await route.abort('failed');});
    await page.reload();await page.getByText('Reply 2: A second question after reconnect.',{exact:true}).waitFor();
    assert.equal(await page.getByText('Reply 1: Help me plan a focused week.',{exact:true}).count(),1);
    assert.equal(await page.locator('.chat-text').count(),4);
    await page.unroute('**/api/browser/conversations/*/stream?*');
    await page.screenshot({path:'.local/rebuild/browser-screenshots/chat-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/rebuild/browser-screenshots/chat-mobile.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='2';});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:'.local/rebuild/browser-screenshots/chat-css-zoom-200.png',fullPage:true});
    await page.evaluate(()=>{document.documentElement.style.zoom='';});
    assert.equal(await page.evaluate(()=>document.cookie),'');
    const cookies=await context.cookies();assert.ok(cookies.some(c=>c.name.startsWith('fmat-auth')&&c.httpOnly&&c.sameSite==='Lax'));
    const hostResponse=await context.request.get(origin+'/api/browser/host/state');assert.equal(hostResponse.status(),200);assert.match(hostResponse.headers()['cache-control'],/private.*no-store/u);
    const copied=await browser.newContext();await copied.addCookies(cookies);
    await page.getByRole('button',{name:'Sign out'}).click();await page.getByLabel('Email address').waitFor();
    assert.equal((await context.request.get(origin+'/api/browser/host/state')).status(),401);
    assert.equal((await copied.request.get(origin+'/api/browser/host/state')).status(),401,'Logout invalidates a copied, unexpired session');await copied.close();
    assert.ok(callback);const replay=await context.request.get(callback,{maxRedirects:0});assert.equal(replay.status(),303);assert.equal(replay.headers().location,origin+'/app?auth=expired');
    const forged=await browser.newContext();await forged.addCookies([{name:'fmat-auth',value:'base64-forged',url:origin}]);assert.equal((await forged.request.get(origin+'/api/browser/host/state')).status(),401);await forged.close();
    await sql.query(`insert into fmat.requests(id,host_id,details,token_hash,expires_at) values('${requestId}','${userId}','{"purpose":"A protected discussion"}','${createHash('sha256').update(token).digest('hex')}',now()+interval '1 day');`);
    await page.goto(origin+'/booking/'+requestId);await page.getByRole('heading',{name:'This link is private.'}).waitFor();
    await page.goto(origin+'/booking/'+requestId+'#token='+token);await page.getByRole('heading',{name:'A protected discussion'}).waitFor();
    assert.equal(new URL(page.url()).hash,'');assert.equal(await page.evaluate(()=>document.cookie),'');
    await page.reload();await page.getByRole('heading',{name:'A protected discussion'}).waitFor();
    const guestResponse=await context.request.get(origin+'/api/browser/guest/state?requestId='+requestId);assert.match(guestResponse.headers()['cache-control'],/private.*no-store/u);
    assert.ok((await context.cookies()).some(c=>c.name==='fmat-request-'+requestId&&c.httpOnly&&c.sameSite==='Lax'));
    const other=await browser.newContext();const denied=await other.request.get(origin+'/api/browser/guest/state?requestId='+requestId);assert.equal(denied.status(),401);await other.close();
    const guestConsent=await context.request.post(origin+'/api/browser/calendar/start',{headers:{origin},data:{requestId}});assert.equal(guestConsent.status(),200);
    const guestConsentUrl=new URL((await guestConsent.json()).url);assert.deepEqual(guestConsentUrl.searchParams.get('scope')?.split(' '),['openid','email','https://www.googleapis.com/auth/calendar.freebusy']);
    await page.goto(origin+'/connections/google/callback?state='+guestConsentUrl.searchParams.get('state')+'&error=access_denied');await page.getByRole('status').filter({hasText:'Google connection was skipped.'}).waitFor();assert.equal(new URL(page.url()).pathname,'/booking/'+requestId);
    await composer.fill('A private requester question.');await page.getByRole('button',{name:'Send',exact:true}).click();
    await page.getByText('Reply 1: A private requester question.',{exact:true}).waitFor();
    assert.equal(await page.getByText('Help me plan a focused week.',{exact:true}).count(),0,'Host setup never enters requester history');
    await page.reload();await page.getByText('Reply 1: A private requester question.',{exact:true}).waitFor();
    await sql.query(`update fmat.requests set status='declined',token_revoked_at=now() where id='${requestId}';`);
    await page.getByRole('heading',{name:'Meeting status'}).waitFor();assert.equal(await page.locator('.chat-text').count(),0,'Revocation removes existing transcript without a reload');assert.equal(await page.getByText('A protected discussion').count(),0);
    await page.setViewportSize({width:390,height:844});await page.goto(origin+'/app');await page.getByLabel('Email address').waitFor();
    await page.screenshot({path:'.local/rebuild/browser-screenshots/host-mobile.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='2';});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:'.local/rebuild/browser-screenshots/host-css-zoom-200.png',fullPage:true});
    await page.evaluate(()=>{document.documentElement.style.zoom='';});await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'Not invited yet? Join the waitlist'}).click();await page.getByLabel('Email address').fill(email);await page.getByRole('button',{name:'Join the waitlist',exact:true}).click();await page.getByRole('status').filter({hasText:'You’re on the list'}).waitFor();
    assert.equal(await sql.query(`select count(*) from fmat.waitlist where email='${email}';`),'1');
    const repeated=await context.request.post(origin+'/api/browser/waitlist',{headers:{origin},data:{email:' '+email.toUpperCase()+' ',name:'',idempotencyKey:randomUUID()}});assert.equal(repeated.status(),200);
    assert.equal(await sql.query(`select count(*) from fmat.waitlist where email='${email}';`),'1');
  }finally{
    await page.screenshot({path:'.local/rebuild/browser-screenshots/last-state.png',fullPage:true}).catch(()=>{});
    await browser.close();await runtime.stop();if(child.exitCode===null){const closed=once(child,'close');child.kill('SIGTERM');await closed;}await writeFile('.local/rebuild/browser-server.log',log);
    userId ||= await sql.query(`select id from auth.users where email='${email}';`);
    const cleanupId=userId||'00000000-0000-4000-8000-000000000000';
    await sql.query(`delete from fmat.audit_events where subject_id in(select id::text from fmat.oauth_exchanges where actor->>'id'='${cleanupId}' or actor->>'requestId'='${requestId}');delete from fmat.oauth_exchanges where actor->>'id'='${cleanupId}' or actor->>'requestId'='${requestId}';delete from fmat.runtime_messages where conversation_id in(select id from fmat.conversation_scopes where host_id='${cleanupId}');delete from fmat.conversation_grants where conversation_id in(select id from fmat.conversation_scopes where host_id='${cleanupId}');delete from fmat.conversation_scopes where host_id='${cleanupId}';delete from fmat.request_history where request_id='${requestId}';delete from fmat.requests where id='${requestId}';delete from fmat.idempotency where actor_scope='host:${cleanupId}' or input->>'email'='${email}';delete from fmat.audit_events where subject_id in ('${cleanupId}','${invitation}');delete from fmat.calendar_connections where principal_id='${userId}';delete from fmat.hosts where id='${cleanupId}';delete from fmat.invitations where id='${invitation}';delete from fmat.waitlist where email='${email}';`).finally(()=>sql.close());
    if(userId)await fetch(local.API_URL+'/auth/v1/admin/users/'+userId,{method:'DELETE',headers:adminHeaders});
  }
});
