import {confirmedBookingReceipt,bookingJoinUrl} from '../../contracts/booking-receipt.ts';
import {preparedEmail,type PreparedEmail} from './cloudflare.ts';
const escape=(value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export function bookingEmail(input:{id:string;accountId:string;to:string;receipt:unknown;viewUrl:string}):PreparedEmail{
 const receipt=confirmedBookingReceipt.parse(input.receipt),url=new URL(input.viewUrl);
 if(url.protocol!=='https:'||url.username||url.password||!receipt.organizer)throw new Error('INVALID_BOOKING_EMAIL');
 const format=new Intl.DateTimeFormat('en',{dateStyle:'full',timeStyle:'short',timeZone:receipt.timezone}),join=bookingJoinUrl(receipt);
 const rows=[['Purpose',receipt.purpose],['Starts',format.format(new Date(receipt.start))],['Ends',format.format(new Date(receipt.end))],['Timezone',receipt.timezone],['Duration',`${(Date.parse(receipt.end)-Date.parse(receipt.start))/60000} minutes`],['Calendar organizer',receipt.organizer.email],['Participants',receipt.participants.map(p=>p.email).join(', ')],[receipt.mode==='online'?'Meeting link':'Location',receipt.location]];
 const text=['Meeting confirmed',receipt.title,...rows.map(([key,value])=>`${key}: ${value}`),...(join?['Join meeting: '+join]:[]),'View booking: '+url.href,'For changes after booking, use your calendar.','Sent by Find Me a Time. The Calendar organizer is shown above.'].join('\n\n');
 const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:24px;font-family:Arial,sans-serif;color:#18251c;background:#f8faf8"><main style="max-width:600px;margin:auto;padding:24px;background:#ffffff;border-radius:16px;overflow-wrap:anywhere"><p>Find Me a Time</p><h1>Meeting confirmed</h1><h2>'+escape(receipt.title)+'</h2><dl>'+rows.map(([key,value])=>'<dt style="margin-top:16px;font-weight:bold">'+escape(key)+'</dt><dd style="margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere">'+escape(value)+'</dd>').join('')+'</dl><p style="line-height:2">'+(join?'<a href="'+escape(join)+'">Join meeting</a><br>':'')+'<a href="'+escape(url.href)+'">View booking</a></p><p>For changes after booking, use your calendar.</p><p>Sent by Find Me a Time. The Calendar organizer is shown above.</p></main></body></html>';
 return preparedEmail.parse({id:input.id,accountId:input.accountId,message:{from:'no-reply@findmeatime.com',to:input.to,subject:('Confirmed: '+receipt.title).replace(/[\r\n]+/gu,' ').slice(0,200),html,text}});
}
