"use client";
type Slot = { label: string; reason: string; rank: number };
type Request = { id: string; requester_name: string; requester_email: string; purpose: string; duration_minutes: number; location: string; candidate_slots: Slot[]; status: string; confirmed_start: string | null; google_event_url: string | null; created_at: string };
export type Share = { id: string; created_at: string; meeting_requests: Request[] };


export default function ReceivedRequests({ shares }: { shares: Share[] }) {
  return <section className="mt-8"><h2 className="text-xl font-semibold">받은 요청</h2>{shares.length === 0 ? <div className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">아직 받은 요청이 없습니다. 요청 링크를 만들어 상대방에게 공유해 주세요.</div> : <div className="mt-4 space-y-4">{shares.map((share) => <article key={share.id} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-semibold">링크 · {new Date(share.created_at).toLocaleDateString("ko-KR")}</h3>{share.meeting_requests.length === 0 ? <p className="mt-3 text-sm text-slate-500">아직 들어온 요청이 없습니다.</p> : <div className="mt-4 space-y-4">{share.meeting_requests.map((request) => <div key={request.id} className="border-t border-slate-100 pt-4"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold">{request.purpose}</h4><span className="text-sm text-slate-500">{request.duration_minutes}분 · {request.location || "장소 미정"}</span></div><p className="mt-1 text-sm text-slate-600">{request.requester_name} · {request.requester_email}</p><div className="mt-3 grid gap-3 md:grid-cols-3">{(request.candidate_slots ?? []).map((slot) => <div key={slot.label} className="rounded-xl bg-slate-50 p-4"><p className="font-medium">{slot.rank}순위 · {slot.label}</p><p className="mt-2 text-sm text-slate-600">{slot.reason}</p></div>)}</div><p className="mt-3 text-xs text-slate-500">{request.status === "approved" ? "수락 완료 · Google Calendar에 등록되었습니다." : request.status === "confirming" ? "일정 등록 중 · 링크 상세에서 등록 결과를 확인해 주세요." : request.status === "calendar_conflict" ? "Google에서 일정이 변경되어 확인이 필요합니다." : "후보 추천 상태 · 일정은 아직 확정되지 않았습니다."}</p></div>)}</div>}</article>)}</div>}</section>;
}
