'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {analysisState,type AnalysisState} from '../../../lib/contracts/calendar-analysis.ts';
import {calendarCatalog,type CalendarCatalog} from '../../../lib/contracts/calendar.ts';
import type {SetupState} from '../../../lib/contracts/setup.ts';
import {Button} from './ui/button';import {Input} from './ui/input';import {Checkbox} from './ui/checkbox';
import {Field,FieldLabel,FieldDescription,FieldSet,FieldLegend,FieldContent} from './ui/field';
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
async function call(action:string,input?:unknown){const response=await fetch('/api/browser/'+action,{method:input===undefined?'GET':'POST',cache:'no-store',signal:AbortSignal.timeout(55_000),headers:{'content-type':'application/json'},...(input===undefined?{}:{body:JSON.stringify(input)})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message??'Calendar analysis is unavailable. Try again or edit your preferences.');return data;}
export function CalendarAnalysis({setup,disabled,onChange,onSkip}:{setup:SetupState;disabled:boolean;onChange:()=>Promise<void>;onSkip:()=>void}){
 const id=useId(),[state,setState]=useState<AnalysisState|null>(null),[catalog,setCatalog]=useState<CalendarCatalog|null>(null),[form,setForm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [ids,setIds]=useState<string[]>([]),[start,setStart]=useState(new Date().toISOString().slice(0,10)),[end,setEnd]=useState(new Date(Date.now()+28*86400000).toISOString().slice(0,10)),[zone,setZone]=useState(setup.draft?.settings.rules?.timezone??setup.confirmed.rules?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone);
 const pending=useRef<{action:string;body:Record<string,unknown>;signature:string}|null>(null);
 useEffect(()=>{let active=true;const refresh=()=>void call('analysis/read').then(data=>{if(active)setState(analysisState.parse(data));}).catch(e=>{if(active)setError(e.message);});refresh();const timer=setInterval(refresh,30_000);return()=>{active=false;clearInterval(timer);};},[setup.revision,setup.rulesVersion,setup.calendarGeneration]);
 async function open(){setBusy(true);setError('');try{setCatalog(calendarCatalog.parse(await call('calendar/list')));setForm(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function mutate(action:string,body:Record<string,unknown>){const signature=JSON.stringify({action,body});if(pending.current&&pending.current.signature!==signature){setError('Reload analysis before another action; the earlier result is not confirmed.');return;}pending.current??={action,body:{...body,idempotencyKey:crypto.randomUUID()},signature};setBusy(true);setError('');try{const next=analysisState.parse(await call('analysis/'+action,pending.current.body));await onChange();setState(next);pending.current=null;setForm(false);}catch(e){setError((e as Error).message);try{await onChange();}catch{/* Preserve the operation error; reload can recover current state. */}}finally{setBusy(false);}}
 const scan=state?.scan,summary=scan?.summary,locked=disabled||busy;
 return <section role="region" aria-label="Calendar suggestions" className="flex min-w-0 flex-col gap-3" aria-busy={busy}>
  <p>Optional Calendar suggestions</p><p className="text-sm">Choose calendars and a date range before any event scan. Only private patterns and repeated places are retained; titles, descriptions and attendee identities are excluded. You can always edit preferences manually.</p>
  {setup.calendarGeneration&&!form?<Button variant="outline" disabled={locked} onClick={()=>void open()}>Explore calendar suggestions</Button>:null}
  {form&&catalog?<form onSubmit={e=>{e.preventDefault();void mutate('start',{expectedRevision:setup.revision,rulesVersion:catalog.rulesVersion,generation:catalog.generation,calendarIds:ids,startDate:start,endDate:end,timezone:zone,consented:true});}}><FieldSet disabled={locked}><FieldLegend>Choose what to analyze</FieldLegend><FieldDescription>Choose 1–10 calendars and 14–56 days within 90 days of today. This selection only controls this scan. Results last 15 minutes. Limits: 10,000 events, ten pages per calendar and a 20-second event-read deadline; an incomplete read produces no suggestions.</FieldDescription>
   {catalog.calendars.map((c,i)=><Field key={c.id} orientation="horizontal"><Checkbox id={id+i} disabled={c.accessRole==='freeBusyReader'} checked={ids.includes(c.id)} onCheckedChange={checked=>setIds(current=>checked?[...current,c.id]:current.filter(v=>v!==c.id))}/><FieldContent className="min-w-0 break-words"><FieldLabel htmlFor={id+i}>{c.name}</FieldLabel><FieldDescription className="break-all">{c.id} · {c.timeZone??'Calendar timezone'}{c.accessRole==='freeBusyReader'?' · Event details unavailable':''}</FieldDescription></FieldContent></Field>)}
   <Field><FieldLabel htmlFor={id+'start'}>Analysis start date</FieldLabel><Input id={id+'start'} type="date" value={start} onChange={e=>setStart(e.target.value)} required/></Field>
   <Field><FieldLabel htmlFor={id+'end'}>Analysis end date (exclusive)</FieldLabel><Input id={id+'end'} type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></Field>
   <Field><FieldLabel htmlFor={id+'zone'}>Analysis timezone</FieldLabel><Input id={id+'zone'} value={zone} onChange={e=>setZone(e.target.value)} required/></Field>
   <Button type="submit" className="h-auto min-h-11 whitespace-normal" disabled={ids.length<1||ids.length>10}>Analyze these calendars and dates</Button><Button type="button" variant="ghost" onClick={()=>{setForm(false);onSkip();}}>Choose preferences manually</Button>
  </FieldSet></form>:null}
  {scan?<p role="status">{({running:'Analysis is running. Reload to check its result; after 90 seconds you can retry.',failed:'Analysis did not complete. No missing data is treated as free time. Retry or use manual preferences.',stale:'Calendar or setup changed. Run a fresh analysis or edit preferences manually.',expired:'These suggestions expired. Analyze again or use manual preferences.',dismissed:'Suggestions dismissed. The same result will stay dismissed unless its evidence changes.',applied:'Suggested schedule added to your draft. Explicit choices were preserved; settings still need confirmation.',ready:'Your private suggestions are ready.'})[scan.status]}</p>:null}
  {summary&&scan?<><p>{scan.scope.startDate}–{scan.scope.endDate} (end exclusive) · {scan.scope.timezone} · {scan.scope.calendarIds.length} selected calendars</p>
   <p>{summary.eventCount} busy event entries. {summary.windowSource==='calendar'?'Suggested two-hour gaps were clear on at least 75% of matching weekdays in the scanned range.':summary.windowSource==='starter'?'Sparse calendar evidence: these weekday afternoons are starter defaults.':'No consistent two-hour weekday gap was found; choose your own times.'} The search frame is weekdays 09:00–18:00. These are preferences to review, not reserved or guaranteed availability.</p>
   {summary.windows.map((w,i)=><p key={i}>{w.days.map(d=>dayNames[d]).join(', ')} · {w.start}–{w.end}</p>)}
   <p>Starter defaults for missing fields: 30-minute meetings and a 10-minute meeting buffer. Existing explicit and confirmed values take precedence.</p>
   <p>{summary.onlineCount} entries include a video link; {summary.physicalCount} include a usable place. Choose Online, In person or Either in your mode step; observations do not answer for you.</p>
   {summary.locations.length?<><p>Repeated places, quoted from your selected calendars. These are private candidates, not inferred home/work or saved venues. Edit location below to choose a place or decide per meeting.</p>{summary.locations.map((p,i)=><p key={i} className="break-words">“{p.label}” · {p.count} entries</p>)}</>:<p>No repeated usable location was found. Choose a place or decide per meeting.</p>}
   {summary.limitations.includes('mixed_timezones')?<p>Calendar timezones differ; all gaps are shown in the analysis timezone.</p>:null}
   {summary.limitations.includes('missing_locations')?<p>Some entries have no usable location; they cannot establish a venue or transportation preference.</p>:null}
   {scan.status==='ready'?<div className="flex flex-wrap gap-2"><Button className="h-auto min-h-11 w-full whitespace-normal" disabled={locked||summary.windows.length===0} onClick={()=>void mutate('apply',{scanId:scan.id,expectedRevision:setup.revision})}>Use suggested schedule in draft</Button><Button variant="outline" disabled={locked} onClick={()=>void mutate('dismiss',{scanId:scan.id,expectedRevision:setup.revision})}>Dismiss these suggestions</Button></div>:null}
  </>:null}
  {scan||error?<Button variant="ghost" disabled={locked} onClick={()=>{pending.current=null;setError('');void call('analysis/read').then(data=>setState(analysisState.parse(data))).then(onChange).catch(e=>setError(e.message));}}>Reload analysis</Button>:null}
  {error?<p role="alert" className="text-destructive">{error}</p>:null}
 </section>;
}
