"use client";
import { useState, type FormEvent } from "react";
export default function RequestForm({ fixedDuration }: { fixedDuration: number | null }) {
  const [name, setName] = useState(""); const [purpose, setPurpose] = useState(""); const [duration, setDuration] = useState("60"); const [location, setLocation] = useState("");
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError("");
    try { const response = await fetch("/api/requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, purpose, duration: fixedDuration ?? Number(duration), location }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "요청을 저장하지 못했습니다."); setSent(true); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "요청을 저장하지 못했습니다."); }
    finally { setLoading(false); }
  }
  if (sent) return <div className="mt-8 rounded-2xl bg-emerald-50 p-6"><h2 className="text-xl font-semibold text-emerald-900">미팅 요청을 보냈어요</h2><p className="mt-2 leading-7 text-emerald-800">일정 소유자가 두 Google Calendar를 확인하고 가능한 후보 시간을 검토할 거예요. 소유자가 수락하면 연결한 Google 계정 이메일로 일정 초대를 보내도록 요청합니다.</p></div>;
  return <form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-medium text-slate-800">이름<input required maxLength={100} value={name} onChange={(e) => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /></label><label className="block text-sm font-medium text-slate-800">미팅 목적<input required maxLength={500} value={purpose} onChange={(e) => setPurpose(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="예: 파트너십 논의" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-800">소요 시간{fixedDuration ? <div className="mt-2 rounded-xl bg-slate-100 px-4 py-3">{fixedDuration}분 · 호스트가 정한 길이</div> : <select value={duration} onChange={(e) => setDuration(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"><option value="30">30분</option><option value="45">45분</option><option value="60">1시간</option><option value="90">1시간 30분</option></select>}</label><label className="block text-sm font-medium text-slate-800">희망 장소<input maxLength={200} value={location} onChange={(e) => setLocation(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="예: 강남역 인근, 온라인" /></label></div><p className="text-xs leading-5 text-slate-500">장소가 다르다고 감지되면 이동 여유 45분, 장소가 같거나 불명확하면 15분을 고려합니다. Google Maps 이동 시간은 사용하지 않습니다.</p>{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={loading} className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-60">{loading ? "캘린더 확인 중…" : "미팅 요청 보내기"}</button></form>;
}
