name: Check
on:
  push:
  pull_request:
jobs:
  application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.9.1
      - run: npm ci
      - run: npm run check
  database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: 2.119.0
      - run: supabase start
      - run: supabase db reset --local
      - run: supabase test db
